/**
 * English source copy. French and Italian files mirror this exact shape;
 * the build fails loudly if a key goes missing.
 *
 * NOTE FOR THE CLIENT: the `testimonials` entries are placeholders written to
 * show the layout. Replace them with real traveller reviews before launch.
 */
module.exports = {
  code: 'en',
  htmlLang: 'en',

  nav: {
    home: 'Home',
    experiences: 'Experiences',
    destinations: 'Destinations',
    gallery: 'Gallery',
    about: 'About Us',
    guide: 'Travel Guide',
    contact: 'Contact',
    reviews: 'Reviews',
    cta: 'WhatsApp',
    menu: 'Menu',
    close: 'Close',
    language: 'Language',
  },

  ui: {
    explore: 'Explore',
    exploreExperience: 'Explore experience',
    book: 'Book this experience',
    plan: 'Plan your adventure',
    viewAll: 'View all experiences',
    viewGallery: 'Open the gallery',
    location: 'Location',
    duration: 'Duration',
    season: 'Best season',
    group: 'Group',
    included: 'What’s included',
    bring: 'What to bring',
    priceFrom: 'from',
    highlights: 'Highlights',
    journey: 'What travellers experience',
    photos: 'Photographs',
    story: 'The story',
    history: 'History',
    whyVisit: 'Why visit',
    moments: 'Best moments',
    info: 'Travel information',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    scroll: 'Scroll',
    readMore: 'Read more',
    all: 'All',
    talkToUs: 'Talk to us on WhatsApp',
    writeUs: 'Write to us',
  },

  meta: {
    home: {
      title: 'Travel and Trips in Mauritania — Sahara & Iron Ore Train',
      desc: 'Private, locally guided journeys through the Sahara, the ancient cities of Chinguetti and Ouadane, the legendary iron ore train and the Banc d’Arguin.',
    },
    experiences: {
      title: 'Experiences — Iron Ore Train, Sahara & Ancient Cities',
      desc: 'Five signature journeys in Mauritania: the iron ore train, a Sahara desert expedition, Chinguetti, Ouadane and the Banc d’Arguin National Park. Private departures, local guides.',
    },
    destinations: {
      title: 'Destinations — Chinguetti, Ouadane, Adrar, Banc d’Arguin',
      desc: 'Where to go in Mauritania: the Adrar plateau, the UNESCO ksour of Chinguetti and Ouadane, the Sahara, the iron ore railway, Banc d’Arguin and Nouakchott.',
    },
    gallery: {
      title: 'Gallery — Photographs from our journeys in Mauritania',
      desc: 'A cinematic photo journey through Mauritania: the iron ore train, desert crossings, ancient cities, Atlantic landscapes and the travellers who came with us.',
    },
    about: {
      title: 'About Us — A Mauritanian Travel Company',
      desc: 'We are a local Mauritanian travel company designing private journeys for international travellers, with our own guides, drivers and desert crews.',
    },
    guide: {
      title: 'Mauritania Travel Guide — Visas, Safety, When to Visit',
      desc: 'Practical, honest advice for travelling in Mauritania: visas, the best season, safety, culture, transport, money and the questions travellers ask us most.',
    },
    reviews: {
      title: 'Reviews — What travellers say on Google',
      desc: 'Real Google reviews from travellers who crossed Mauritania with us: the iron ore train, the Adrar, Chinguetti, Ouadane and the deep desert.',
    },
    contact: {
      title: 'Contact — Plan your journey to Mauritania',
      desc: 'Talk to a local expert on WhatsApp, by email or through our inquiry form. We answer every message personally, usually within a few hours.',
    },
  },

  hero: {
    line1: 'Discover Mauritania',
    line2: 'Beyond the Ordinary',
    sub: 'Experience ancient cities, endless deserts, and unforgettable journeys with local experts.',
    cta1: 'Explore Experiences',
    cta2: 'Plan Your Adventure',
    scroll: 'Scroll to begin',
    waMsg: 'Hello, I would like to plan an adventure in Mauritania with you.',
  },

  home: {
    intro: {
      eyebrow: 'The last great silence',
      title: 'A country the world has not learned to visit yet.',
      body: [
        'Mauritania is the size of Egypt and receives fewer visitors in a year than a single European museum receives in a week. Ninety percent of it is Sahara. The rest is Atlantic coastline, oasis valleys and towns of dry stone that were writing manuscripts on astronomy while Europe was still building cathedrals.',
        'There are no crowds here, no souvenir streets, no queue at the viewpoint. There is a country that still belongs entirely to the people who live in it — and a handful of us who know how to take you through it properly.',
      ],
      stats: [
        { n: '1 200 000', l: 'km² of desert, coast and silence' },
        { n: '2', l: 'UNESCO World Heritage sites' },
        { n: '704 km', l: 'of iron ore railway across the Sahara' },
        { n: '13th c.', l: 'the age of the libraries of Chinguetti' },
      ],
    },

    why: {
      eyebrow: 'Why travel with us',
      title: 'Built by Mauritanians, for travellers who want the real thing.',
      items: [
        {
          t: 'Local experts',
          d: 'Our guide Mohammed and the team are Mauritanian, and the routes are their own. The reviews on this page name him, not a company.',
          img: 'plateau-two-travellers',
        },
        {
          t: 'Authentic experiences',
          d: 'Bread baked in the sand, the three glasses of tea, nights with nomad families in the deep desert. It is how the journeys actually run.',
          img: 'desert-tea',
        },
        {
          t: 'Personalized journeys',
          d: 'Private departures, and daily departures from Nouakchott. Four days or nine, hotels or camps — the route is rebuilt around you.',
          img: 'camp-sunrise',
        },
        {
          t: 'Everything handled',
          d: '4×4 transport, professional local guide and driver, hotels and desert camps, all meals, tea and water throughout, entrance fees.',
          img: 'group-lunch-desert',
        },
      ],
    },

    featured: {
      eyebrow: 'Signature journeys',
      title: 'Five ways to meet Mauritania.',
      sub: 'Each one is private, guided by our own team, and can be extended, shortened or combined.',
    },

    destPreview: {
      eyebrow: 'Where we go',
      title: 'Seven places worth crossing a continent for.',
      cta: 'Explore destinations',
    },

    moments: {
      eyebrow: 'Traveller moments',
      title: 'Photographs from the people who came with us.',
      sub: 'Not one of these images is a stock photo. Every frame on this website was taken on one of our journeys.',
      cta: 'Open the full gallery',
    },

    reviews: {
      eyebrow: 'In their words',
      title: 'What travellers say when they get home.',
      cta: 'Read them on Google',
    },

    finalCta: {
      title: 'Your Mauritanian adventure begins here.',
      sub: 'Tell us when you want to travel and what you want to see.',
      cta1: 'Plan your adventure',
      cta2: 'See all experiences',
      waMsg: 'Hello, I would like to start planning my journey to Mauritania.',
    },
  },

  experiencesPage: {
    hero: {
      eyebrow: 'Signature journeys',
      title: 'Experiences',
      sub: 'Five journeys, each one private, each one led by our own guides. Choose one, or let us build a route that joins them together.',
    },
    outro: {
      title: 'None of these are quite right?',
      sub: 'Then tell us what you had in mind.',
      cta: 'Design a private journey',
      waMsg: 'Hello, I would like to design a private custom journey in Mauritania.',
    },
  },

  experiences: [
    {
      id: 'ouadane-caravan-city',
      title: 'Ouadane — The Forgotten Caravan City',
      tagline: 'If you want to feel like you have gone back 800 years, Ouadane is the place.',
      short: 'A UNESCO ghost town in the heart of the Sahara, founded in the 11th century, reached across the Adrar plateau.',
      location: 'Nouakchott → Atar → Ouadane',
      duration: '4 days / 3 nights',
      season: '',
      group: 'Daily departures from Nouakchott',
      price: '€950',
      priceNote: 'per person',
      audience: 'Best for history lovers, photographers, and seekers of silence',
      hero: 'ouadane-doorway-valley',
      gallery: ['ouadane-archway', 'ruins-gathering', 'red-hills-road', 'desert-tea', 'night-tent-stars', 'camp-sunrise'],
      story: [
        'One of Mauritania’s oldest cities and a UNESCO World Heritage Site: a historic ghost town in the heart of the Sahara, and a key stop on the caravan route between Morocco and West Sudan.',
        'Founded in the 11th century, it was a centre for gold, salt and the book trade. Today it is abandoned, but its stone buildings, ancient mosques and old libraries still speak of its great past.',
        'The silence here is heavy. You can hear the echo of your own footsteps.',
      ],
      highlights: [
        'The ancient mosque, collapsed stone houses and the ruins of the Portuguese fort',
        'Libraries that once held 500-year-old manuscripts',
        'Ouadane Valley and the old water well — the view of the city from above',
        'Sunrise over the ruins, the best light of the whole trip',
        'Two nights in a traditional desert camp, sleeping under a sky full of stars',
      ],
      journey: [
        { t: 'Day 1 — Nouakchott → Atar', d: '7:00 AM pickup from your hotel or the airport. 4×4 across the desert to Atar with stops for tea and photographs in the dunes. Dinner and overnight in Atar.' },
        { t: 'Day 2 — Atar → Ouadane', d: '8:00 AM departure, a 2.5-hour drive across the Adrar plateau of black stone mountains. Walking tour of the old city, desert lunch under an acacia, then Ouadane Valley and the old well. Night in a desert camp.' },
        { t: 'Day 3 — Ouadane', d: '6:00 AM sunrise over the ruins. A deeper walk through the hidden alleys and old quarters. Afternoon with nomad families when they are nearby. Dinner and stargazing at camp.' },
        { t: 'Day 4 — Ouadane → Atar → Nouakchott', d: 'Breakfast and a last walk around the city, back to Atar for lunch and the market, then the long drive south. Arrival in Nouakchott around 10:00 PM.' },
      ],
      included: [
        '4×4 transport Nouakchott – Ouadane – Nouakchott',
        'Professional local guide and driver',
        '1 night in a hotel in Atar, 2 nights in a desert camp',
        'All meals: breakfast, lunch and dinner',
        'Tea and water throughout',
        'Entrance fees',
      ],
      bring: 'Comfortable shoes for walking on stone, hat, sunglasses, sunscreen, camera, power bank.',
      waMsg: 'Hello, I am interested in the 4-day Ouadane tour (€950) from your website.',
    },
    {
      id: 'adrar-treasures',
      title: 'Adrar Treasures',
      tagline: 'Terjit Oasis, Chinguetti, and two days on camelback in the Erg Amatlich.',
      short: 'The real Mauritania: a hidden oasis, two UNESCO cities and a camel trek with no roads, no tourists and no network.',
      location: 'Nouakchott → Terjit → Chinguetti → Ouadane → Atar',
      duration: '7 days',
      season: '',
      group: 'Private departures',
      price: '€950',
      priceNote: 'per person',
      audience: 'Best for travellers who want the desert without the crowds',
      hero: 'oasis-rest-cliff',
      gallery: ['terjit-oasis-canyon', 'palms-in-dunes', 'chinguetti-minaret', 'erg-palm-line', 'camel-silhouette', 'milky-way-acacia'],
      story: [
        'Terjit is a small village built around a natural oasis: palm trees, a canyon, and fresh spring water you can swim in after a day of dust.',
        'Chinguetti is the seventh holy city of Islam and a UNESCO site, a key point on the trade routes that linked West Africa to the Mediterranean. Its libraries hold more than 3,000 books, some of them 1,400 years old.',
        'Then the roads stop. Two days on camelback through the dunes of the Erg Amatlich with a Bedouin team — bread baked in the sand, tea with nomads, private tents under the Milky Way.',
      ],
      highlights: [
        'Terjit Oasis — palm trees, canyon and natural spring water',
        'Chinguetti’s ancient libraries and 1,000-year-old manuscripts',
        'Two-day camel trek in the Erg Amatlich dunes',
        'Learning to bake bread in the sand and the nomad tea ceremony',
        'Ouadane ruins and the drive back through Atar',
      ],
      journey: [
        { t: 'Day 1 — Nouakchott', d: 'Airport pickup and hotel.' },
        { t: 'Day 2 — Nouakchott → Terjit Oasis', d: 'A five-hour 4×4 drive to the Adrar. Swimming in the spring, lunch under the palms, night in a traditional auberge by the oasis or camping.' },
        { t: 'Day 3 — Terjit → Chinguetti', d: 'Morning in the oasis, then on to Chinguetti: the ancient libraries, the stone city and the huge golden dunes. Sunset from the dunes, night in a guesthouse.' },
        { t: 'Days 4–5 — Deep desert camel trek', d: 'Meet the Bedouin team and the camels for two days in the Erg Amatlich. No roads, no tourists, no network — just silence and stars.' },
        { t: 'Day 6 — Desert → Ouadane → Atar', d: 'Sunrise over the dunes, camel ride back, then the UNESCO ghost city of Ouadane. Hotel in Atar with a hot shower.' },
        { t: 'Day 7 — Atar → Nouakchott', d: 'The Atar market for souvenirs, then the drive back to Nouakchott.' },
      ],
      included: [],
      bring: '',
      waMsg: 'Hello, I am interested in the 7-day Adrar Treasures tour (€950) from your website.',
    },
    {
      id: 'grand-crossing',
      title: 'The Grand Crossing',
      tagline: 'Oasis, holy city, the Eye of the Sahara, and a night with the nomads.',
      short: 'Nouakchott to Nouadhibou the long way: Terjit, Chinguetti, Ouadane, the Richat Structure and Ben Amera.',
      location: 'Nouakchott → Terjit → Chinguetti → Ouadane → Ben Amera → Nouadhibou',
      duration: '6 days',
      season: '',
      group: 'Private departures',
      price: '€850',
      priceNote: 'per person',
      audience: 'Best for a first, complete crossing of the country',
      hero: 'golden-dunes',
      gallery: ['eye-rock', 'oasis-palms-dunes', 'plateau-road', 'sand-canyon', 'dune-summit-people', 'camp-dinner-sunrise'],
      story: [
        'This is the route that shows the whole country in one journey. It starts in the capital and ends at the Atlantic, and in between it crosses every landscape Mauritania has.',
        'Ouadane is the closest point to the Richat Structure — the Eye of the Sahara — and the night after visiting it is spent with nomadic families, who are around four percent of the population, learning how desert life actually works.',
        'Further north, Ben Amera is the second largest monolith in the world, standing beside two mountains the Mauritanians call the male and the female.',
      ],
      highlights: [
        'Terjit oasis, built around a natural spring between two cliffs',
        'Chinguetti — the seventh city of Islam and its ancient libraries',
        'The Richat Structure, the Eye of the Sahara, from Ouadane',
        'A night with nomadic families in the deep desert',
        'Ben Amera, the second biggest monolith on earth',
        'Nouadhibou and its fishing harbour on the Atlantic',
      ],
      journey: [
        { t: 'Day 1 — Arrival', d: 'Pickup at Nouakchott airport.' },
        { t: 'Day 2 — Nouakchott → Terjit', d: 'To the Adrar and the oasis village of Terjit.' },
        { t: 'Day 3 — Terjit → Chinguetti', d: 'The seventh city of Islam: libraries of more than 3,000 books, some 1,400 years old.' },
        { t: 'Day 4 — Chinguetti → Ouadane', d: 'One of the oldest cities in Mauritania and the closest point to the Eye of the Sahara. Night with nomadic families.' },
        { t: 'Day 5 — Ouadane → Ben Amera', d: 'The second biggest monolith in the world, and the two mountains beside it.' },
        { t: 'Day 6 — Ben Amera → Nouadhibou', d: 'North to the second city of Mauritania and its fishing fleet.' },
      ],
      included: [],
      bring: '',
      waMsg: 'Hello, I am interested in the 6-day crossing to Nouadhibou (€850) from your website.',
    },
    {
      id: 'iron-ore-train',
      title: 'The Iron Ore Train',
      tagline: 'One of the longest and heaviest trains in the world, and you can ride on top of it.',
      short: 'Over 700 km from the mines of Zouérat to the port of Nouadhibou, 15 to 20 hours across the Sahara.',
      location: 'Zouérat → Choum → Nouadhibou',
      duration: '15 – 20 hours on the train',
      season: 'November to February',
      group: 'Guided, added to any itinerary',
      price: '€950',
      priceNote: 'per person',
      audience: 'Best for the thrill, the scenery and the photography',
      hero: 'ore-train-aerial',
      gallery: ['train-riders', 'ore-train-sunset', 'ore-train-wagons', 'train-arms-open', 'iron-ore-train-mono', 'ore-train-yard'],
      story: [
        'The Mauritania iron ore train is one of the longest and heaviest trains in the world, travelling over 700 kilometres from the mining town of Zouérat to the coastal port of Nouadhibou. It carries iron ore across the Sahara and takes about 15 to 20 hours.',
        'Travellers ride it for adventure — often sitting on top of the open ore wagons, free of charge, or in a basic passenger car.',
        'It is a harsh journey: dust, extreme temperatures and long hours. People do it for the thrill, the scenery, the photography, and to experience one of the world’s most rugged rail journeys.',
      ],
      highlights: [
        'Over 700 km of open Sahara by rail',
        'Sunset, night and sunrise from an open ore wagon',
        'Arrival at the Atlantic in Nouadhibou',
        'One of the great photographic journeys anywhere',
      ],
      journey: [],
      included: [],
      bring: 'Goggles, scarf, warm clothes, water and snacks.',
      waMsg: 'Hello, I am interested in the iron ore train experience (€950) from your website.',
    },
  ],

  destinationsPage: {
    hero: {
      eyebrow: 'Where we go',
      title: 'Destinations',
      sub: 'Seven landscapes that together explain what Mauritania is: the desert, the stone cities that grew inside it, and the ocean that finally stops it.',
    },
  },

  destinations: [
    {
      id: 'chinguetti',
      name: 'Chinguetti',
      sub: 'The seventh city of Islam',
      img: 'chinguetti-minaret',
      photos: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove'],
      story: 'A caravan town half-swallowed by the dunes, where stone houses, a 13th-century minaret and thousands of hand-written manuscripts survive under the sand. UNESCO World Heritage since 1996.',
      history: 'Founded around 1264 as a staging post for pilgrims and traders crossing to Mecca, Chinguetti became a centre of Islamic scholarship so important that Mauritania was once known simply as “the land of Chinguetti”. Its libraries hold works on astronomy, jurisprudence, grammar and medicine copied by hand across seven centuries.',
      why: [
        'The oldest continuously used mosque minaret in the country',
        'Family libraries where manuscripts are still kept and read',
        'An old quarter being slowly reclaimed by the erg',
      ],
      moments: [
        'The call to prayer echoing off stone walls at first light',
        'Turning the page of a 700-year-old astronomy manuscript',
        'Sunset from the dunes with the whole town below you',
      ],
      info: [
        ['Getting there', '1 hour from Atar by 4×4; Atar is reachable by road or by seasonal flight'],
        ['Time needed', '1 – 2 nights'],
        ['Best season', 'October to April'],
        ['Pair it with', 'Ouadane, the Adrar dunes, the Richat Structure'],
      ],
    },
    {
      id: 'ouadane',
      name: 'Ouadane',
      sub: 'The stone city of 1147',
      img: 'ouadane-archway',
      photos: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon'],
      story: 'A ruined medieval town of dry-stone streets built on a cliff above a palm valley — the most spectacular of Mauritania’s four ancient ksour, and the emptiest.',
      history: 'Founded in 1147 by Berber traders, Ouadane grew rich on the gold, salt and date trade and once housed thousands of people. When the caravan routes shifted in the 16th century the town began to empty, and the lower city was gradually abandoned to the desert. It has been UNESCO listed since 1996.',
      why: [
        'An entire abandoned town built without mortar, still standing',
        'The gateway to the Richat Structure, the “Eye of the Sahara”',
        'Almost no other visitors, on almost any day of the year',
      ],
      moments: [
        'Walking up the stepped alleys as the stone turns gold',
        'Standing on the highest terrace above the palm valley',
        'The two-hour drive across black plateau to get there',
      ],
      info: [
        ['Getting there', '2 – 3 hours from Chinguetti across the plateau by 4×4'],
        ['Time needed', '1 night'],
        ['Best season', 'October to April'],
        ['Pair it with', 'The Richat Structure, Chinguetti, the great ergs'],
      ],
    },
    {
      id: 'adrar',
      name: 'Adrar Region',
      sub: 'Plateaux, canyons and palm valleys',
      img: 'terjit-oasis-canyon',
      photos: ['adrar-road-mesa', 'palm-grove', 'plateau-two-travellers', 'oasis-stone-wall'],
      story: 'The heart of Saharan Mauritania: a high plateau of black rock cut by canyons, with hidden oases of date palms and warm springs at the bottom of the gorges.',
      history: 'The Adrar has been inhabited for thousands of years — neolithic tools and rock engravings are still found on its plateaux. It was the cradle of the caravan cities and remains the cultural centre of the Mauritanian Sahara, with Atar as its capital.',
      why: [
        'Oasis canyons where warm springs feed palm forests',
        'The most dramatic desert scenery in the country',
        'The base for Chinguetti, Ouadane and the great dunes',
      ],
      moments: [
        'Swimming in a spring at the bottom of a gorge after a day of dust',
        'The first sight of green from the top of a canyon wall',
        'Date harvest in the palm gardens in July',
      ],
      info: [
        ['Getting there', '6 hours by road from Nouakchott, or a seasonal flight to Atar'],
        ['Time needed', '3 – 7 days'],
        ['Best season', 'November to March'],
        ['Pair it with', 'Everything — this is where most journeys are built'],
      ],
    },
    {
      id: 'sahara',
      name: 'The Sahara Desert',
      sub: 'Ergs, silence and nomad camps',
      img: 'camel-caravan-dune',
      photos: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'lone-vehicle-plain'],
      story: 'Ninety percent of Mauritania is desert, and a large part of it has never been mapped in any detail. This is where the journeys go quiet.',
      history: 'The Sahara was green as recently as 6,000 years ago; rock paintings of cattle and giraffes survive in the interior. The nomadic culture that replaced it — camel caravans, tents, the tea ceremony, poetry recited at night — is still alive here in a way it no longer is in most of North Africa.',
      why: [
        'Dunes and sand seas with no other group in sight',
        'Nights under a sky with zero light pollution',
        'Camel caravans that still work the old routes',
      ],
      moments: [
        'The moment the engines stop and you hear absolutely nothing',
        'Walking barefoot on a dune crest at sunrise',
        'The third glass of tea, an hour after the first',
      ],
      info: [
        ['Getting there', 'By 4×4 with a licensed desert guide — always'],
        ['Time needed', '2 – 9 days'],
        ['Best season', 'November to March'],
        ['Pair it with', 'Chinguetti, Ouadane, the ore train'],
      ],
    },
    {
      id: 'iron-ore-route',
      name: 'Iron Ore Train Route',
      sub: '704 km of rail across the desert',
      img: 'iron-ore-train-mono',
      photos: ['train-riders', 'train-arms-open', 'train-night-rest'],
      story: 'One line, one direction, up to 220 wagons: the railway that carries iron from Zouérat to the Atlantic, and carries travellers who ask nicely.',
      history: 'Built between 1960 and 1963 to move ore from the mines of Zouérat to the port of Nouadhibou, the line crosses 704 kilometres of open Sahara. It was engineered to survive sand, heat and total isolation, and it has run almost without interruption for sixty years.',
      why: [
        'One of the world’s last genuinely free legendary journeys',
        'Sunset, night and sunrise from an open ore wagon',
        'A crossing of the empty quarter of the Sahara',
      ],
      moments: [
        'Hearing the train before you can see it',
        'The first hour, standing up, with the wind and the light',
        'Arriving at the ocean covered in iron dust',
      ],
      info: [
        ['Getting there', 'We meet the line near Choum, by 4×4 from Atar'],
        ['Time needed', '2 – 3 days including transfers'],
        ['Best season', 'October to April — never in summer'],
        ['Pair it with', 'Nouadhibou, Banc d’Arguin, the Adrar'],
      ],
    },
    {
      id: 'banc-darguin',
      name: 'Banc d’Arguin National Park',
      sub: 'Two million birds between desert and ocean',
      img: 'arguin-pelicans',
      photos: ['arguin-birds-shore', 'camels-atlantic', 'beach-convoy'],
      story: 'A 12,000 km² World Heritage park of sandbanks, shallow water and dunes, where the Sahara ends in the Atlantic and migratory birds arrive in their millions.',
      history: 'Created in 1976 and UNESCO listed in 1989, the park protects the wintering grounds of birds from as far away as Siberia. The Imraguen people, the only community allowed to fish inside it, still use traditional sailing lanches and a fishing method assisted by wild dolphins.',
      why: [
        'One of the richest bird sites on the planet',
        'Sailing with Imraguen fishermen',
        'Camels walking the surf line at low tide',
      ],
      moments: [
        'Thousands of pelicans lifting off at once',
        'Driving the wet sand with the ocean beside the wheels',
        'Fish grilled on the beach as the sun goes down',
      ],
      info: [
        ['Getting there', '3 – 4 hours north of Nouakchott by 4×4, permit required'],
        ['Time needed', '2 – 4 days'],
        ['Best season', 'November to April for migratory birds'],
        ['Pair it with', 'Nouadhibou, the ore train, Nouakchott'],
      ],
    },
    {
      id: 'nouakchott',
      name: 'Nouakchott',
      sub: 'The capital on the sand',
      img: 'nouakchott-fish-market',
      photos: ['atlantic-sunset-group', 'beach-arrival', 'ocean-silhouettes'],
      story: 'A city that was a village of a few hundred people in 1958 and is now home to a third of the country — flat, low, sand-coloured, and far more interesting than it first looks.',
      history: 'Chosen as the capital at independence in 1960 precisely because it belonged to nobody, Nouakchott grew explosively as drought pushed nomadic families off the land. Its fishing beach, camel market and craft centres are the best introduction to modern Mauritanian life.',
      why: [
        'The Port de Pêche, one of West Africa’s great spectacles',
        'Markets, silverwork and the national museum',
        'The gateway to everywhere else in the country',
      ],
      moments: [
        'Hundreds of pirogues landing the catch onto the sand',
        'Sunset on the Atlantic beach with the whole city out walking',
        'Your first glass of Mauritanian tea',
      ],
      info: [
        ['Getting there', 'International flights to Nouakchott–Oumtounsy (NKC)'],
        ['Time needed', '1 day at the start or end of a journey'],
        ['Best season', 'Year-round; coastal air stays mild'],
        ['Pair it with', 'Banc d’Arguin, the Adrar, the ore train'],
      ],
    },
  ],

  galleryPage: {
    hero: {
      eyebrow: 'Photographs',
      title: 'Gallery',
      sub: 'Every photograph on this website was taken on one of our journeys, by our guides and by the travellers who came with us.',
      scroll: 'Begin the journey',
    },
    chapters: {
      train: { n: '01', t: 'Iron Ore Train', d: 'Twelve hours on an open wagon, from the mines of Zouérat to the Atlantic.' },
      desert: { n: '02', t: 'Desert Journeys', d: 'Ergs, bivouacs, caravans, and the silence people cross a continent to hear.' },
      culture: { n: '03', t: 'Culture', d: 'Stone cities, family libraries, shared meals and eight centuries of hospitality.' },
      landscapes: { n: '04', t: 'Landscapes', d: 'Canyons, oases, sandbanks and the place where the Sahara falls into the ocean.' },
      travellers: { n: '05', t: 'Travellers', d: 'The people who came with us, and what this country did to them.' },
    },
    ui: { openImage: 'Open photograph', of: 'of', jump: 'Jump to chapter' },
  },

  aboutPage: {
    hero: {
      eyebrow: 'Who we are',
      title: 'A Mauritanian company, in a country that needed one.',
      sub: 'Travel and Trips in Mauritania exists so that travellers arriving here meet the country through the people who live in it.',
      img: 'flag-and-camels',
    },
    story: {
      eyebrow: 'Our story',
      title: 'Our story',
      body: [],
      img: 'guide-and-traveller-ridge',
    },
    pillars: {
      eyebrow: 'What we stand for',
      title: 'What we stand for',
      items: [],
    },
    guides: {
      eyebrow: 'Our guides',
      title: 'Our guides',
      body: [],
      img: 'plateau-two-travellers',
      stats: [],
    },
    safety: {
      eyebrow: 'Travelling safely',
      title: 'Travelling safely',
      items: [],
      img: 'beach-convoy',
    },
    mission: {
      eyebrow: 'Our mission',
      quote: 'To show Mauritania to the world without changing what makes it worth showing.',
      body: '',
      cta: 'Plan your journey with us',
      waMsg: 'Hello, I would like to plan a journey in Mauritania.',
    },
  },

  guidePage: {
    hero: {
      eyebrow: 'Before you come',
      title: 'Mauritania Travel Guide',
      sub: 'Everything travellers ask us, answered honestly. If something here is still unclear, message us — we answer personally.',
      img: 'adrar-road-mesa',
    },
    sections: [
      {
        id: 'when',
        t: 'Best time to visit Mauritania',
        body: [
          'The season runs from **October to April**. Days are 22–32 °C, nights in the desert drop to 8–15 °C, and the light is at its best. December and January are the coolest and the most popular months.',
          'From **May to September** the interior regularly exceeds 45 °C and desert travel becomes genuinely unpleasant and, in places, unsafe.',
          'The **harmattan**, a dry dust wind, can reduce visibility for a few days between December and February. The coast stays milder and windier all year, so Banc d’Arguin and Nouakchott remain comfortable outside the deep summer.',
        ],
      },
      {
        id: 'visa',
        t: 'Visas and entry',
        body: [
          'Most European and North American travellers can obtain a **visa on arrival** at Nouakchott–Oumtounsy International Airport and at the main land borders. It is issued on the spot, typically valid for 30 days, and paid in **cash euros**.',
          'You will need a passport valid for at least six months, an onward or return ticket and an address in the country.',
          'Rules and fees can change without much notice, and some nationalities need a visa in advance. Check the current requirement for your own passport before booking.',
        ],
      },
      {
        id: 'pack',
        t: 'What to pack',
        body: [
          '**Clothing.** Light, loose, covering layers for the day; a warm fleece or jacket and long trousers for desert nights, which are genuinely cold from December to February. A scarf or *chèche* is the single most useful item you will own — for sun, dust and wind.',
          '**Feet.** Closed walking shoes plus sandals for camp and sand. Bring more socks than you think.',
          '**Sun and dust.** High-factor sunscreen, lip balm, sunglasses, and a dust-proof bag or dry bag for cameras — the fine sand gets everywhere.',
          '**Practical.** Headlamp, power bank (there is no electricity in the bivouac), universal adapter, refillable bottle, personal medication, wet wipes, and a small first-aid kit.',
          '**Money.** Bring euros in cash. Cards are accepted almost nowhere outside a few hotels in Nouakchott, and ATMs are unreliable. The local currency is the ouguiya (MRU).',
        ],
      },
      {
        id: 'safety',
        t: 'Safety in Mauritania',
        body: [
          'Mauritania is calm, and the regions travellers visit — Nouakchott, the Atlantic coast, the Adrar, the railway corridor — are considered stable and are regularly travelled by European visitors. Violent crime against tourists is very rare, and the culture of hospitality towards guests is extremely strong.',
          'The real risks here are environmental, not political: heat, dehydration, soft sand and distance from medical help. That is why desert travel is done with licensed guides and properly equipped vehicles, never independently.',
          'Take normal travel insurance that covers desert travel, and follow your own government’s current advice before you book.',
        ],
      },
      {
        id: 'culture',
        t: 'Culture and traditions',
        body: [
          'Mauritania is an Islamic republic, and daily life follows it: five prayers, Friday as the day of rest, **no alcohol anywhere in the country**, and a month of fasting during Ramadan when eating and drinking in public during daylight is not done.',
          'Dress modestly — shoulders and knees covered for everyone. Women do not need to cover their hair, though a scarf is useful and appreciated in villages and mosques.',
          'Greet people before asking anything: a handshake and a few words about health and family come before business. Always accept tea if it is offered; the three glasses take an hour and refusing them is the one thing that genuinely surprises people.',
          '**Photography.** Ask before photographing anyone, especially women, and accept no as an answer. Never photograph military posts, checkpoints or government buildings. Your guide will tell you when it is fine.',
          'Eat and pass with the right hand. And if you are invited into someone’s home, you will be fed far more than you can manage — that is not optional.',
        ],
      },
      {
        id: 'transport',
        t: 'Getting around',
        body: [
          '**Flights.** Nouakchott–Oumtounsy (NKC) is the main gateway, with connections from Paris, Casablanca, Istanbul, Madrid and Dakar. Seasonal charters sometimes fly directly to Atar in winter.',
          '**By road.** The Nouakchott–Atar road is tarmac and takes around six hours. Beyond it, everything is piste and requires 4×4. Distances are long and fuel stations are far apart.',
          '**The ore train.** Free, unforgettable and completely unregulated. It is not something to attempt without a guide, equipment and food.',
        ],
      },
    ],
    faqTitle: 'Frequently asked questions',
    faq: [
      { q: 'Is Mauritania safe for tourists?', a: 'The regions travellers visit — Nouakchott, the Atlantic coast, the Adrar and the railway corridor — are calm and regularly travelled by European visitors, and violent crime against tourists is very rare. The real risks are environmental: heat, dehydration, soft sand and distance from medical help, which is why desert travel is done with licensed guides and properly equipped vehicles. Read your own government’s current advice before you book.' },
      { q: 'Do I need a visa?', a: 'Most European and North American travellers receive a visa on arrival at Nouakchott–Oumtounsy International Airport and at the main land borders, issued on the spot, typically valid 30 days and paid in cash euros. Rules change, and some nationalities need one in advance — check for your own passport before booking.' },
      { q: 'When is the best time to come?', a: 'October to April. Days are 22–32 °C and desert nights drop to 8–15 °C. December and January are the coolest. From May to September the interior regularly passes 45 °C.' },
      { q: 'Can I really ride the iron ore train?', a: 'Yes. The train carries iron ore from Zouérat to Nouadhibou and travellers ride on top of the ore in the open wagons, free of charge. It takes roughly twelve hours, there is no shelter, and the desert night is genuinely cold.' },
      { q: 'Is there mobile signal and internet?', a: 'In towns, yes, and it is cheap. In the deep desert and on the train, no.' },
      { q: 'What is the money situation?', a: 'The local currency is the ouguiya (MRU). Bring euros in cash: cards are accepted almost nowhere outside a few hotels in Nouakchott, and ATMs are unreliable.' },
      { q: 'Is alcohol available?', a: 'No. Mauritania is an Islamic republic and alcohol is not sold anywhere in the country.' },
    ],
    cta: {
      title: 'Still have a question?',
      sub: 'Message us directly. We will get back to you.',
      cta: 'Ask us on WhatsApp',
      waMsg: 'Hello, I have a question about travelling in Mauritania.',
    },
  },

  contactPage: {
    hero: {
      eyebrow: 'Get in touch',
      title: 'Let’s plan your journey.',
      sub: 'Tell us who is travelling, roughly when, and what you would love to see. We will come back to you.',
      img: 'dune-sunset-crew',
    },
    methods: {
      whatsapp: { t: 'WhatsApp', d: 'The fastest way to reach us.', a: 'Start a conversation' },
      email: { t: 'Email', d: 'For detailed itineraries, documents and group bookings.', a: 'Write to us' },
      phone: { t: 'Phone', d: 'Call us directly.', a: 'Call now' },
      location: { t: 'Where we are', d: 'Nouakchott, Mauritania.', a: 'Open in Google Maps' },
    },
    map: { t: 'Find us', d: 'Our office is in Nouakchott. Tap the map for directions, opening hours and the full Google profile.' },
    form: {
      eyebrow: 'Inquiry',
      title: 'Tell us about your trip.',
      sub: 'This form opens WhatsApp with your message ready to send, so nothing gets lost in a spam folder.',
      name: 'Your name',
      namePh: 'Anna Rossi',
      email: 'Email',
      emailPh: 'you@example.com',
      country: 'Country',
      countryPh: 'Italy',
      people: 'Travellers',
      dates: 'Approximate dates',
      datesPh: 'February 2027, about 10 days',
      interest: 'What interests you most',
      interestOptions: ['Iron Ore Train Adventure', 'Sahara Desert Expedition', 'Chinguetti Heritage Journey', 'Ouadane Ancient City', 'Banc d’Arguin Discovery', 'A custom private journey', 'I am not sure yet'],
      message: 'Anything else we should know',
      messagePh: 'Fitness level, comfort preferences, dietary needs, special occasions…',
      submit: 'Send via WhatsApp',
      submitAlt: 'or send the same message by email',
      required: 'Please fill in your name and what interests you.',
      intro: 'Hello, I would like to plan a journey in Mauritania.',
    },
    promise: {
      t: 'What happens next',
      items: [],
    },
  },

  reviewsUi: {
    photo: 'photo',
    photos: 'photos',
    ownerReply: 'Response from the owner',
    onGoogle: 'Read on Google',
    reviewsOnGoogle: 'reviews on Google',
    viewProfile: 'See all reviews',
    prev: 'Previous review',
    next: 'Next review',
  },

  reviewsPage: {
    hero: {
      eyebrow: 'In their words',
      title: 'Reviews',
      sub: 'Every review below is a real Google review, shown exactly as it was written — in the reviewer’s own words, under their own name.',
      img: 'dune-summit-people',
    },
    cta: {
      title: 'Come and write the next one.',
      sub: 'Tell us when you would like to travel and we will build the route around you.',
      cta: 'Plan your journey',
      waMsg: 'Hello, I read your reviews and I would like to plan a journey in Mauritania.',
    },
  },

  footer: {
    tagline: 'Private, locally guided journeys through the Sahara, the ancient cities and the Atlantic coast of Mauritania.',
    explore: 'Explore',
    company: 'Company',
    contact: 'Contact',
    follow: 'Follow the journey',
    rights: 'All rights reserved.',
    built: 'Every photograph on this site was taken on our own journeys.',
    waMsg: 'Hello, I would like information about your journeys in Mauritania.',
  },

  a11y: {
    skip: 'Skip to content',
    heroSlides: 'Hero photographs',
    lightbox: 'Photograph viewer',
    menu: 'Main menu',
  },
};
