/** Copie française. Structure identique à en.js. */
module.exports = {
  code: 'fr',
  htmlLang: 'fr',

  nav: {
    home: 'Accueil',
    experiences: 'Expériences',
    destinations: 'Destinations',
    gallery: 'Galerie',
    about: 'À propos',
    guide: 'Guide de voyage',
    contact: 'Contact',
    cta: 'WhatsApp',
    menu: 'Menu',
    close: 'Fermer',
    language: 'Langue',
  },

  ui: {
    explore: 'Découvrir',
    exploreExperience: 'Découvrir l’expérience',
    book: 'Réserver cette expérience',
    plan: 'Préparez votre aventure',
    viewAll: 'Voir toutes les expériences',
    viewGallery: 'Ouvrir la galerie',
    location: 'Lieu',
    duration: 'Durée',
    season: 'Meilleure saison',
    group: 'Groupe',
    highlights: 'Points forts',
    journey: 'Ce que vivent les voyageurs',
    photos: 'Photographies',
    story: 'Le récit',
    history: 'Histoire',
    whyVisit: 'Pourquoi y aller',
    moments: 'Les plus beaux moments',
    info: 'Informations pratiques',
    close: 'Fermer',
    prev: 'Précédent',
    next: 'Suivant',
    scroll: 'Défiler',
    readMore: 'Lire la suite',
    all: 'Tout',
    talkToUs: 'Écrivez-nous sur WhatsApp',
    writeUs: 'Écrivez-nous',
  },

  meta: {
    home: {
      title: 'Travel and Trips in Mauritania — Sahara & train du fer',
      desc: 'Voyages privés guidés par des Mauritaniens : le Sahara, les cités anciennes de Chinguetti et Ouadane, le train du fer et le Banc d’Arguin.',
    },
    experiences: {
      title: 'Expériences — Train du fer, Sahara et cités anciennes',
      desc: 'Cinq voyages signature en Mauritanie : le train du fer, l’expédition saharienne, Chinguetti, Ouadane et le parc national du Banc d’Arguin. Départs privés, guides locaux.',
    },
    destinations: {
      title: 'Destinations — Chinguetti, Ouadane, Adrar, Banc d’Arguin',
      desc: 'Où aller en Mauritanie : le plateau de l’Adrar, les ksour UNESCO de Chinguetti et Ouadane, le Sahara, la voie ferrée du fer, le Banc d’Arguin et Nouakchott.',
    },
    gallery: {
      title: 'Galerie — Photographies de nos voyages en Mauritanie',
      desc: 'Un voyage photographique en Mauritanie : le train du fer, les traversées du désert, les cités anciennes, l’Atlantique et les voyageurs qui nous ont accompagnés.',
    },
    about: {
      title: 'À propos — Une agence mauritanienne | Travel and Trips in Mauritania',
      desc: 'Nous sommes une agence de voyage mauritanienne qui conçoit des voyages privés pour les voyageurs internationaux, avec nos propres guides, chauffeurs et équipes du désert.',
    },
    guide: {
      title: 'Guide de voyage Mauritanie — Visa, sécurité, saison',
      desc: 'Conseils pratiques et honnêtes pour voyager en Mauritanie : visa, saison, sécurité, culture, transports, argent et les questions que l’on nous pose le plus.',
    },
    contact: {
      title: 'Contact — Préparez votre voyage en Mauritanie',
      desc: 'Parlez à un expert local sur WhatsApp, par e-mail ou via notre formulaire. Nous répondons personnellement à chaque message, généralement en quelques heures.',
    },
  },

  hero: {
    line1: 'Découvrez la Mauritanie',
    line2: 'Au-delà de l’ordinaire',
    sub: 'Cités anciennes, déserts infinis et voyages inoubliables, avec des experts locaux.',
    cta1: 'Découvrir les expériences',
    cta2: 'Préparez votre aventure',
    scroll: 'Faites défiler',
    waMsg: 'Bonjour, je souhaite préparer une aventure en Mauritanie avec vous.',
  },

  home: {
    intro: {
      eyebrow: 'Le dernier grand silence',
      title: 'Un pays que le monde n’a pas encore appris à visiter.',
      body: [
        'La Mauritanie est grande comme l’Égypte et reçoit en une année moins de visiteurs qu’un seul musée européen en une semaine. Quatre-vingt-dix pour cent de son territoire est saharien. Le reste, c’est la côte atlantique, des vallées d’oasis et des villes de pierre sèche où l’on copiait des manuscrits d’astronomie quand l’Europe bâtissait encore ses cathédrales.',
        'Ici, pas de foule, pas de rue à souvenirs, pas de file d’attente au belvédère. Il y a un pays qui appartient encore entièrement à ceux qui y vivent — et quelques-uns d’entre nous qui savent vous y conduire comme il faut.',
      ],
      stats: [
        { n: '1 200 000', l: 'km² de désert, de côte et de silence' },
        { n: '2', l: 'sites inscrits au patrimoine mondial' },
        { n: '704 km', l: 'de voie ferrée à travers le Sahara' },
        { n: 'XIIIᵉ s.', l: 'l’âge des bibliothèques de Chinguetti' },
      ],
    },

    why: {
      eyebrow: 'Pourquoi voyager avec nous',
      title: 'Créée par des Mauritaniens, pour les voyageurs qui veulent le vrai.',
      items: [],
    },

    featured: {
      eyebrow: 'Voyages signature',
      title: 'Cinq façons de rencontrer la Mauritanie.',
      sub: 'Chacune est privée, encadrée par notre propre équipe, et peut être allongée, raccourcie ou combinée.',
    },

    destPreview: {
      eyebrow: 'Où nous allons',
      title: 'Sept lieux qui valent la traversée d’un continent.',
      cta: 'Découvrir les destinations',
    },

    moments: {
      eyebrow: 'Instants de voyage',
      title: 'Les photographies de ceux qui sont venus avec nous.',
      sub: 'Aucune de ces images n’est une banque d’images. Chaque photo de ce site a été prise pendant l’un de nos voyages.',
      cta: 'Ouvrir la galerie complète',
    },

    reviews: {
      eyebrow: 'En leurs mots',
      title: 'Ce que disent les voyageurs une fois rentrés.',
      cta: 'Les lire sur Google',
    },

    finalCta: {
      title: 'Votre aventure mauritanienne commence ici.',
      sub: 'Dites-nous quand vous voulez partir et ce que vous voulez voir.',
      cta1: 'Préparez votre aventure',
      cta2: 'Voir toutes les expériences',
      waMsg: 'Bonjour, je souhaite commencer à préparer mon voyage en Mauritanie.',
    },
  },

  experiencesPage: {
    hero: {
      eyebrow: 'Voyages signature',
      title: 'Expériences',
      sub: 'Cinq voyages, tous privés, tous encadrés par nos propres guides. Choisissez-en un, ou laissez-nous construire un itinéraire qui les relie.',
    },
    outro: {
      title: 'Aucun ne vous correspond tout à fait ?',
      sub: 'Alors dites-nous ce que vous aviez en tête.',
      cta: 'Concevoir un voyage privé',
      waMsg: 'Bonjour, je souhaite concevoir un voyage privé sur mesure en Mauritanie.',
    },
  },

  experiences: [
    {
      id: 'iron-ore-train',
      title: 'L’aventure du train du fer',
      tagline: 'Douze heures sur le plus long train du monde.',
      short: 'Montez sur un wagon de minerai ouvert au coucher du soleil et traversez le Sahara sur la voie ferrée la plus légendaire d’Afrique.',
      location: 'Choum → Nouadhibou',
      duration: '',
      season: '',
      group: '',
      hero: 'train-riders',
      gallery: ['iron-ore-train-mono', 'train-arms-open', 'train-night-rest', 'train-night-portrait'],
      story: [
        'Une fois par jour, un train pouvant atteindre trois kilomètres quitte les mines de Zouérat, chargé de minerai de fer, en direction de l’Atlantique. Ni guichet, ni siège, ni horaire fiable — et c’est l’un des derniers voyages gratuits qui restent sur cette planète.',
        'On monte à bord là où le désert croise la voie. Alors le Sahara se met à défiler : ocre, puis rose, puis violet, puis un ciel noir avec plus d’étoiles qu’on ne vous en a jamais montrées.',
        'Au matin, le train atteint l’océan à Nouadhibou, et tout le monde descend couvert de poussière de fer, incapable de cesser de sourire.',
      ],
      highlights: [],
      journey: [],
      waMsg: 'Bonjour, je suis intéressé(e) par l’aventure du train du fer vue sur votre site.',
    },
    {
      id: 'sahara-expedition',
      title: 'Expédition dans le Sahara',
      tagline: 'Dunes, bivouacs et un horizon qui n’arrive jamais.',
      short: 'Une traversée guidée des grands ergs de l’Adrar : dormir à la belle étoile et marcher avec les caravanes de chameaux.',
      location: 'Région de l’Adrar, Mauritanie centrale',
      duration: '',
      season: '',
      group: '',
      hero: 'camel-caravan-dune',
      gallery: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'dune-descent', 'lone-vehicle-plain', 'flag-and-camels'],
      story: [
        'C’est le Sahara que l’on imagine avant de l’avoir vu : des dunes couleur de braise, des plateaux de pierre noire, des lits d’oueds pleins d’acacias, et un silence si total qu’on entend son propre pouls la nuit.',
        'Le soir dans l’erg, c’est un feu, la cuisine au bois et trois verres de thé versés lentement pendant que la lumière s’en va.',
        'Aucune traversée ne ressemble à la suivante. Le vent déplace les dunes, et le mois décide quelles vallées gardent encore de l’eau.',
      ],
      highlights: [],
      journey: [],
      waMsg: 'Bonjour, je suis intéressé(e) par l’expédition dans le Sahara vue sur votre site.',
    },
    {
      id: 'chinguetti-heritage',
      title: 'Chinguetti, voyage au patrimoine',
      tagline: 'La septième ville de l’islam et les bibliothèques dans son sable.',
      short: 'Une cité caravanière du XIIIᵉ siècle où des familles conservent encore les manuscrits que leurs ancêtres ont portés à travers le désert.',
      location: 'Chinguetti, région de l’Adrar',
      duration: '',
      season: '',
      group: '',
      hero: 'chinguetti-minaret',
      gallery: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove', 'terjit-oasis-canyon'],
      story: [
        'Chinguetti fut fondée au XIIIᵉ siècle comme point de rassemblement des caravanes en route vers La Mecque, et devint l’un des grands centres du savoir au Sahara. Les érudits y venaient étudier l’astronomie, les mathématiques, le droit et la médecine.',
        'Aujourd’hui, la vieille ville est à demi ensevelie sous le sable, et les manuscrits sont toujours là — conservés dans des bibliothèques familiales, enveloppés d’étoffe, montrés par les descendants de ceux qui les ont copiés.',
        'Le vieux quartier se parcourt dans la lumière basse du matin. Les dunes au-dessus de la ville sont là où le jour finit.',
      ],
      highlights: [],
      journey: [],
      waMsg: 'Bonjour, je suis intéressé(e) par le voyage patrimonial à Chinguetti vu sur votre site.',
    },
    {
      id: 'ouadane-ancient-city',
      title: 'Ouadane, la cité ancienne',
      tagline: 'Mille ans de pierre sèche au-dessus d’une vallée verte.',
      short: 'Le plus spectaculaire des ksour mauritaniens : une ville en ruines accrochée à une falaise, fondée en 1147.',
      location: 'Ouadane, région de l’Adrar',
      duration: '',
      season: '',
      group: '',
      hero: 'ouadane-archway',
      gallery: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon', 'oasis-stone-wall'],
      story: [
        'Ouadane fut bâtie en 1147 sur la route caravanière qui portait l’or vers le nord et le sel vers le sud. À son apogée, c’était l’une des villes les plus riches du Sahara. Puis les routes se sont déplacées, et le désert a commencé à la reprendre.',
        'Ce qui reste est extraordinaire : des ruelles en escalier de pierre sèche, des portes et des escaliers encore debout, toute une ville basse en ruines au-dessus d’une vallée de palmiers-dattiers.',
        'C’est à deux heures de route à travers le plateau noir depuis Chinguetti, et presque personne n’y va. La plupart du temps, la cité est entièrement déserte.',
      ],
      highlights: [],
      journey: [],
      waMsg: 'Bonjour, je suis intéressé(e) par l’expérience de la cité ancienne de Ouadane vue sur votre site.',
    },
    {
      id: 'banc-darguin',
      title: 'Découverte du Banc d’Arguin',
      tagline: 'Là où le Sahara entre dans l’Atlantique.',
      short: 'Un sanctuaire UNESCO de bancs de sable et de hauts-fonds accueillant des millions d’oiseaux migrateurs — et des dromadaires sur la plage.',
      location: 'Parc national du Banc d’Arguin, côte atlantique',
      duration: '',
      season: '',
      group: '',
      hero: 'camels-atlantic',
      gallery: ['arguin-pelicans', 'arguin-birds-shore', 'beach-convoy', 'beach-arrival', 'atlantic-sunset-group', 'nouakchott-fish-market'],
      story: [
        'Le Banc d’Arguin est l’un des sites ornithologiques les plus importants au monde, un parc classé au patrimoine mondial où le désert se jette simplement dans les eaux froides de l’Atlantique. Deux millions d’oiseaux migrateurs y hivernent.',
        'Les familles de pêcheurs imraguen naviguent encore en lanche traditionnelle au-dessus des hauts-fonds, et à marée basse le sable dur de la ligne de marée devient une route, l’océan d’un côté, les dunes de l’autre.',
        'C’est le paysage le plus doux et le plus étrange de Mauritanie.',
      ],
      highlights: [],
      journey: [],
      waMsg: 'Bonjour, je suis intéressé(e) par la découverte du Banc d’Arguin vue sur votre site.',
    },
  ],

  destinationsPage: {
    hero: {
      eyebrow: 'Où nous allons',
      title: 'Destinations',
      sub: 'Sept paysages qui, ensemble, expliquent ce qu’est la Mauritanie : le désert, les cités de pierre nées en son sein, et l’océan qui finit par l’arrêter.',
    },
  },

  destinations: [
    {
      id: 'chinguetti',
      name: 'Chinguetti',
      sub: 'La septième ville de l’islam',
      img: 'chinguetti-minaret',
      photos: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove'],
      story: 'Une cité caravanière à demi avalée par les dunes, où subsistent sous le sable des maisons de pierre, un minaret du XIIIᵉ siècle et des milliers de manuscrits copiés à la main. Patrimoine mondial de l’UNESCO depuis 1996.',
      history: 'Fondée vers 1264 comme étape pour les pèlerins et les marchands en route vers La Mecque, Chinguetti devint un centre du savoir islamique si important que la Mauritanie fut longtemps appelée simplement « le pays de Chinguetti ». Ses bibliothèques conservent des ouvrages d’astronomie, de jurisprudence, de grammaire et de médecine copiés à la main pendant sept siècles.',
      why: [
        'Le plus ancien minaret encore en usage du pays',
        'Des bibliothèques familiales où les manuscrits sont toujours conservés et lus',
        'Un vieux quartier lentement repris par l’erg',
      ],
      moments: [
        'L’appel à la prière résonnant sur les murs de pierre à l’aube',
        'Tourner la page d’un manuscrit d’astronomie de 700 ans',
        'Le coucher du soleil depuis les dunes, toute la ville en contrebas',
      ],
      info: [
        ['Y aller', '1 heure d’Atar en 4×4 ; Atar est accessible par la route ou par vol saisonnier'],
        ['Durée conseillée', '1 – 2 nuits'],
        ['Meilleure saison', 'D’octobre à avril'],
        ['À combiner avec', 'Ouadane, les dunes de l’Adrar, la structure de Richat'],
      ],
    },
    {
      id: 'ouadane',
      name: 'Ouadane',
      sub: 'La cité de pierre de 1147',
      img: 'ouadane-archway',
      photos: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon'],
      story: 'Une ville médiévale en ruines, faite de ruelles de pierre sèche bâties sur une falaise au-dessus d’une palmeraie — le plus spectaculaire des quatre ksour anciens de Mauritanie, et le plus désert.',
      history: 'Fondée en 1147 par des marchands berbères, Ouadane s’enrichit du commerce de l’or, du sel et des dattes et compta plusieurs milliers d’habitants. Quand les routes caravanières se déplacèrent au XVIᵉ siècle, la ville commença à se vider et la cité basse fut peu à peu abandonnée au désert. Elle est inscrite à l’UNESCO depuis 1996.',
      why: [
        'Une ville abandonnée entière, bâtie sans mortier, toujours debout',
        'La porte d’entrée vers la structure de Richat, « l’Œil du Sahara »',
        'Presque aucun autre visiteur, presque tous les jours de l’année',
      ],
      moments: [
        'Monter les ruelles en escalier quand la pierre devient or',
        'Se tenir sur la plus haute terrasse au-dessus de la palmeraie',
        'Les deux heures de piste sur le plateau noir pour y arriver',
      ],
      info: [
        ['Y aller', '2 – 3 heures depuis Chinguetti à travers le plateau, en 4×4'],
        ['Durée conseillée', '1 nuit'],
        ['Meilleure saison', 'D’octobre à avril'],
        ['À combiner avec', 'La structure de Richat, Chinguetti, les grands ergs'],
      ],
    },
    {
      id: 'adrar',
      name: 'Région de l’Adrar',
      sub: 'Plateaux, canyons et vallées de palmiers',
      img: 'terjit-oasis-canyon',
      photos: ['adrar-road-mesa', 'palm-grove', 'plateau-two-travellers', 'oasis-stone-wall'],
      story: 'Le cœur de la Mauritanie saharienne : un haut plateau de roche noire entaillé de canyons, avec des oasis cachées de palmiers-dattiers et des sources chaudes au fond des gorges.',
      history: 'L’Adrar est habité depuis des millénaires — on y trouve encore des outils néolithiques et des gravures rupestres sur les plateaux. Berceau des cités caravanières, il reste le centre culturel du Sahara mauritanien, avec Atar pour capitale.',
      why: [
        'Des canyons-oasis où des sources chaudes nourrissent des palmeraies',
        'Les paysages désertiques les plus spectaculaires du pays',
        'La base pour Chinguetti, Ouadane et les grandes dunes',
      ],
      moments: [
        'Se baigner dans une source au fond d’une gorge après une journée de poussière',
        'La première tache de vert aperçue du haut d’une falaise',
        'La récolte des dattes dans les palmeraies en juillet',
      ],
      info: [
        ['Y aller', '6 heures de route depuis Nouakchott, ou un vol saisonnier vers Atar'],
        ['Durée conseillée', '3 – 7 jours'],
        ['Meilleure saison', 'De novembre à mars'],
        ['À combiner avec', 'Tout — c’est ici que se construisent la plupart des voyages'],
      ],
    },
    {
      id: 'sahara',
      name: 'Le désert du Sahara',
      sub: 'Ergs, silence et campements nomades',
      img: 'camel-caravan-dune',
      photos: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'lone-vehicle-plain'],
      story: 'Quatre-vingt-dix pour cent de la Mauritanie est désertique, et une grande partie n’a jamais été cartographiée en détail. C’est là que les voyages deviennent silencieux.',
      history: 'Le Sahara était vert il y a seulement 6 000 ans ; des peintures rupestres de bovins et de girafes subsistent à l’intérieur des terres. La culture nomade qui lui a succédé — caravanes, tentes, cérémonie du thé, poésie récitée la nuit — est encore vivante ici comme elle ne l’est plus dans la plupart de l’Afrique du Nord.',
      why: [
        'Des dunes et des mers de sable sans aucun autre groupe en vue',
        'Des nuits sous un ciel sans la moindre pollution lumineuse',
        'Des caravanes qui empruntent encore les anciennes routes',
      ],
      moments: [
        'L’instant où les moteurs s’arrêtent et où l’on n’entend absolument rien',
        'Marcher pieds nus sur une crête de dune au lever du jour',
        'Le troisième verre de thé, une heure après le premier',
      ],
      info: [
        ['Y aller', 'En 4×4 avec un guide saharien agréé — toujours'],
        ['Durée conseillée', '2 – 9 jours'],
        ['Meilleure saison', 'De novembre à mars'],
        ['À combiner avec', 'Chinguetti, Ouadane, le train du fer'],
      ],
    },
    {
      id: 'iron-ore-route',
      name: 'La ligne du train du fer',
      sub: '704 km de rail à travers le désert',
      img: 'iron-ore-train-mono',
      photos: ['train-riders', 'train-arms-open', 'train-night-rest'],
      story: 'Une voie, une direction, jusqu’à 220 wagons : la ligne qui transporte le fer de Zouérat jusqu’à l’Atlantique, et les voyageurs qui le demandent poliment.',
      history: 'Construite entre 1960 et 1963 pour acheminer le minerai des mines de Zouérat au port de Nouadhibou, la ligne traverse 704 kilomètres de Sahara ouvert. Conçue pour résister au sable, à la chaleur et à l’isolement total, elle fonctionne presque sans interruption depuis soixante ans.',
      why: [
        'L’un des derniers grands voyages véritablement gratuits au monde',
        'Coucher de soleil, nuit et aube depuis un wagon ouvert',
        'Une traversée du quart vide du Sahara',
      ],
      moments: [
        'Entendre le train bien avant de le voir',
        'La première heure, debout, avec le vent et la lumière',
        'Arriver à l’océan couvert de poussière de fer',
      ],
      info: [
        ['Y aller', 'Nous rejoignons la voie près de Choum, en 4×4 depuis Atar'],
        ['Durée conseillée', '2 – 3 jours, transferts compris'],
        ['Meilleure saison', 'D’octobre à avril — jamais en été'],
        ['À combiner avec', 'Nouadhibou, le Banc d’Arguin, l’Adrar'],
      ],
    },
    {
      id: 'banc-darguin',
      name: 'Parc national du Banc d’Arguin',
      sub: 'Deux millions d’oiseaux entre désert et océan',
      img: 'arguin-pelicans',
      photos: ['arguin-birds-shore', 'camels-atlantic', 'beach-convoy'],
      story: 'Un parc de 12 000 km² classé au patrimoine mondial, fait de bancs de sable, d’eaux peu profondes et de dunes, où le Sahara s’achève dans l’Atlantique et où les oiseaux migrateurs arrivent par millions.',
      history: 'Créé en 1976 et inscrit à l’UNESCO en 1989, le parc protège les zones d’hivernage d’oiseaux venus d’aussi loin que la Sibérie. Les Imraguen, seule communauté autorisée à y pêcher, utilisent encore des lanches à voile traditionnelles et une pêche assistée par les dauphins sauvages.',
      why: [
        'L’un des sites ornithologiques les plus riches de la planète',
        'Naviguer avec les pêcheurs imraguen',
        'Les dromadaires longeant l’écume à marée basse',
      ],
      moments: [
        'Des milliers de pélicans s’envolant d’un seul coup',
        'Rouler sur le sable mouillé, l’océan contre les roues',
        'Le poisson grillé sur la plage au soleil couchant',
      ],
      info: [
        ['Y aller', '3 – 4 heures au nord de Nouakchott en 4×4, permis obligatoire'],
        ['Durée conseillée', '2 – 4 jours'],
        ['Meilleure saison', 'De novembre à avril pour les migrateurs'],
        ['À combiner avec', 'Nouadhibou, le train du fer, Nouakchott'],
      ],
    },
    {
      id: 'nouakchott',
      name: 'Nouakchott',
      sub: 'La capitale posée sur le sable',
      img: 'nouakchott-fish-market',
      photos: ['atlantic-sunset-group', 'beach-arrival', 'ocean-silhouettes'],
      story: 'Une ville qui n’était qu’un village de quelques centaines d’habitants en 1958 et abrite aujourd’hui un tiers du pays — plate, basse, couleur sable, et bien plus intéressante qu’il n’y paraît.',
      history: 'Choisie comme capitale à l’indépendance en 1960 précisément parce qu’elle n’appartenait à personne, Nouakchott a explosé à mesure que la sécheresse chassait les familles nomades. Sa plage de pêche, son marché aux chameaux et ses centres artisanaux sont la meilleure introduction à la vie mauritanienne d’aujourd’hui.',
      why: [
        'Le port de pêche, l’un des grands spectacles d’Afrique de l’Ouest',
        'Les marchés, l’argenterie et le musée national',
        'La porte d’entrée vers tout le reste du pays',
      ],
      moments: [
        'Des centaines de pirogues débarquant la pêche sur le sable',
        'Le coucher du soleil sur la plage, toute la ville en promenade',
        'Votre premier verre de thé mauritanien',
      ],
      info: [
        ['Y aller', 'Vols internationaux vers Nouakchott–Oumtounsy (NKC)'],
        ['Durée conseillée', '1 journée au début ou à la fin du voyage'],
        ['Meilleure saison', 'Toute l’année ; l’air côtier reste doux'],
        ['À combiner avec', 'Le Banc d’Arguin, l’Adrar, le train du fer'],
      ],
    },
  ],

  galleryPage: {
    hero: {
      eyebrow: 'Photographies',
      title: 'Galerie',
      sub: 'Chaque photographie de ce site a été prise pendant l’un de nos voyages, par nos guides et par les voyageurs qui nous ont accompagnés.',
      scroll: 'Commencer le voyage',
    },
    chapters: {
      train: { n: '01', t: 'Le train du fer', d: 'Douze heures sur un wagon ouvert, des mines de Zouérat jusqu’à l’Atlantique.' },
      desert: { n: '02', t: 'Traversées du désert', d: 'Ergs, bivouacs, caravanes, et le silence que l’on traverse un continent pour entendre.' },
      culture: { n: '03', t: 'Culture', d: 'Cités de pierre, bibliothèques familiales, repas partagés et huit siècles d’hospitalité.' },
      landscapes: { n: '04', t: 'Paysages', d: 'Canyons, oasis, bancs de sable et l’endroit où le Sahara tombe dans l’océan.' },
      travellers: { n: '05', t: 'Voyageurs', d: 'Ceux qui sont venus avec nous, et ce que ce pays a fait d’eux.' },
    },
    ui: { openImage: 'Ouvrir la photographie', of: 'sur', jump: 'Aller au chapitre' },
  },

  aboutPage: {
    hero: {
      eyebrow: 'Qui nous sommes',
      title: 'Une agence mauritanienne, dans un pays qui en avait besoin.',
      sub: 'Travel and Trips in Mauritania existe pour que les voyageurs qui arrivent ici rencontrent le pays \u00e0 travers ceux qui y vivent.',
      img: 'flag-and-camels',
    },
    story: {
      eyebrow: 'Notre histoire',
      title: 'Notre histoire',
      body: [],
      img: 'guide-and-traveller-ridge',
    },
    pillars: {
      eyebrow: 'Ce que nous d\u00e9fendons',
      title: 'Ce que nous d\u00e9fendons',
      items: [],
    },
    guides: {
      eyebrow: 'Nos guides',
      title: 'Nos guides',
      body: [],
      img: 'plateau-two-travellers',
      stats: [],
    },
    safety: {
      eyebrow: 'Voyager en s\u00e9curit\u00e9',
      title: 'Voyager en s\u00e9curit\u00e9',
      items: [],
      img: 'beach-convoy',
    },
    mission: {
      eyebrow: 'Notre mission',
      quote: 'Montrer la Mauritanie au monde sans changer ce qui m\u00e9rite d\u2019\u00eatre montr\u00e9.',
      body: '',
      cta: 'Pr\u00e9parez votre voyage avec nous',
      waMsg: 'Bonjour, je souhaite pr\u00e9parer un voyage en Mauritanie.',
    },
  },

  guidePage: {
    hero: {
      eyebrow: 'Avant de venir',
      title: 'Guide de voyage Mauritanie',
      sub: 'Tout ce que les voyageurs nous demandent, répondu honnêtement. S’il reste une zone d’ombre, écrivez-nous : nous répondons personnellement.',
      img: 'adrar-road-mesa',
    },
    sections: [
      {
        id: 'when',
        t: 'Quand partir en Mauritanie',
        body: [
          'La saison va d’**octobre à avril**. Les journées sont à 22–32 °C, les nuits dans le désert descendent à 8–15 °C, et la lumière est à son meilleur. Décembre et janvier sont les mois les plus frais et les plus demandés.',
          'De **mai à septembre**, l’intérieur dépasse régulièrement 45 °C et voyager dans le désert devient réellement pénible et, par endroits, dangereux.',
          'L’**harmattan**, un vent de poussière sec, peut réduire la visibilité pendant quelques jours entre décembre et février. La côte reste plus douce et plus ventée toute l’année : le Banc d’Arguin et Nouakchott restent agréables hors du plein été.',
        ],
      },
      {
        id: 'visa',
        t: 'Visa et entrée',
        body: [
          'La plupart des voyageurs européens et nord-américains obtiennent un **visa à l’arrivée** à l’aéroport international de Nouakchott–Oumtounsy et aux principaux postes frontières terrestres. Il est délivré sur place, généralement valable 30 jours, et payé en **euros en espèces**.',
          'Il vous faut un passeport valable au moins six mois, un billet de sortie ou de retour et une adresse dans le pays.',
          'Les règles et les tarifs peuvent changer sans grand préavis, et certaines nationalités doivent obtenir un visa à l’avance. Vérifiez les conditions en vigueur pour votre passeport avant de réserver.',
        ],
      },
      {
        id: 'pack',
        t: 'Que mettre dans son sac',
        body: [
          '**Vêtements.** Des couches légères, amples et couvrantes pour la journée ; une polaire ou une veste chaude et un pantalon long pour les nuits du désert, réellement froides de décembre à février. Un foulard ou *chèche* est l’objet le plus utile que vous posséderez — contre le soleil, la poussière et le vent.',
          '**Chaussures.** Des chaussures de marche fermées, plus des sandales pour le campement et le sable. Emportez plus de chaussettes que prévu.',
          '**Soleil et poussière.** Crème solaire à indice élevé, baume à lèvres, lunettes de soleil, et une housse étanche pour les appareils photo — le sable fin s’infiltre partout.',
          '**Pratique.** Lampe frontale, batterie externe (il n’y a pas d’électricité au bivouac), adaptateur universel, gourde, médicaments personnels, lingettes et une petite trousse de secours.',
          '**Argent.** Emportez des euros en espèces. Les cartes ne sont acceptées presque nulle part hors de quelques hôtels de Nouakchott, et les distributeurs sont peu fiables. La monnaie locale est l’ouguiya (MRU).',
        ],
      },
      {
        id: 'safety',
        t: 'La sécurité en Mauritanie',
        body: [
          'La Mauritanie est calme, et les régions que visitent les voyageurs — Nouakchott, la côte atlantique, l’Adrar, le corridor ferroviaire — sont considérées comme stables et régulièrement parcourues par des visiteurs européens. Les agressions contre les touristes sont très rares, et la culture d’hospitalité envers l’invité est extrêmement forte.',
          'Les vrais risques ici sont environnementaux, pas politiques : la chaleur, la déshydratation, le sable mou et l’éloignement des secours médicaux. C’est pourquoi le désert se parcourt avec des guides agréés et des véhicules bien équipés, jamais en autonomie.',
          'Prenez une assurance voyage couvrant le désert et consultez les recommandations actuelles de votre gouvernement avant de réserver.',
        ],
      },
      {
        id: 'culture',
        t: 'Culture et traditions',
        body: [
          'La Mauritanie est une république islamique, et la vie quotidienne suit ce rythme : cinq prières, le vendredi comme jour de repos, **aucun alcool dans tout le pays**, et un mois de jeûne pendant le ramadan, où l’on ne mange ni ne boit en public pendant la journée.',
          'Habillez-vous sobrement — épaules et genoux couverts, pour tout le monde. Les femmes ne sont pas tenues de se couvrir les cheveux, mais un foulard est utile et apprécié dans les villages et les mosquées.',
          'Saluez avant de demander quoi que ce soit : une poignée de main et quelques mots sur la santé et la famille précèdent toute affaire. Acceptez toujours le thé s’il vous est offert ; les trois verres prennent une heure et les refuser est la seule chose qui surprenne vraiment.',
          '**Photographie.** Demandez avant de photographier quelqu’un, surtout les femmes, et acceptez un refus. Ne photographiez jamais les postes militaires, les checkpoints ou les bâtiments officiels. Votre guide vous dira quand c’est possible.',
          'Mangez et donnez de la main droite. Et si l’on vous invite chez quelqu’un, vous serez nourri bien au-delà de vos capacités — ce n’est pas facultatif.',
        ],
      },
      {
        id: 'transport',
        t: 'Se déplacer',
        body: [
          '**Vols.** Nouakchott–Oumtounsy (NKC) est la porte d’entrée principale, avec des liaisons depuis Paris, Casablanca, Istanbul, Madrid et Dakar. Des charters saisonniers desservent parfois directement Atar en hiver.',
          '**Par la route.** La route Nouakchott–Atar est goudronnée et prend environ six heures. Au-delà, tout est piste et exige un 4×4. Les distances sont longues et les stations-service très espacées.',
          '**Le train du fer.** Gratuit, inoubliable et totalement non réglementé. Ce n’est pas à tenter sans guide, sans matériel et sans nourriture.',
        ],
      },
    ],
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'La Mauritanie est-elle sûre pour les touristes ?', a: 'Les régions que visitent les voyageurs — Nouakchott, la côte atlantique, l’Adrar et le corridor ferroviaire — sont calmes et régulièrement parcourues par des visiteurs européens, et les agressions contre les touristes sont très rares. Les vrais risques sont environnementaux : chaleur, déshydratation, sable mou et éloignement des secours, raison pour laquelle le désert se parcourt avec des guides agréés et des véhicules bien équipés. Consultez les recommandations actuelles de votre gouvernement avant de réserver.' },
      { q: 'Ai-je besoin d’un visa ?', a: 'La plupart des voyageurs européens et nord-américains obtiennent un visa à l’arrivée à l’aéroport international de Nouakchott–Oumtounsy et aux principaux postes frontières, délivré sur place, généralement valable 30 jours et payé en euros espèces. Les règles changent et certaines nationalités doivent l’obtenir à l’avance : vérifiez pour votre passeport avant de réserver.' },
      { q: 'Quelle est la meilleure période ?', a: 'D’octobre à avril. Les journées sont à 22–32 °C et les nuits du désert descendent à 8–15 °C. Décembre et janvier sont les plus frais. De mai à septembre, l’intérieur dépasse régulièrement 45 °C.' },
      { q: 'Peut-on vraiment monter dans le train du fer ?', a: 'Oui. Le train transporte le minerai de Zouérat à Nouadhibou et les voyageurs voyagent sur le minerai, dans les wagons ouverts, gratuitement. Le trajet dure environ douze heures, sans aucun abri, et la nuit du désert est réellement froide.' },
      { q: 'Y a-t-il du réseau et de l’internet ?', a: 'En ville, oui, et c’est bon marché. Dans le désert profond et dans le train, non.' },
      { q: 'Comment se passe l’argent ?', a: 'La monnaie locale est l’ouguiya (MRU). Emportez des euros en espèces : les cartes ne sont acceptées presque nulle part hors de quelques hôtels de Nouakchott, et les distributeurs sont peu fiables.' },
      { q: 'Trouve-t-on de l’alcool ?', a: 'Non. La Mauritanie est une république islamique et l’alcool n’est vendu nulle part dans le pays.' },
    ],
    cta: {
      title: 'Une question reste sans réponse ?',
      sub: 'Écrivez-nous directement. Nous vous répondrons.',
      cta: 'Posez votre question sur WhatsApp',
      waMsg: 'Bonjour, j’ai une question sur un voyage en Mauritanie.',
    },
  },

  contactPage: {
    hero: {
      eyebrow: 'Nous contacter',
      title: 'Préparons votre voyage.',
      sub: 'Dites-nous qui voyage, à peu près quand, et ce que vous rêvez de voir. Nous reviendrons vers vous.',
      img: 'dune-sunset-crew',
    },
    methods: {
      whatsapp: { t: 'WhatsApp', d: 'Le moyen le plus rapide de nous joindre.', a: 'Démarrer la conversation' },
      email: { t: 'E-mail', d: 'Pour les itinéraires détaillés, les documents et les groupes.', a: 'Nous écrire' },
      phone: { t: 'Téléphone', d: 'Appelez-nous directement.', a: 'Appeler' },
      location: { t: 'Où nous sommes', d: 'Nouakchott, Mauritanie.', a: 'Ouvrir dans Google Maps' },
    },
    form: {
      eyebrow: 'Demande',
      title: 'Parlez-nous de votre voyage.',
      sub: 'Ce formulaire ouvre WhatsApp avec votre message prêt à envoyer : rien ne se perd dans un dossier de spam.',
      name: 'Votre nom',
      namePh: 'Anna Rossi',
      email: 'E-mail',
      emailPh: 'vous@exemple.com',
      country: 'Pays',
      countryPh: 'France',
      people: 'Voyageurs',
      dates: 'Dates approximatives',
      datesPh: 'Février 2027, environ 10 jours',
      interest: 'Ce qui vous intéresse le plus',
      interestOptions: ['L’aventure du train du fer', 'Expédition dans le Sahara', 'Chinguetti, voyage au patrimoine', 'Ouadane, la cité ancienne', 'Découverte du Banc d’Arguin', 'Un voyage privé sur mesure', 'Je ne sais pas encore'],
      message: 'Autre chose à nous signaler',
      messagePh: 'Condition physique, niveau de confort, régime alimentaire, occasions spéciales…',
      submit: 'Envoyer via WhatsApp',
      submitAlt: 'ou envoyer le même message par e-mail',
      required: 'Merci d’indiquer votre nom et ce qui vous intéresse.',
      intro: 'Bonjour, je souhaite préparer un voyage en Mauritanie.',
    },
    promise: {
      t: 'Ce qui se passe ensuite',
      items: [],
    },
  },

  footer: {
    tagline: 'Voyages privés guidés par des locaux à travers le Sahara, les cités anciennes et la côte atlantique de la Mauritanie.',
    explore: 'Explorer',
    company: 'L’agence',
    contact: 'Contact',
    follow: 'Suivre le voyage',
    rights: 'Tous droits réservés.',
    built: 'Chaque photographie de ce site a été prise pendant nos propres voyages.',
    waMsg: 'Bonjour, je souhaite des informations sur vos voyages en Mauritanie.',
  },

  a11y: {
    skip: 'Aller au contenu',
    heroSlides: 'Photographies principales',
    lightbox: 'Visionneuse de photographies',
    menu: 'Menu principal',
  },
};
