/** Testi italiani. Struttura identica a en.js. */
module.exports = {
  code: 'it',
  htmlLang: 'it',

  nav: {
    home: 'Home',
    experiences: 'Esperienze',
    destinations: 'Destinazioni',
    gallery: 'Galleria',
    about: 'Chi siamo',
    guide: 'Guida di viaggio',
    contact: 'Contatti',
    cta: 'WhatsApp',
    menu: 'Menu',
    close: 'Chiudi',
    language: 'Lingua',
  },

  ui: {
    explore: 'Scopri',
    exploreExperience: 'Scopri l’esperienza',
    book: 'Prenota questa esperienza',
    plan: 'Progetta la tua avventura',
    viewAll: 'Vedi tutte le esperienze',
    viewGallery: 'Apri la galleria',
    location: 'Luogo',
    duration: 'Durata',
    season: 'Stagione migliore',
    group: 'Gruppo',
    highlights: 'Punti salienti',
    journey: 'Cosa vivono i viaggiatori',
    photos: 'Fotografie',
    story: 'Il racconto',
    history: 'Storia',
    whyVisit: 'Perché andarci',
    moments: 'I momenti migliori',
    info: 'Informazioni pratiche',
    close: 'Chiudi',
    prev: 'Precedente',
    next: 'Successivo',
    scroll: 'Scorri',
    readMore: 'Continua a leggere',
    all: 'Tutte',
    talkToUs: 'Scrivici su WhatsApp',
    writeUs: 'Scrivici',
  },

  meta: {
    home: {
      title: 'Travel and Trips in Mauritania — Sahara e treno del ferro',
      desc: 'Viaggi privati guidati da mauritani: il Sahara, le città antiche di Chinguetti e Ouadane, il leggendario treno del ferro e il Banc d’Arguin. Pensati per viaggiatori internazionali.',
    },
    experiences: {
      title: 'Esperienze — Treno del ferro, Sahara e città antiche',
      desc: 'Cinque viaggi d’autore in Mauritania: il treno del ferro, la spedizione nel Sahara, Chinguetti, Ouadane e il parco nazionale del Banc d’Arguin. Partenze private, guide locali.',
    },
    destinations: {
      title: 'Destinazioni — Chinguetti, Ouadane, Adrar, Banc d’Arguin',
      desc: 'Dove andare in Mauritania: l’altopiano dell’Adrar, gli ksour UNESCO di Chinguetti e Ouadane, il Sahara, la ferrovia del ferro, il Banc d’Arguin e Nouakchott.',
    },
    gallery: {
      title: 'Galleria — Fotografie dai nostri viaggi in Mauritania',
      desc: 'Un viaggio fotografico in Mauritania: il treno del ferro, le traversate del deserto, le città antiche, l’Atlantico e i viaggiatori che sono venuti con noi.',
    },
    about: {
      title: 'Chi siamo — Un’agenzia mauritana | Travel and Trips in Mauritania',
      desc: 'Siamo un’agenzia di viaggio mauritana che progetta viaggi privati per viaggiatori internazionali, con le nostre guide, i nostri autisti e le nostre squadre del deserto.',
    },
    guide: {
      title: 'Guida di viaggio Mauritania — Visto, sicurezza, stagione',
      desc: 'Consigli pratici e onesti per viaggiare in Mauritania: visto, stagione, sicurezza, cultura, trasporti, denaro e le domande che ci fanno più spesso.',
    },
    contact: {
      title: 'Contatti — Progetta il tuo viaggio in Mauritania',
      desc: 'Parla con un esperto locale su WhatsApp, via e-mail o con il nostro modulo. Rispondiamo personalmente a ogni messaggio, di solito in poche ore.',
    },
  },

  hero: {
    line1: 'Scopri la Mauritania',
    line2: 'Oltre l’ordinario',
    sub: 'Città antiche, deserti infiniti e viaggi indimenticabili, con esperti locali.',
    cta1: 'Scopri le esperienze',
    cta2: 'Progetta la tua avventura',
    scroll: 'Scorri per iniziare',
    waMsg: 'Buongiorno, vorrei organizzare con voi un’avventura in Mauritania.',
  },

  home: {
    intro: {
      eyebrow: 'L’ultimo grande silenzio',
      title: 'Un Paese che il mondo non ha ancora imparato a visitare.',
      body: [
        'La Mauritania è grande quanto l’Egitto e riceve in un anno meno visitatori di quanti un solo museo europeo ne riceva in una settimana. Il novanta per cento è Sahara. Il resto è costa atlantica, valli di oasi e città di pietra a secco dove si copiavano manoscritti di astronomia mentre l’Europa costruiva ancora le sue cattedrali.',
        'Qui non ci sono folle, né vie di souvenir, né code al punto panoramico. C’è un Paese che appartiene ancora interamente a chi ci vive — e alcuni di noi che sanno come portarvici davvero.',
      ],
      stats: [
        { n: '1 200 000', l: 'km² di deserto, costa e silenzio' },
        { n: '2', l: 'siti patrimonio mondiale UNESCO' },
        { n: '704 km', l: 'di ferrovia attraverso il Sahara' },
        { n: 'XIII sec.', l: 'l’età delle biblioteche di Chinguetti' },
      ],
    },

    why: {
      eyebrow: 'Perché viaggiare con noi',
      title: 'Nata da mauritani, per viaggiatori che vogliono la cosa vera.',
      items: [
        {
          t: 'Esperti locali',
          d: 'Siamo di qui. La nostra squadra vive fra Nouakchott e l’Adrar, e gli itinerari che proponiamo sono quelli su cui siamo cresciuti — non programmi comprati da un grossista.',
          img: 'plateau-two-travellers',
        },
        {
          t: 'Esperienze autentiche',
          d: 'Dormite dove dormono i nomadi, mangiate ciò che cucina la famiglia e bevete i tre bicchieri di tè come si deve. Niente è messo in scena per la macchina fotografica, perché non serve.',
          img: 'acacia-lunch',
        },
        {
          t: 'Viaggi su misura',
          d: 'Ogni viaggio è privato e ricostruito intorno a voi: due persone o dodici, cinque giorni o tre settimane, avventura dura o comfort lento. Diteci cosa volete provare.',
          img: 'lone-vehicle-plain',
        },
        {
          t: 'Guide professioniste',
          d: 'Guide e autisti sahariani autorizzati che attraversano questo Paese da decenni, che parlano inglese, francese, italiano, arabo e hassaniya, con comunicazione satellitare a ogni partenza.',
          img: 'guide-and-traveller-ridge',
        },
      ],
    },

    featured: {
      eyebrow: 'Viaggi d’autore',
      title: 'Cinque modi di incontrare la Mauritania.',
      sub: 'Ognuno è privato, guidato dalla nostra squadra, e si può allungare, accorciare o combinare.',
    },

    destPreview: {
      eyebrow: 'Dove andiamo',
      title: 'Sette luoghi per cui vale la pena attraversare un continente.',
      cta: 'Scopri le destinazioni',
    },

    moments: {
      eyebrow: 'Momenti di viaggio',
      title: 'Le fotografie di chi è venuto con noi.',
      sub: 'Nessuna di queste immagini viene da una banca dati. Ogni scatto di questo sito è stato fatto durante uno dei nostri viaggi.',
      cta: 'Apri la galleria completa',
    },

    testimonials: {
      eyebrow: 'Con le loro parole',
      title: 'Cosa dicono i viaggiatori una volta tornati a casa.',
      items: [
        { q: 'Dodici ore sul treno del minerale, una notte sotto più stelle di quante ne avessi mai viste e una squadra che ha reso tutto perfettamente sicuro. La settimana più straordinaria della mia vita da viaggiatrice.', n: 'Claire', c: 'Francia' },
        { q: 'Non immaginavo che esistesse ancora un Paese così. Chinguetti all’alba, dune deserte e guide che ci hanno trattati come famiglia dalla prima ora.', n: 'Marco', c: 'Italia' },
        { q: 'Organizzato alla perfezione e mai troppo organizzato. Hanno capito esattamente il viaggio che volevamo e poi lo hanno realizzato in silenzio.', n: 'Daniel', c: 'Regno Unito' },
      ],
    },

    finalCta: {
      title: 'La tua avventura mauritana comincia qui.',
      sub: 'Diteci quando volete partire e cosa volete vedere. Progettiamo il viaggio, rispondiamo a ogni domanda e ci occupiamo di tutto dal momento in cui atterrate.',
      cta1: 'Progetta la tua avventura',
      cta2: 'Vedi tutte le esperienze',
      waMsg: 'Buongiorno, vorrei iniziare a organizzare il mio viaggio in Mauritania.',
    },
  },

  experiencesPage: {
    hero: {
      eyebrow: 'Viaggi d’autore',
      title: 'Esperienze',
      sub: 'Cinque viaggi, tutti privati, tutti guidati dalle nostre guide. Sceglietene uno, oppure lasciate che costruiamo un itinerario che li unisca.',
    },
    outro: {
      title: 'Nessuno è esattamente ciò che cercate?',
      sub: 'Allora ne progetteremo un altro. La maggior parte dei nostri viaggiatori parte con un itinerario che esiste solo per loro.',
      cta: 'Progetta un viaggio privato',
      waMsg: 'Buongiorno, vorrei progettare un viaggio privato su misura in Mauritania.',
    },
  },

  experiences: [
    {
      id: 'iron-ore-train',
      title: 'Avventura sul treno del ferro',
      tagline: 'Dodici ore sul treno più lungo del mondo.',
      short: 'Salite su un vagone aperto carico di minerale al tramonto e attraversate il Sahara sulla ferrovia più leggendaria d’Africa.',
      location: 'Choum → Nouadhibou',
      duration: '3 giorni / 2 notti',
      season: 'Ottobre — aprile',
      group: 'Privato, 2 – 12 viaggiatori',
      hero: 'train-riders',
      gallery: ['iron-ore-train-mono', 'train-arms-open', 'train-night-rest', 'train-night-portrait'],
      story: [
        'Una volta al giorno un treno lungo fino a tre chilometri lascia le miniere di Zouérat carico di minerale di ferro diretto all’Atlantico. Non ha biglietteria, non ha posti a sedere e non ha un orario di cui fidarsi — ed è uno degli ultimi viaggi gratuiti rimasti su questo pianeta.',
        'Raggiungiamo il treno dove il deserto incontra la linea, carichiamo coperte, stuoie, acqua e cibo su un vagone vuoto e saliamo. Poi il Sahara comincia a scorrere: ocra, poi rosa, poi viola, poi un cielo nero con più stelle di quante ve ne abbiano mai mostrate.',
        'Al mattino siete all’oceano, a Nouadhibou, coperti di polvere e incapaci di smettere di sorridere. Le nostre guide viaggiano con voi per tutto il percorso.',
      ],
      highlights: [
        'Una traversata notturna completa su un vagone aperto, guidata dall’inizio alla fine',
        'Tramonto e alba sul Sahara dalla cima del treno',
        'Giaciglio caldo, protezione dal vento, cibo caldo e tè inclusi',
        'Trasferimenti da e per la linea in 4×4 privato',
        'Arrivo a Nouadhibou e sulla costa atlantica',
      ],
      journey: [
        { t: 'Pomeriggio — Raggiungere la linea', d: 'Andiamo alla ferrovia vicino a Choum, prepariamo il vagone e aspettiamo quel suono che arriva molto prima del treno.' },
        { t: 'Tramonto — La partenza', d: 'Salite a bordo mentre la luce cambia. La prima ora sul minerale in movimento è quella che tutti ricordano per sempre.' },
        { t: 'Notte — Le stelle', d: 'Avvolti nelle coperte, tè in mano, ad attraversare centinaia di chilometri di buio assoluto sotto la Via Lattea.' },
        { t: 'Mattino — L’oceano', d: 'Arrivo a Nouadhibou, doccia calda, una colazione lunga e l’Atlantico davanti a voi.' },
      ],
      waMsg: 'Buongiorno, sono interessato/a all’avventura sul treno del ferro vista sul vostro sito.',
    },
    {
      id: 'sahara-expedition',
      title: 'Spedizione nel deserto del Sahara',
      tagline: 'Dune, bivacchi e un orizzonte che non arriva mai.',
      short: 'Una traversata guidata dei grandi erg dell’Adrar, dormendo sotto le stelle e camminando con le carovane di cammelli.',
      location: 'Regione dell’Adrar, Mauritania centrale',
      duration: '5 – 9 giorni',
      season: 'Novembre — marzo',
      group: 'Privato, 2 – 10 viaggiatori',
      hero: 'camel-caravan-dune',
      gallery: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'dune-descent', 'lone-vehicle-plain', 'flag-and-camels'],
      story: [
        'Questo è il Sahara che si immagina prima di averlo visto: dune color brace, altopiani di pietra nera, letti di uadi pieni di acacie e un silenzio così totale che di notte si sente il proprio battito.',
        'Viaggiamo in 4×4 e a piedi, con i cammelli che portano il campo quando volete camminare. Ogni sera la squadra monta il bivacco sulla sabbia, cucina sulla legna e versa i tre bicchieri di tè mentre la luce se ne va.',
        'Qui non esiste un itinerario venduto a cento gruppi a stagione. Scegliamo le dune in base al vento, al mese e al tipo di viaggiatore che siete.',
      ],
      highlights: [
        'Notti in bivacco sulle dune, senza nessun altro campo in vista',
        'Camminare una tappa con una carovana e i suoi cammellieri',
        'Canyon-oasi, palmeti e sorgenti naturali',
        'Cucina sulla legna, cerimonia del tè, ospitalità nomade',
        'L’alba dalla cima di un erg su cui non c’è nessun altro',
      ],
      journey: [
        { t: 'Giorno 1 — Verso l’Adrar', d: 'Sei ore a nord di Nouakchott attraverso colori che cambiano: pianura grigia, altopiano rosso, poi le prime vere dune.' },
        { t: 'Giorni 2–4 — I grandi erg', d: 'Traversata dei mari di sabbia in veicolo e a piedi, con lunghe pause all’ombra, tè e bagni nelle sorgenti delle oasi.' },
        { t: 'Le sere — Il campo', d: 'Il fuoco, il cibo cucinato davanti a voi, i materassi sulla sabbia e un cielo che fa ammutolire tutti.' },
        { t: 'Ultimo giorno — Il ritorno', d: 'Ritorno per le valli di palme con sosta in un villaggio-oasi, oppure proseguimento diretto verso Chinguetti e Ouadane.' },
      ],
      waMsg: 'Buongiorno, sono interessato/a alla spedizione nel deserto del Sahara vista sul vostro sito.',
    },
    {
      id: 'chinguetti-heritage',
      title: 'Chinguetti, viaggio nel patrimonio',
      tagline: 'La settima città dell’Islam e le biblioteche nella sua sabbia.',
      short: 'Due giorni dentro una città carovaniera del XIII secolo dove le famiglie custodiscono ancora i manoscritti che i loro antenati portarono attraverso il deserto.',
      location: 'Chinguetti, regione dell’Adrar',
      duration: '2 – 3 giorni',
      season: 'Ottobre — aprile',
      group: 'Privato, 2 – 12 viaggiatori',
      hero: 'chinguetti-minaret',
      gallery: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove', 'terjit-oasis-canyon'],
      story: [
        'Chinguetti fu fondata nel XIII secolo come punto di raccolta per le carovane dirette alla Mecca e divenne uno dei grandi centri del sapere del Sahara. Gli studiosi vi arrivavano per studiare astronomia, matematica, diritto e medicina.',
        'Oggi la città vecchia è mezza sepolta dalla sabbia, e i manoscritti sono ancora qui — conservati in biblioteche familiari, avvolti nella stoffa, mostrati dai discendenti di chi li ha scritti.',
        'Attraversiamo il quartiere antico nella luce bassa del mattino, incontriamo un bibliotecario, beviamo il tè in un cortile e saliamo sulle dune sopra la città per il tramonto.',
      ],
      highlights: [
        'Il minareto di pietra della Moschea Vecchia, in uso dal XIII secolo',
        'Una visita privata a una delle biblioteche familiari di manoscritti',
        'Le strade insabbiate del vecchio ksar alle prime luci',
        'Il tramonto dalle dune che si stanno lentamente riprendendo la città',
        'Il tè e la conversazione con famiglie che vivono qui da secoli',
      ],
      journey: [
        { t: 'Arrivo — La città nuova', d: 'Sistemazione, pranzo e attesa che il caldo si spezzi prima di entrare nel quartiere antico.' },
        { t: 'Ora d’oro — Il vecchio ksar', d: 'Vicoli di pietra, portali, la moschea e il suono della città ascoltato da dentro le sue mura.' },
        { t: 'Le biblioteche', d: 'Una lettura privata di manoscritti copiati a mano sette secoli fa, spiegati dalla famiglia che li custodisce.' },
        { t: 'Alba — Le dune', d: 'Salire sopra la città per vedere il sole arrivare su un erg che si estende fino all’orizzonte.' },
      ],
      waMsg: 'Buongiorno, sono interessato/a al viaggio nel patrimonio di Chinguetti visto sul vostro sito.',
    },
    {
      id: 'ouadane-ancient-city',
      title: 'Ouadane, la città antica',
      tagline: 'Mille anni di pietra a secco sopra una valle verde.',
      short: 'Il più spettacolare degli ksour mauritani: una città in rovina aggrappata a una rupe, fondata nel 1147.',
      location: 'Ouadane, regione dell’Adrar',
      duration: '2 giorni',
      season: 'Ottobre — aprile',
      group: 'Privato, 2 – 12 viaggiatori',
      hero: 'ouadane-archway',
      gallery: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon', 'oasis-stone-wall'],
      story: [
        'Ouadane fu costruita nel 1147 sulla via carovaniera che portava l’oro a nord e il sale a sud. Al suo apice era una delle città più ricche del Sahara. Poi le rotte cambiarono, e il deserto cominciò a riprendersela.',
        'Ciò che resta è straordinario: vicoli a gradini di pietra a secco, portali e scale ancora in piedi, un’intera città bassa in rovina sopra una valle di palme da dattero.',
        'Sono due ore di pista sull’altopiano nero da Chinguetti, e non ci va quasi nessuno. Quasi sempre avrete l’intera città per voi.',
      ],
      highlights: [
        'La città bassa abbandonata, costruita senza una goccia di malta',
        'La moschea antica e il quartiere carovaniero',
        'La traversata dell’altopiano dell’Adrar per arrivarci',
        'La valle di palme da dattero sotto le rovine',
        'Il tramonto sul ksar senza nessun altro visitatore',
      ],
      journey: [
        { t: 'Mattino — Attraverso l’altopiano', d: 'Un percorso lento nel deserto di roccia nera e valli asciutte, con soste per formazioni rocciose e vecchi pozzi.' },
        { t: 'Pomeriggio — Le rovine', d: 'Visita guidata della città bassa con uno storico locale, dalla moschea fino alle terrazze più alte.' },
        { t: 'Sera — La valle', d: 'Il tè sopra i giardini di palme, quando la pietra prende il colore del sole.' },
        { t: 'Opzione — Guelb er Richat', d: 'Aggiungete un giorno per raggiungere la struttura di Richat, «l’Occhio del Sahara» di 40 km, visibile dallo spazio.' },
      ],
      waMsg: 'Buongiorno, sono interessato/a all’esperienza della città antica di Ouadane vista sul vostro sito.',
    },
    {
      id: 'banc-darguin',
      title: 'Scoperta del Banc d’Arguin',
      tagline: 'Dove il Sahara entra nell’Atlantico.',
      short: 'Un santuario UNESCO di banchi di sabbia e bassi fondali che ospita milioni di uccelli migratori — e cammelli sulla spiaggia.',
      location: 'Parco nazionale del Banc d’Arguin, costa atlantica',
      duration: '2 – 4 giorni',
      season: 'Novembre — aprile',
      group: 'Privato, 2 – 10 viaggiatori',
      hero: 'camels-atlantic',
      gallery: ['arguin-pelicans', 'arguin-birds-shore', 'beach-convoy', 'beach-arrival', 'atlantic-sunset-group', 'nouakchott-fish-market'],
      story: [
        'Il Banc d’Arguin è uno dei siti ornitologici più importanti al mondo, un parco patrimonio dell’umanità dove il deserto finisce semplicemente nelle acque fredde dell’Atlantico. Due milioni di uccelli migratori vi svernano.',
        'Percorriamo la costa con famiglie di pescatori Imraguen, navighiamo su una lancia tradizionale sopra i bassi fondali e guidiamo sulla sabbia compatta della battigia, con l’oceano da un lato e le dune dall’altro.',
        'È il paesaggio più dolce e più strano della Mauritania — ed è il motivo per cui tanti viaggiatori prolungano il viaggio.',
      ],
      highlights: [
        'Pellicani, fenicotteri, sterne e limicoli in numeri enormi',
        'Navigare con i pescatori Imraguen su una lancia tradizionale',
        'Guidare sulla battigia dove il Sahara incontra l’oceano',
        'I cammelli che camminano sulla schiuma, l’immagine che tutti riportano a casa',
        'Il pesce fresco grigliato sulla spiaggia al tramonto',
      ],
      journey: [
        { t: 'Partenza — A nord lungo la costa', d: 'Si lascia Nouakchott sulla via costiera, con sosta alla spiaggia dei pescatori e alle sue centinaia di piroghe dipinte.' },
        { t: 'Il parco — Banchi di sabbia e uccelli', d: 'Ingresso nella riserva, navigazione sopra i bassi fondali e stormi che si alzano a migliaia.' },
        { t: 'Villaggi Imraguen', d: 'Tempo con le uniche persone autorizzate a pescare dentro il parco, con metodi immutati da generazioni.' },
        { t: 'Tramonto — Il campo sulla spiaggia', d: 'Pesce grigliato, un fuoco sulla sabbia e l’Atlantico che si fa scuro davanti alle dune.' },
      ],
      waMsg: 'Buongiorno, sono interessato/a alla scoperta del Banc d’Arguin vista sul vostro sito.',
    },
  ],

  destinationsPage: {
    hero: {
      eyebrow: 'Dove andiamo',
      title: 'Destinazioni',
      sub: 'Sette paesaggi che insieme spiegano cos’è la Mauritania: il deserto, le città di pietra nate dentro di esso e l’oceano che alla fine lo ferma.',
    },
  },

  destinations: [
    {
      id: 'chinguetti',
      name: 'Chinguetti',
      sub: 'La settima città dell’Islam',
      img: 'chinguetti-minaret',
      photos: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove'],
      story: 'Una città carovaniera mezza inghiottita dalle dune, dove sotto la sabbia sopravvivono case di pietra, un minareto del XIII secolo e migliaia di manoscritti copiati a mano. Patrimonio mondiale UNESCO dal 1996.',
      history: 'Fondata intorno al 1264 come tappa per pellegrini e mercanti diretti alla Mecca, Chinguetti divenne un centro di sapere islamico così importante che la Mauritania era conosciuta semplicemente come «la terra di Chinguetti». Le sue biblioteche conservano opere di astronomia, giurisprudenza, grammatica e medicina copiate a mano per sette secoli.',
      why: [
        'Il minareto ancora in uso più antico del Paese',
        'Biblioteche familiari dove i manoscritti sono ancora conservati e letti',
        'Un quartiere antico che l’erg si sta lentamente riprendendo',
      ],
      moments: [
        'Il richiamo alla preghiera che rimbalza sulle mura di pietra all’alba',
        'Girare la pagina di un manoscritto di astronomia di 700 anni',
        'Il tramonto dalle dune, con tutta la città sotto di voi',
      ],
      info: [
        ['Come arrivare', '1 ora da Atar in 4×4; Atar è raggiungibile via strada o con volo stagionale'],
        ['Quanto tempo', '1 – 2 notti'],
        ['Stagione migliore', 'Da ottobre ad aprile'],
        ['Da abbinare a', 'Ouadane, le dune dell’Adrar, la struttura di Richat'],
      ],
    },
    {
      id: 'ouadane',
      name: 'Ouadane',
      sub: 'La città di pietra del 1147',
      img: 'ouadane-archway',
      photos: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon'],
      story: 'Una città medievale in rovina, fatta di vicoli di pietra a secco costruiti su una rupe sopra una valle di palme — il più spettacolare dei quattro ksour antichi della Mauritania, e il più deserto.',
      history: 'Fondata nel 1147 da mercanti berberi, Ouadane si arricchì con il commercio di oro, sale e datteri e contò migliaia di abitanti. Quando nel XVI secolo le rotte carovaniere si spostarono, la città cominciò a svuotarsi e la parte bassa fu gradualmente abbandonata al deserto. È patrimonio UNESCO dal 1996.',
      why: [
        'Un’intera città abbandonata, costruita senza malta, ancora in piedi',
        'La porta d’accesso alla struttura di Richat, «l’Occhio del Sahara»',
        'Quasi nessun altro visitatore, quasi ogni giorno dell’anno',
      ],
      moments: [
        'Salire i vicoli a gradini mentre la pietra diventa oro',
        'Stare sulla terrazza più alta sopra la valle di palme',
        'Le due ore di pista sull’altopiano nero per arrivarci',
      ],
      info: [
        ['Come arrivare', '2 – 3 ore da Chinguetti attraverso l’altopiano, in 4×4'],
        ['Quanto tempo', '1 notte'],
        ['Stagione migliore', 'Da ottobre ad aprile'],
        ['Da abbinare a', 'La struttura di Richat, Chinguetti, i grandi erg'],
      ],
    },
    {
      id: 'adrar',
      name: 'Regione dell’Adrar',
      sub: 'Altopiani, canyon e valli di palme',
      img: 'terjit-oasis-canyon',
      photos: ['adrar-road-mesa', 'palm-grove', 'plateau-two-travellers', 'oasis-stone-wall'],
      story: 'Il cuore della Mauritania sahariana: un altopiano di roccia nera inciso da canyon, con oasi nascoste di palme da dattero e sorgenti calde in fondo alle gole.',
      history: 'L’Adrar è abitato da millenni: sui suoi altopiani si trovano ancora strumenti neolitici e incisioni rupestri. Culla delle città carovaniere, resta il centro culturale del Sahara mauritano, con Atar come capoluogo.',
      why: [
        'Canyon-oasi dove sorgenti calde alimentano foreste di palme',
        'Il paesaggio desertico più spettacolare del Paese',
        'La base per Chinguetti, Ouadane e le grandi dune',
      ],
      moments: [
        'Fare il bagno in una sorgente in fondo a una gola dopo una giornata di polvere',
        'La prima macchia di verde vista dall’alto di una parete',
        'La raccolta dei datteri nei palmeti a luglio',
      ],
      info: [
        ['Come arrivare', '6 ore di strada da Nouakchott, o un volo stagionale per Atar'],
        ['Quanto tempo', '3 – 7 giorni'],
        ['Stagione migliore', 'Da novembre a marzo'],
        ['Da abbinare a', 'Tutto — è qui che nasce la maggior parte dei viaggi'],
      ],
    },
    {
      id: 'sahara',
      name: 'Il deserto del Sahara',
      sub: 'Erg, silenzio e campi nomadi',
      img: 'camel-caravan-dune',
      photos: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'lone-vehicle-plain'],
      story: 'Il novanta per cento della Mauritania è deserto, e gran parte non è mai stata cartografata nel dettaglio. È qui che i viaggi diventano silenziosi.',
      history: 'Il Sahara era verde appena 6.000 anni fa; nell’interno sopravvivono pitture rupestri di bovini e giraffe. La cultura nomade che l’ha sostituito — carovane, tende, cerimonia del tè, poesia recitata di notte — è ancora viva qui come non lo è più in gran parte del Nord Africa.',
      why: [
        'Dune e mari di sabbia senza nessun altro gruppo in vista',
        'Notti sotto un cielo senza alcun inquinamento luminoso',
        'Carovane che percorrono ancora le rotte antiche',
      ],
      moments: [
        'L’istante in cui i motori si spengono e non si sente assolutamente nulla',
        'Camminare scalzi su una cresta di duna all’alba',
        'Il terzo bicchiere di tè, un’ora dopo il primo',
      ],
      info: [
        ['Come arrivare', 'In 4×4 con una guida sahariana autorizzata — sempre'],
        ['Quanto tempo', '2 – 9 giorni'],
        ['Stagione migliore', 'Da novembre a marzo'],
        ['Da abbinare a', 'Chinguetti, Ouadane, il treno del ferro'],
      ],
    },
    {
      id: 'iron-ore-route',
      name: 'La linea del treno del ferro',
      sub: '704 km di rotaia attraverso il deserto',
      img: 'iron-ore-train-mono',
      photos: ['train-riders', 'train-arms-open', 'train-night-rest'],
      story: 'Una linea, una direzione, fino a 220 vagoni: la ferrovia che porta il ferro da Zouérat all’Atlantico, e i viaggiatori che lo chiedono con gentilezza.',
      history: 'Costruita fra il 1960 e il 1963 per portare il minerale dalle miniere di Zouérat al porto di Nouadhibou, la linea attraversa 704 chilometri di Sahara aperto. Fu progettata per resistere a sabbia, calore e isolamento totale, e funziona quasi senza interruzioni da sessant’anni.',
      why: [
        'Uno degli ultimi grandi viaggi davvero gratuiti al mondo',
        'Tramonto, notte e alba da un vagone aperto',
        'Una traversata del quarto vuoto del Sahara',
      ],
      moments: [
        'Sentire il treno molto prima di vederlo',
        'La prima ora, in piedi, con il vento e la luce',
        'Arrivare all’oceano coperti di polvere di ferro',
      ],
      info: [
        ['Come arrivare', 'Raggiungiamo la linea vicino a Choum, in 4×4 da Atar'],
        ['Quanto tempo', '2 – 3 giorni, trasferimenti inclusi'],
        ['Stagione migliore', 'Da ottobre ad aprile — mai d’estate'],
        ['Da abbinare a', 'Nouadhibou, il Banc d’Arguin, l’Adrar'],
      ],
    },
    {
      id: 'banc-darguin',
      name: 'Parco nazionale del Banc d’Arguin',
      sub: 'Due milioni di uccelli fra deserto e oceano',
      img: 'arguin-pelicans',
      photos: ['arguin-birds-shore', 'camels-atlantic', 'beach-convoy'],
      story: 'Un parco di 12.000 km² patrimonio dell’umanità, fatto di banchi di sabbia, acque basse e dune, dove il Sahara finisce nell’Atlantico e gli uccelli migratori arrivano a milioni.',
      history: 'Creato nel 1976 e iscritto all’UNESCO nel 1989, il parco protegge le aree di svernamento di uccelli che arrivano fin dalla Siberia. Gli Imraguen, l’unica comunità autorizzata a pescarvi, usano ancora lance a vela tradizionali e una pesca assistita dai delfini selvatici.',
      why: [
        'Uno dei siti ornitologici più ricchi del pianeta',
        'Navigare con i pescatori Imraguen',
        'I cammelli che camminano sulla battigia con la bassa marea',
      ],
      moments: [
        'Migliaia di pellicani che si alzano tutti insieme',
        'Guidare sulla sabbia bagnata con l’oceano accanto alle ruote',
        'Il pesce grigliato sulla spiaggia mentre il sole scende',
      ],
      info: [
        ['Come arrivare', '3 – 4 ore a nord di Nouakchott in 4×4, permesso obbligatorio'],
        ['Quanto tempo', '2 – 4 giorni'],
        ['Stagione migliore', 'Da novembre ad aprile per i migratori'],
        ['Da abbinare a', 'Nouadhibou, il treno del ferro, Nouakchott'],
      ],
    },
    {
      id: 'nouakchott',
      name: 'Nouakchott',
      sub: 'La capitale sulla sabbia',
      img: 'nouakchott-fish-market',
      photos: ['atlantic-sunset-group', 'beach-arrival', 'ocean-silhouettes'],
      story: 'Una città che nel 1958 era un villaggio di poche centinaia di persone e oggi ospita un terzo del Paese — piatta, bassa, color sabbia, e molto più interessante di quanto sembri.',
      history: 'Scelta come capitale all’indipendenza nel 1960 proprio perché non apparteneva a nessuno, Nouakchott è cresciuta in modo esplosivo mentre la siccità spingeva via dalla terra le famiglie nomadi. La spiaggia dei pescatori, il mercato dei cammelli e i centri artigiani sono la migliore introduzione alla Mauritania di oggi.',
      why: [
        'Il porto di pesca, uno dei grandi spettacoli dell’Africa occidentale',
        'I mercati, l’argenteria e il museo nazionale',
        'La porta d’accesso a tutto il resto del Paese',
      ],
      moments: [
        'Centinaia di piroghe che scaricano il pescato sulla sabbia',
        'Il tramonto sulla spiaggia atlantica, con tutta la città a passeggio',
        'Il vostro primo bicchiere di tè mauritano',
      ],
      info: [
        ['Come arrivare', 'Voli internazionali per Nouakchott–Oumtounsy (NKC)'],
        ['Quanto tempo', '1 giorno all’inizio o alla fine del viaggio'],
        ['Stagione migliore', 'Tutto l’anno; l’aria costiera resta mite'],
        ['Da abbinare a', 'Il Banc d’Arguin, l’Adrar, il treno del ferro'],
      ],
    },
  ],

  galleryPage: {
    hero: {
      eyebrow: 'Fotografie',
      title: 'Galleria',
      sub: 'Ogni fotografia di questo sito è stata scattata durante uno dei nostri viaggi, dalle nostre guide e dai viaggiatori che sono venuti con noi.',
      scroll: 'Inizia il viaggio',
    },
    chapters: {
      train: { n: '01', t: 'Il treno del ferro', d: 'Dodici ore su un vagone aperto, dalle miniere di Zouérat all’Atlantico.' },
      desert: { n: '02', t: 'Traversate del deserto', d: 'Erg, bivacchi, carovane e il silenzio che si attraversa un continente per ascoltare.' },
      culture: { n: '03', t: 'Cultura', d: 'Città di pietra, biblioteche familiari, pasti condivisi e otto secoli di ospitalità.' },
      landscapes: { n: '04', t: 'Paesaggi', d: 'Canyon, oasi, banchi di sabbia e il punto in cui il Sahara cade nell’oceano.' },
      travellers: { n: '05', t: 'Viaggiatori', d: 'Le persone che sono venute con noi, e ciò che questo Paese ha fatto loro.' },
    },
    ui: { openImage: 'Apri la fotografia', of: 'di', jump: 'Vai al capitolo' },
  },

  aboutPage: {
    hero: {
      eyebrow: 'Chi siamo',
      title: 'Un’agenzia mauritana, in un Paese che ne aveva bisogno.',
      sub: 'Abbiamo creato Travel and Trips in Mauritania perché chi arriva qui incontri il Paese attraverso le persone che davvero ci vivono.',
      img: 'flag-and-camels',
    },
    story: {
      eyebrow: 'La nostra storia',
      title: 'È cominciata con ospiti che continuavano a voler tornare.',
      body: [
        'Siamo guide, autisti e squadre del deserto di Nouakchott e dell’Adrar. Per anni abbiamo lavorato sulle piste per le agenzie di altri, vedendo arrivare viaggiatori che non avevano quasi idea di cosa li aspettasse — e ripartire dicendo che era stato il viaggio più bello della loro vita.',
        'Così abbiamo creato la nostra agenzia: locale, piccola e responsabile direttamente verso il viaggiatore. Nessun call center, nessun subappalto, nessun programma comprato da un grossista. Quando ci scrivete, scrivete alle persone che saranno con voi nel deserto.',
        'Oggi ospitiamo viaggiatori da Francia, Italia, Regno Unito, Germania, Spagna e oltre, in inglese, francese, italiano, arabo e hassaniya. Quasi tutti arrivano sapendo pochissimo della Mauritania. Ed è esattamente la parte che amiamo.',
      ],
      img: 'guide-and-traveller-ridge',
    },
    pillars: {
      eyebrow: 'In cosa crediamo',
      title: 'Quattro cose su cui non scendiamo a compromessi.',
      items: [
        { t: 'Locale, sempre', d: 'Ogni guida, autista, cuoco e cammelliere dei nostri viaggi è mauritano. Il denaro che spendete resta nelle comunità che attraversate.' },
        { t: 'Piccoli gruppi', d: 'Solo partenze private, da due viaggiatori in su. Non vendiamo posti sull’autobus di qualcun altro.' },
        { t: 'Pianificazione onesta', d: 'Se un itinerario è troppo duro per le vostre date, la vostra forma fisica o la stagione, lo diciamo prima della prenotazione — non dopo.' },
        { t: 'Rispetto prima di tutto', d: 'Attraversiamo le case delle persone, non un set. Chiediamo prima di fotografare, paghiamo il giusto e non lasciamo nulla dietro di noi.' },
      ],
    },
    guides: {
      eyebrow: 'Le nostre guide',
      title: 'Il motivo per cui i viaggiatori ci scrivono dopo.',
      body: [
        'Le nostre guide sahariane attraversano questo Paese da decenni. Navigano a memoria, con il terreno e il cielo, sanno quale valle ha acqua a marzo, quale famiglia visitare a Chinguetti e quale duna salire un’ora prima del tramonto.',
        'Sono autorizzate, formate in primo soccorso e portano comunicazione satellitare a ogni partenza. E vi faranno ridere per una settimana.',
      ],
      img: 'plateau-two-travellers',
      stats: [
        { n: '5', l: 'lingue parlate dalla nostra squadra' },
        { n: '100%', l: 'guide e staff mauritani' },
        { n: '24/7', l: 'assistenza per tutta la durata del viaggio' },
      ],
    },
    safety: {
      eyebrow: 'Viaggiare sicuri',
      title: 'Cosa facciamo perché possiate rilassarvi.',
      items: [
        'Ogni spostamento nel deserto avviene con guide autorizzate e 4×4 mantenuti, mai da soli.',
        'Telefono o beacon satellitare a ogni partenza nel deserto, e un contatto quotidiano con il nostro ufficio.',
        'Itinerari pianificati nelle regioni ufficialmente aperte al turismo, aggiornati di continuo.',
        'Accoglienza in aeroporto all’arrivo e un contatto locale raggiungibile a qualsiasi ora del viaggio.',
        'Equipaggio formato in primo soccorso, riserve d’acqua e attrezzatura di recupero completa su ogni veicolo.',
      ],
      img: 'beach-convoy',
    },
    mission: {
      eyebrow: 'La nostra missione',
      quote: 'Mostrare la Mauritania al mondo senza cambiare ciò che la rende degna di essere mostrata.',
      body: 'Vogliamo che i viaggiatori arrivino curiosi e ripartano legati — e che i villaggi, le guide e le famiglie che li ospitano stiano meglio perché sono venuti.',
      cta: 'Progetta il viaggio con noi',
      waMsg: 'Buongiorno, ho letto di voi e vorrei organizzare un viaggio in Mauritania.',
    },
  },

  guidePage: {
    hero: {
      eyebrow: 'Prima di partire',
      title: 'Guida di viaggio Mauritania',
      sub: 'Tutto quello che i viaggiatori ci chiedono, con risposte oneste. Se qualcosa resta poco chiaro, scriveteci: rispondiamo personalmente.',
      img: 'adrar-road-mesa',
    },
    sections: [
      {
        id: 'when',
        t: 'Quando andare in Mauritania',
        body: [
          'La stagione va da **ottobre ad aprile**. Le giornate stanno fra 22 e 32 °C, le notti nel deserto scendono a 8–15 °C e la luce è al suo meglio. Dicembre e gennaio sono i mesi più freschi e più richiesti.',
          'Da **maggio a settembre** l’interno supera regolarmente i 45 °C e viaggiare nel deserto diventa davvero faticoso e, in alcuni punti, pericoloso. Non organizziamo spedizioni a luglio e agosto.',
          'L’**harmattan**, un vento secco di polvere, può ridurre la visibilità per qualche giorno fra dicembre e febbraio. La costa resta più mite e ventilata tutto l’anno: il Banc d’Arguin e Nouakchott restano piacevoli al di fuori della piena estate.',
        ],
      },
      {
        id: 'visa',
        t: 'Visto e ingresso',
        body: [
          'La maggior parte dei viaggiatori europei e nordamericani ottiene il **visto all’arrivo** all’aeroporto internazionale di Nouakchott–Oumtounsy e ai principali valichi terrestri. Viene rilasciato sul posto, di norma valido 30 giorni, e si paga in **euro contanti**.',
          'Servono un passaporto valido almeno sei mesi, un biglietto di uscita o ritorno e un indirizzo nel Paese — forniamo una lettera di conferma a ogni viaggiatore che ospitiamo.',
          'Regole e tariffe possono cambiare con poco preavviso, e alcune nazionalità devono ottenere il visto in anticipo. Indicateci la vostra nazionalità quando ci scrivete e confermeremo i requisiti aggiornati prima di qualsiasi prenotazione.',
        ],
      },
      {
        id: 'pack',
        t: 'Cosa mettere in valigia',
        body: [
          '**Abbigliamento.** Strati leggeri, larghi e coprenti per il giorno; un pile o una giacca calda e pantaloni lunghi per le notti nel deserto, davvero fredde da dicembre a febbraio. Una sciarpa o *chèche* è l’oggetto più utile che avrete — contro sole, polvere e vento.',
          '**Scarpe.** Scarpe da camminata chiuse più sandali per il campo e la sabbia. Portate più calze di quante pensiate.',
          '**Sole e polvere.** Crema solare ad alta protezione, burrocacao, occhiali da sole e una custodia stagna per le fotocamere — la sabbia fine entra ovunque.',
          '**Pratico.** Frontalino, power bank (al bivacco non c’è elettricità), adattatore universale, borraccia, farmaci personali, salviette e un piccolo kit di primo soccorso. Noi forniamo acqua, giacigli, materassi e tutta l’attrezzatura da campo.',
          '**Denaro.** Portate euro in contanti. Le carte non sono accettate quasi da nessuna parte fuori da pochi hotel di Nouakchott, e i bancomat sono inaffidabili. La valuta locale è l’ouguiya (MRU).',
        ],
      },
      {
        id: 'safety',
        t: 'La sicurezza in Mauritania',
        body: [
          'La Mauritania è tranquilla, e le regioni che i viaggiatori visitano — Nouakchott, la costa atlantica, l’Adrar, il corridoio ferroviario — sono considerate stabili e sono percorse regolarmente da visitatori europei. I reati violenti contro i turisti sono molto rari e la cultura dell’ospitalità verso gli ospiti è fortissima.',
          'I rischi veri qui sono ambientali, non politici: caldo, disidratazione, sabbia molle e distanza dai soccorsi medici. Per questo nel deserto si viaggia con guide autorizzate e mezzi attrezzati, mai in autonomia.',
          'Restiamo nelle zone ufficialmente aperte al turismo, evitiamo del tutto le regioni di confine orientali, portiamo comunicazione satellitare e ci colleghiamo ogni giorno con il nostro ufficio. Stipulate un’assicurazione di viaggio che copra il deserto e leggete le indicazioni aggiornate del vostro governo prima di prenotare.',
        ],
      },
      {
        id: 'culture',
        t: 'Cultura e tradizioni',
        body: [
          'La Mauritania è una repubblica islamica e la vita quotidiana la segue: cinque preghiere, il venerdì come giorno di riposo, **nessun alcol in tutto il Paese** e un mese di digiuno durante il Ramadan, quando non si mangia né si beve in pubblico durante il giorno.',
          'Vestitevi in modo sobrio: spalle e ginocchia coperte, per tutti. Le donne non devono coprirsi i capelli, ma un foulard è utile e apprezzato nei villaggi e nelle moschee.',
          'Salutate prima di chiedere qualsiasi cosa: una stretta di mano e qualche parola su salute e famiglia vengono prima degli affari. Accettate sempre il tè se ve lo offrono; i tre bicchieri richiedono un’ora e rifiutarli è l’unica cosa che sorprende davvero.',
          '**Fotografia.** Chiedete prima di fotografare qualcuno, soprattutto le donne, e accettate un no. Non fotografate mai posti militari, checkpoint o edifici governativi. La vostra guida vi dirà quando si può.',
          'Mangiate e passate le cose con la mano destra. E se vi invitano in casa, sarete nutriti molto più di quanto riusciate — non è facoltativo.',
        ],
      },
      {
        id: 'transport',
        t: 'Come ci si sposta',
        body: [
          '**Voli.** Nouakchott–Oumtounsy (NKC) è la porta d’ingresso principale, con collegamenti da Parigi, Casablanca, Istanbul, Madrid e Dakar. In inverno voli charter stagionali raggiungono a volte direttamente Atar.',
          '**Su strada.** La strada Nouakchott–Atar è asfaltata e richiede circa sei ore. Oltre, è tutta pista e serve un 4×4. Le distanze sono lunghe e i distributori molto distanti fra loro.',
          '**Il treno del ferro.** Gratuito, indimenticabile e completamente non regolamentato. Lo prendiamo con attrezzatura, cibo e guide — non è cosa da tentare da soli.',
          '**Con noi.** Tutti i nostri viaggi usano 4×4 privati e mantenuti, con autisti esperti del deserto, compresi i trasferimenti dall’aeroporto a qualsiasi ora.',
        ],
      },
    ],
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'La Mauritania è sicura per i turisti?', a: 'Sì, nelle regioni in cui viaggiamo. Nouakchott, la costa, l’Adrar e il corridoio ferroviario sono tranquilli e regolarmente visitati da viaggiatori europei. Usiamo guide autorizzate, restiamo nelle zone aperte al turismo, portiamo comunicazione satellitare e ci aggiorniamo ogni giorno. Leggete comunque le indicazioni aggiornate del vostro governo.' },
      { q: 'Serve il visto?', a: 'La maggior parte delle nazionalità riceve il visto all’arrivo all’aeroporto di Nouakchott, pagato in euro contanti, di norma valido 30 giorni. Indicateci la vostra nazionalità e confermeremo le regole aggiornate, fornendo la lettera d’invito.' },
      { q: 'Qual è il periodo migliore?', a: 'Da ottobre ad aprile. Dicembre e gennaio sono i più freschi. Non organizziamo viaggi nel deserto a luglio e agosto, quando l’interno supera i 45 °C.' },
      { q: 'Si può davvero salire sul treno del ferro?', a: 'Sì. I viaggiatori viaggiano sopra il minerale, nei vagoni aperti, gratuitamente. Forniamo giacigli, protezione dal vento, cibo, acqua e guide, e vi accompagniamo per tutto il tragitto.' },
      { q: 'È adatto anche a chi non è un avventuriero?', a: 'Molti dei nostri viaggiatori hanno fra i 60 e i 75 anni. I viaggi si possono costruire intorno a strutture confortevoli, tappe brevi e camminate dolci — oppure intorno a dune e vagoni aperti. Diteci quale dei due siete.' },
      { q: 'Posso viaggiare da solo, o come donna sola?', a: 'Sì. Ospitiamo regolarmente viaggiatori soli, comprese donne che viaggiano da sole, e ogni partenza è privata con la nostra squadra. La Mauritania è un Paese conservatore ma molto ospitale; la guida gestisce il contesto locale.' },
      { q: 'Come si paga?', a: 'Su questo sito non si paga nulla. Concordiamo itinerario e prezzo direttamente con voi su WhatsApp o via e-mail, e si salda in euro contanti all’arrivo oppure con bonifico in anticipo, come preferite.' },
      { q: 'Che lingue parlano le vostre guide?', a: 'Inglese, francese, italiano, arabo e hassaniya. Indicateci la vostra lingua e vi assegneremo la guida giusta.' },
      { q: 'C’è campo e internet?', a: 'In città sì, ed è economico. Nel deserto profondo e sul treno no — ed è anche il punto. Portiamo comunicazione satellitare per le emergenze.' },
      { q: 'E per i pasti e le esigenze alimentari?', a: 'I pasti sono cucinati freschi dalla nostra squadra: carne e pesce alla brace, riso, verdure, pane, frutta. Vegetariano e altre esigenze sono semplici da gestire se ce lo dite prima.' },
    ],
    cta: {
      title: 'Avete ancora una domanda?',
      sub: 'Scriveteci direttamente. Vi risponderà una persona vera della nostra squadra in Mauritania, di solito in poche ore.',
      cta: 'Chiedete su WhatsApp',
      waMsg: 'Buongiorno, ho una domanda su un viaggio in Mauritania.',
    },
  },

  contactPage: {
    hero: {
      eyebrow: 'Contatti',
      title: 'Progettiamo il vostro viaggio.',
      sub: 'Diteci chi viaggia, più o meno quando e cosa vorreste vedere. Vi risponderemo con un itinerario, un prezzo e consigli onesti — senza impegno.',
      img: 'dune-sunset-crew',
    },
    methods: {
      whatsapp: { t: 'WhatsApp', d: 'Il modo più rapido per raggiungerci. Rispondiamo personalmente, di solito in poche ore.', a: 'Inizia la conversazione' },
      email: { t: 'E-mail', d: 'Per itinerari dettagliati, documenti e prenotazioni di gruppo.', a: 'Scrivici' },
      phone: { t: 'Telefono', d: 'Chiamateci direttamente negli orari d’ufficio mauritani (GMT).', a: 'Chiama ora' },
      location: { t: 'Dove siamo', d: 'Nouakchott, Mauritania — con squadre ad Atar e Nouadhibou.', a: 'Apri in Google Maps' },
    },
    form: {
      eyebrow: 'Richiesta',
      title: 'Raccontateci il vostro viaggio.',
      sub: 'Questo modulo apre WhatsApp con il messaggio già pronto: così nulla si perde in una cartella spam.',
      name: 'Il vostro nome',
      namePh: 'Anna Rossi',
      email: 'E-mail',
      emailPh: 'tu@esempio.com',
      country: 'Paese',
      countryPh: 'Italia',
      people: 'Viaggiatori',
      dates: 'Date approssimative',
      datesPh: 'Febbraio 2027, circa 10 giorni',
      interest: 'Cosa vi interessa di più',
      interestOptions: ['Avventura sul treno del ferro', 'Spedizione nel deserto del Sahara', 'Chinguetti, viaggio nel patrimonio', 'Ouadane, la città antica', 'Scoperta del Banc d’Arguin', 'Un viaggio privato su misura', 'Non lo so ancora'],
      message: 'Altro che dovremmo sapere',
      messagePh: 'Forma fisica, preferenze di comfort, esigenze alimentari, occasioni speciali…',
      submit: 'Invia via WhatsApp',
      submitAlt: 'oppure invia lo stesso messaggio via e-mail',
      required: 'Inserite il vostro nome e cosa vi interessa.',
      intro: 'Buongiorno, vorrei organizzare un viaggio in Mauritania.',
    },
    promise: {
      t: 'Cosa succede dopo',
      items: [
        'Rispondiamo personalmente — mai una risposta automatica.',
        'Proponiamo un itinerario, un ritmo e un prezzo chiaro, senza nulla di nascosto.',
        'Lo aggiustiamo insieme finché non è giusto. Nessun acconto finché non siete soddisfatti.',
      ],
    },
  },

  footer: {
    tagline: 'Viaggi privati guidati da locali attraverso il Sahara, le città antiche e la costa atlantica della Mauritania.',
    explore: 'Esplora',
    company: 'Agenzia',
    contact: 'Contatti',
    follow: 'Segui il viaggio',
    rights: 'Tutti i diritti riservati.',
    built: 'Ogni fotografia di questo sito è stata scattata durante i nostri viaggi.',
    waMsg: 'Buongiorno, vorrei informazioni sui vostri viaggi in Mauritania.',
  },

  a11y: {
    skip: 'Vai al contenuto',
    heroSlides: 'Fotografie principali',
    lightbox: 'Visualizzatore di fotografie',
    menu: 'Menu principale',
  },
};
