/** Testi italiani. Struttura identica a en.js. */
module.exports = {
  code: 'it',
  htmlLang: 'it',

  nav: {
    home: 'Home',
    experiences: 'Esperienze',
    destinations: 'Destinazioni',
    gallery: 'Galleria',
    about: 'Chi siamo',
    guide: 'Guida di viaggio',
    contact: 'Contatti',
    reviews: 'Recensioni',
    cta: 'WhatsApp',
    menu: 'Menu',
    close: 'Chiudi',
    language: 'Lingua',
  },

  ui: {
    explore: 'Scopri',
    exploreExperience: 'Scopri l’esperienza',
    book: 'Prenota questa esperienza',
    plan: 'Progetta la tua avventura',
    viewAll: 'Vedi tutte le esperienze',
    viewGallery: 'Apri la galleria',
    location: 'Luogo',
    duration: 'Durata',
    season: 'Stagione migliore',
    group: 'Gruppo',
    included: 'Cosa è incluso',
    bring: 'Cosa portare',
    priceFrom: 'da',
    highlights: 'Punti salienti',
    journey: 'Cosa vivono i viaggiatori',
    photos: 'Fotografie',
    story: 'Il racconto',
    history: 'Storia',
    whyVisit: 'Perché andarci',
    moments: 'I momenti migliori',
    info: 'Informazioni pratiche',
    close: 'Chiudi',
    prev: 'Precedente',
    next: 'Successivo',
    scroll: 'Scorri',
    readMore: 'Continua a leggere',
    all: 'Tutte',
    talkToUs: 'Scrivici su WhatsApp',
    writeUs: 'Scrivici',
  },

  meta: {
    home: {
      title: 'Travel and Trips in Mauritania — Sahara e treno del ferro',
      desc: 'Viaggi privati guidati da mauritani: il Sahara, le città antiche di Chinguetti e Ouadane, il leggendario treno del ferro e il Banc d’Arguin. Pensati per viaggiatori internazionali.',
    },
    experiences: {
      title: 'Esperienze — Treno del ferro, Sahara e città antiche',
      desc: 'Cinque viaggi d’autore in Mauritania: il treno del ferro, la spedizione nel Sahara, Chinguetti, Ouadane e il parco nazionale del Banc d’Arguin. Partenze private, guide locali.',
    },
    destinations: {
      title: 'Destinazioni — Chinguetti, Ouadane, Adrar, Banc d’Arguin',
      desc: 'Dove andare in Mauritania: l’altopiano dell’Adrar, gli ksour UNESCO di Chinguetti e Ouadane, il Sahara, la ferrovia del ferro, il Banc d’Arguin e Nouakchott.',
    },
    gallery: {
      title: 'Galleria — Fotografie dai nostri viaggi in Mauritania',
      desc: 'Un viaggio fotografico in Mauritania: il treno del ferro, le traversate del deserto, le città antiche, l’Atlantico e i viaggiatori che sono venuti con noi.',
    },
    about: {
      title: 'Chi siamo — Un’agenzia mauritana | Travel and Trips in Mauritania',
      desc: 'Siamo un’agenzia di viaggio mauritana che progetta viaggi privati per viaggiatori internazionali, con le nostre guide, i nostri autisti e le nostre squadre del deserto.',
    },
    guide: {
      title: 'Guida di viaggio Mauritania — Visto, sicurezza, stagione',
      desc: 'Consigli pratici e onesti per viaggiare in Mauritania: visto, stagione, sicurezza, cultura, trasporti, denaro e le domande che ci fanno più spesso.',
    },
    reviews: {
      title: 'Recensioni — Cosa dicono i viaggiatori su Google',
      desc: 'Recensioni Google autentiche dei viaggiatori che hanno attraversato la Mauritania con noi: il treno del ferro, l’Adrar, Chinguetti, Ouadane e il deserto profondo.',
    },
    contact: {
      title: 'Contatti — Progetta il tuo viaggio in Mauritania',
      desc: 'Parla con un esperto locale su WhatsApp, via e-mail o con il nostro modulo. Rispondiamo personalmente a ogni messaggio, di solito in poche ore.',
    },
  },

  hero: {
    line1: 'Scopri la Mauritania',
    line2: 'Oltre l’ordinario',
    sub: 'Città antiche, deserti infiniti e viaggi indimenticabili, con esperti locali.',
    cta1: 'Scopri le esperienze',
    cta2: 'Progetta la tua avventura',
    scroll: 'Scorri per iniziare',
    waMsg: 'Buongiorno, vorrei organizzare con voi un’avventura in Mauritania.',
  },

  home: {
    intro: {
      eyebrow: 'L’ultimo grande silenzio',
      title: 'Un Paese che il mondo non ha ancora imparato a visitare.',
      body: [
        'La Mauritania è grande quanto l’Egitto e riceve in un anno meno visitatori di quanti un solo museo europeo ne riceva in una settimana. Il novanta per cento è Sahara. Il resto è costa atlantica, valli di oasi e città di pietra a secco dove si copiavano manoscritti di astronomia mentre l’Europa costruiva ancora le sue cattedrali.',
        'Qui non ci sono folle, né vie di souvenir, né code al punto panoramico. C’è un Paese che appartiene ancora interamente a chi ci vive — e alcuni di noi che sanno come portarvici davvero.',
      ],
      stats: [
        { n: '1 200 000', l: 'km² di deserto, costa e silenzio' },
        { n: '2', l: 'siti patrimonio mondiale UNESCO' },
        { n: '704 km', l: 'di ferrovia attraverso il Sahara' },
        { n: 'XIII sec.', l: 'l’età delle biblioteche di Chinguetti' },
      ],
    },

    why: {
      eyebrow: 'Perché viaggiare con noi',
      title: 'Nata da mauritani, per viaggiatori che vogliono la cosa vera.',
      items: [
        {
          t: 'Esperti locali',
          d: 'La nostra guida Mohammed e la squadra sono mauritani, e gli itinerari sono i loro. Le recensioni in questa pagina citano lui, non un’azienda.',
          img: 'plateau-two-travellers',
        },
        {
          t: 'Esperienze autentiche',
          d: 'Il pane cotto nella sabbia, i tre bicchieri di tè, le notti con le famiglie nomadi nel deserto profondo. È così che i viaggi funzionano davvero.',
          img: 'desert-tea',
        },
        {
          t: 'Viaggi su misura',
          d: 'Partenze private e partenze giornaliere da Nouakchott. Quattro giorni o nove, hotel o campi tendati — l’itinerario si ricostruisce intorno a voi.',
          img: 'camp-sunrise',
        },
        {
          t: 'Tutto organizzato',
          d: 'Trasporto in 4×4, guida e autista locali professionisti, hotel e campi nel deserto, tutti i pasti, tè e acqua per tutto il viaggio, ingressi.',
          img: 'group-lunch-desert',
        },
      ],
    },

    featured: {
      eyebrow: 'Viaggi d’autore',
      title: 'Cinque modi di incontrare la Mauritania.',
      sub: 'Ognuno è privato, guidato dalla nostra squadra, e si può allungare, accorciare o combinare.',
    },

    destPreview: {
      eyebrow: 'Dove andiamo',
      title: 'Sette luoghi per cui vale la pena attraversare un continente.',
      cta: 'Scopri le destinazioni',
    },

    moments: {
      eyebrow: 'Momenti di viaggio',
      title: 'Le fotografie di chi è venuto con noi.',
      sub: 'Nessuna di queste immagini viene da una banca dati. Ogni scatto di questo sito è stato fatto durante uno dei nostri viaggi.',
      cta: 'Apri la galleria completa',
    },

    reviews: {
      eyebrow: 'Con le loro parole',
      title: 'Cosa dicono i viaggiatori una volta tornati a casa.',
      cta: 'Leggile su Google',
    },

    finalCta: {
      title: 'La tua avventura mauritana comincia qui.',
      sub: 'Diteci quando volete partire e cosa volete vedere.',
      cta1: 'Progetta la tua avventura',
      cta2: 'Vedi tutte le esperienze',
      waMsg: 'Buongiorno, vorrei iniziare a organizzare il mio viaggio in Mauritania.',
    },
  },

  experiencesPage: {
    hero: {
      eyebrow: 'Viaggi d’autore',
      title: 'Esperienze',
      sub: 'Cinque viaggi, tutti privati, tutti guidati dalle nostre guide. Sceglietene uno, oppure lasciate che costruiamo un itinerario che li unisca.',
    },
    outro: {
      title: 'Nessuno è esattamente ciò che cercate?',
      sub: 'Allora diteci che cosa avevate in mente.',
      cta: 'Progetta un viaggio privato',
      waMsg: 'Buongiorno, vorrei progettare un viaggio privato su misura in Mauritania.',
    },
  },

  experiences: [
    {
      id: 'ouadane-caravan-city',
      title: 'Ouadane — la città carovaniera dimenticata',
      tagline: 'Se volete sentirvi come tornati indietro di 800 anni, Ouadane è il posto giusto.',
      short: 'Una città fantasma patrimonio UNESCO nel cuore del Sahara, fondata nell’XI secolo, raggiunta attraverso l’altopiano dell’Adrar.',
      location: 'Nouakchott → Atar → Ouadane',
      duration: '4 giorni / 3 notti',
      season: '',
      group: 'Partenze giornaliere da Nouakchott',
      price: '950 €',
      priceNote: 'a persona',
      audience: 'Ideale per amanti della storia, fotografi e cercatori di silenzio',
      hero: 'ouadane-doorway-valley',
      gallery: ['ouadane-archway', 'ruins-gathering', 'red-hills-road', 'desert-tea', 'night-tent-stars', 'camp-sunrise'],
      story: [
        'Una delle città più antiche della Mauritania e patrimonio mondiale UNESCO: una città fantasma nel cuore del Sahara, tappa chiave della via carovaniera fra il Marocco e il Sudan occidentale.',
        'Fondata nell’XI secolo, fu un centro dell’oro, del sale e del commercio dei libri. Oggi è abbandonata, ma i suoi edifici in pietra, le moschee antiche e le vecchie biblioteche raccontano ancora la sua grandezza.',
        'Qui il silenzio è pesante. Si sente l’eco dei propri passi.',
      ],
      highlights: [
        'La moschea antica, le case di pietra crollate e le rovine del forte portoghese',
        'Biblioteche che custodivano manoscritti di 500 anni',
        'La valle di Ouadane e il vecchio pozzo — la vista sulla città dall’alto',
        'L’alba sulle rovine, la luce più bella di tutto il viaggio',
        'Due notti in un campo tradizionale, a dormire sotto un cielo pieno di stelle',
      ],
      journey: [
        { t: 'Giorno 1 — Nouakchott → Atar', d: 'Ritiro alle 7:00 in hotel o all’aeroporto. 4×4 attraverso il deserto fino ad Atar, con soste per il tè e le fotografie tra le dune. Cena e pernottamento ad Atar.' },
        { t: 'Giorno 2 — Atar → Ouadane', d: 'Partenza alle 8:00, due ore e mezza di pista sull’altopiano dell’Adrar tra montagne di pietra nera. Visita a piedi della città vecchia, pranzo sotto un’acacia, poi la valle di Ouadane e il vecchio pozzo. Notte in campo tendato.' },
        { t: 'Giorno 3 — Ouadane', d: 'Alle 6:00 l’alba sulle rovine. Camminata più profonda tra i vicoli nascosti e i quartieri antichi. Pomeriggio con famiglie nomadi quando sono nei paraggi. Cena e osservazione delle stelle al campo.' },
        { t: 'Giorno 4 — Ouadane → Atar → Nouakchott', d: 'Colazione e ultimo giro in città, ritorno ad Atar per il pranzo e il mercato, poi la lunga strada verso sud. Arrivo a Nouakchott verso le 22:00.' },
      ],
      included: [
        'Trasporto in 4×4 Nouakchott – Ouadane – Nouakchott',
        'Guida e autista locali professionisti',
        '1 notte in hotel ad Atar, 2 notti in campo tendato',
        'Tutti i pasti: colazione, pranzo e cena',
        'Tè e acqua per tutto il viaggio',
        'Ingressi',
      ],
      bring: 'Scarpe comode per camminare sulla pietra, cappello, occhiali da sole, crema solare, macchina fotografica, power bank.',
      waMsg: 'Buongiorno, sono interessato/a al tour di 4 giorni a Ouadane (950 €) visto sul vostro sito.',
    },
    {
      id: 'adrar-treasures',
      title: 'Tesori dell’Adrar',
      tagline: 'L’oasi di Terjit, Chinguetti e due giorni sul cammello nell’Erg Amatlich.',
      short: 'La vera Mauritania: un’oasi nascosta, due città UNESCO e un trekking in cammello senza strade, senza turisti e senza campo.',
      location: 'Nouakchott → Terjit → Chinguetti → Ouadane → Atar',
      duration: '7 giorni',
      season: '',
      group: 'Partenze private',
      price: '950 €',
      priceNote: 'a persona',
      audience: 'Ideale per chi vuole il deserto senza la folla',
      hero: 'oasis-rest-cliff',
      gallery: ['terjit-oasis-canyon', 'palms-in-dunes', 'chinguetti-minaret', 'erg-palm-line', 'camel-silhouette', 'milky-way-acacia'],
      story: [
        'Terjit è un piccolo villaggio costruito attorno a un’oasi naturale: palme, un canyon e acqua sorgiva dolce in cui fare il bagno dopo una giornata di polvere.',
        'Chinguetti è la settima città santa dell’Islam e sito UNESCO, punto chiave delle rotte commerciali che collegavano l’Africa occidentale al Mediterraneo. Le sue biblioteche conservano più di 3.000 libri, alcuni di 1.400 anni.',
        'Poi le strade finiscono. Due giorni sul cammello tra le dune dell’Erg Amatlich con una squadra beduina — il pane cotto nella sabbia, il tè con i nomadi, tende private sotto la Via Lattea.',
      ],
      highlights: [
        'L’oasi di Terjit — palme, canyon e sorgente naturale',
        'Le biblioteche antiche di Chinguetti e i manoscritti millenari',
        'Due giorni di trekking in cammello nelle dune dell’Erg Amatlich',
        'Imparare a cuocere il pane nella sabbia e la cerimonia del tè nomade',
        'Le rovine di Ouadane e il ritorno attraverso Atar',
      ],
      journey: [
        { t: 'Giorno 1 — Nouakchott', d: 'Accoglienza in aeroporto e hotel.' },
        { t: 'Giorno 2 — Nouakchott → oasi di Terjit', d: 'Cinque ore di 4×4 verso l’Adrar. Bagno nella sorgente, pranzo sotto le palme, notte in un’auberge tradizionale vicino all’oasi o in campo.' },
        { t: 'Giorno 3 — Terjit → Chinguetti', d: 'Mattina all’oasi, poi Chinguetti: le biblioteche antiche, la città di pietra e le enormi dune dorate. Tramonto dalle dune, notte in guesthouse.' },
        { t: 'Giorni 4–5 — Trekking nel deserto profondo', d: 'Incontro con la squadra beduina e i cammelli per due giorni nell’Erg Amatlich. Niente strade, niente turisti, niente campo — solo silenzio e stelle.' },
        { t: 'Giorno 6 — Deserto → Ouadane → Atar', d: 'Alba sulle dune, ritorno in cammello, poi la città fantasma UNESCO di Ouadane. Hotel ad Atar con doccia calda.' },
        { t: 'Giorno 7 — Atar → Nouakchott', d: 'Il mercato di Atar per i souvenir, poi la strada verso Nouakchott.' },
      ],
      included: [],
      bring: '',
      waMsg: 'Buongiorno, sono interessato/a al tour Tesori dell’Adrar di 7 giorni (950 €) visto sul vostro sito.',
    },
    {
      id: 'grand-crossing',
      title: 'La grande traversata',
      tagline: 'Un’oasi, una città santa, l’Occhio del Sahara e una notte con i nomadi.',
      short: 'Da Nouakchott a Nouadhibou per la via lunga: Terjit, Chinguetti, Ouadane, la struttura di Richat e Ben Amera.',
      location: 'Nouakchott → Terjit → Chinguetti → Ouadane → Ben Amera → Nouadhibou',
      duration: '6 giorni',
      season: '',
      group: 'Partenze private',
      price: '850 €',
      priceNote: 'a persona',
      audience: 'Ideale per una prima traversata completa del Paese',
      hero: 'golden-dunes',
      gallery: ['eye-rock', 'oasis-palms-dunes', 'plateau-road', 'sand-canyon', 'dune-summit-people', 'camp-dinner-sunrise'],
      story: [
        'È l’itinerario che mostra tutto il Paese in un solo viaggio. Parte dalla capitale e finisce all’Atlantico, e nel mezzo attraversa ogni paesaggio della Mauritania.',
        'Ouadane è il punto più vicino alla struttura di Richat — l’Occhio del Sahara — e la notte successiva si passa con famiglie nomadi, circa il quattro per cento della popolazione, per capire come funziona davvero la vita nel deserto.',
        'Più a nord, Ben Amera è il secondo monolito più grande del mondo, accanto a due montagne che i mauritani chiamano il maschio e la femmina.',
      ],
      highlights: [
        'L’oasi di Terjit, nata da una sorgente naturale fra due pareti',
        'Chinguetti — la settima città dell’Islam e le sue biblioteche antiche',
        'La struttura di Richat, l’Occhio del Sahara, da Ouadane',
        'Una notte con famiglie nomadi nel deserto profondo',
        'Ben Amera, secondo monolito al mondo',
        'Nouadhibou e il suo porto di pesca sull’Atlantico',
      ],
      journey: [
        { t: 'Giorno 1 — Arrivo', d: 'Accoglienza all’aeroporto di Nouakchott.' },
        { t: 'Giorno 2 — Nouakchott → Terjit', d: 'Verso l’Adrar e il villaggio-oasi di Terjit.' },
        { t: 'Giorno 3 — Terjit → Chinguetti', d: 'La settima città dell’Islam: biblioteche con oltre 3.000 libri, alcuni di 1.400 anni.' },
        { t: 'Giorno 4 — Chinguetti → Ouadane', d: 'Una delle città più antiche della Mauritania e il punto più vicino all’Occhio del Sahara. Notte con famiglie nomadi.' },
        { t: 'Giorno 5 — Ouadane → Ben Amera', d: 'Il secondo monolito più grande del mondo e le due montagne accanto.' },
        { t: 'Giorno 6 — Ben Amera → Nouadhibou', d: 'Verso nord, alla seconda città del Paese e alla sua flotta di pesca.' },
      ],
      included: [],
      bring: '',
      waMsg: 'Buongiorno, sono interessato/a alla traversata di 6 giorni fino a Nouadhibou (850 €) vista sul vostro sito.',
    },
    {
      id: 'iron-ore-train',
      title: 'Il treno del ferro',
      tagline: 'Uno dei treni più lunghi e pesanti del mondo — e ci si può salire sopra.',
      short: 'Oltre 700 km dalle miniere di Zouérat al porto di Nouadhibou, da 15 a 20 ore attraverso il Sahara.',
      location: 'Zouérat → Choum → Nouadhibou',
      duration: '15 – 20 ore di treno',
      season: 'Da novembre a febbraio',
      group: 'Con guida, da aggiungere a qualsiasi itinerario',
      price: '950 €',
      priceNote: 'a persona',
      audience: 'Per il brivido, i paesaggi e la fotografia',
      hero: 'ore-train-aerial',
      gallery: ['train-riders', 'ore-train-sunset', 'ore-train-wagons', 'train-arms-open', 'iron-ore-train-mono', 'ore-train-yard'],
      story: [
        'Il treno minerario mauritano è uno dei treni più lunghi e pesanti del mondo: oltre 700 chilometri dalla città mineraria di Zouérat al porto di Nouadhibou. Trasporta minerale di ferro attraverso il Sahara e impiega circa 15-20 ore.',
        'I viaggiatori lo prendono per avventura — spesso seduti sopra i vagoni aperti carichi di minerale, gratuitamente, oppure in una carrozza passeggeri essenziale.',
        'È un viaggio duro: polvere, temperature estreme e ore lunghe. Lo si fa per il brivido, il paesaggio, la fotografia e per vivere uno dei viaggi ferroviari più aspri del mondo.',
      ],
      highlights: [
        'Oltre 700 km di Sahara aperto in ferrovia',
        'Tramonto, notte e alba da un vagone aperto',
        'Arrivo sull’Atlantico a Nouadhibou',
        'Uno dei grandi viaggi fotografici al mondo',
      ],
      journey: [],
      included: [],
      bring: 'Occhiali di protezione, chèche, vestiti caldi, acqua e snack.',
      waMsg: 'Buongiorno, sono interessato/a al viaggio sul treno del ferro (950 €) visto sul vostro sito.',
    },
  ],

  destinationsPage: {
    hero: {
      eyebrow: 'Dove andiamo',
      title: 'Destinazioni',
      sub: 'Sette paesaggi che insieme spiegano cos’è la Mauritania: il deserto, le città di pietra nate dentro di esso e l’oceano che alla fine lo ferma.',
    },
  },

  destinations: [
    {
      id: 'chinguetti',
      name: 'Chinguetti',
      sub: 'La settima città dell’Islam',
      img: 'chinguetti-minaret',
      photos: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove'],
      story: 'Una città carovaniera mezza inghiottita dalle dune, dove sotto la sabbia sopravvivono case di pietra, un minareto del XIII secolo e migliaia di manoscritti copiati a mano. Patrimonio mondiale UNESCO dal 1996.',
      history: 'Fondata intorno al 1264 come tappa per pellegrini e mercanti diretti alla Mecca, Chinguetti divenne un centro di sapere islamico così importante che la Mauritania era conosciuta semplicemente come «la terra di Chinguetti». Le sue biblioteche conservano opere di astronomia, giurisprudenza, grammatica e medicina copiate a mano per sette secoli.',
      why: [
        'Il minareto ancora in uso più antico del Paese',
        'Biblioteche familiari dove i manoscritti sono ancora conservati e letti',
        'Un quartiere antico che l’erg si sta lentamente riprendendo',
      ],
      moments: [
        'Il richiamo alla preghiera che rimbalza sulle mura di pietra all’alba',
        'Girare la pagina di un manoscritto di astronomia di 700 anni',
        'Il tramonto dalle dune, con tutta la città sotto di voi',
      ],
      info: [
        ['Come arrivare', '1 ora da Atar in 4×4; Atar è raggiungibile via strada o con volo stagionale'],
        ['Quanto tempo', '1 – 2 notti'],
        ['Stagione migliore', 'Da ottobre ad aprile'],
        ['Da abbinare a', 'Ouadane, le dune dell’Adrar, la struttura di Richat'],
      ],
    },
    {
      id: 'ouadane',
      name: 'Ouadane',
      sub: 'La città di pietra del 1147',
      img: 'ouadane-archway',
      photos: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon'],
      story: 'Una città medievale in rovina, fatta di vicoli di pietra a secco costruiti su una rupe sopra una valle di palme — il più spettacolare dei quattro ksour antichi della Mauritania, e il più deserto.',
      history: 'Fondata nel 1147 da mercanti berberi, Ouadane si arricchì con il commercio di oro, sale e datteri e contò migliaia di abitanti. Quando nel XVI secolo le rotte carovaniere si spostarono, la città cominciò a svuotarsi e la parte bassa fu gradualmente abbandonata al deserto. È patrimonio UNESCO dal 1996.',
      why: [
        'Un’intera città abbandonata, costruita senza malta, ancora in piedi',
        'La porta d’accesso alla struttura di Richat, «l’Occhio del Sahara»',
        'Quasi nessun altro visitatore, quasi ogni giorno dell’anno',
      ],
      moments: [
        'Salire i vicoli a gradini mentre la pietra diventa oro',
        'Stare sulla terrazza più alta sopra la valle di palme',
        'Le due ore di pista sull’altopiano nero per arrivarci',
      ],
      info: [
        ['Come arrivare', '2 – 3 ore da Chinguetti attraverso l’altopiano, in 4×4'],
        ['Quanto tempo', '1 notte'],
        ['Stagione migliore', 'Da ottobre ad aprile'],
        ['Da abbinare a', 'La struttura di Richat, Chinguetti, i grandi erg'],
      ],
    },
    {
      id: 'adrar',
      name: 'Regione dell’Adrar',
      sub: 'Altopiani, canyon e valli di palme',
      img: 'terjit-oasis-canyon',
      photos: ['adrar-road-mesa', 'palm-grove', 'plateau-two-travellers', 'oasis-stone-wall'],
      story: 'Il cuore della Mauritania sahariana: un altopiano di roccia nera inciso da canyon, con oasi nascoste di palme da dattero e sorgenti calde in fondo alle gole.',
      history: 'L’Adrar è abitato da millenni: sui suoi altopiani si trovano ancora strumenti neolitici e incisioni rupestri. Culla delle città carovaniere, resta il centro culturale del Sahara mauritano, con Atar come capoluogo.',
      why: [
        'Canyon-oasi dove sorgenti calde alimentano foreste di palme',
        'Il paesaggio desertico più spettacolare del Paese',
        'La base per Chinguetti, Ouadane e le grandi dune',
      ],
      moments: [
        'Fare il bagno in una sorgente in fondo a una gola dopo una giornata di polvere',
        'La prima macchia di verde vista dall’alto di una parete',
        'La raccolta dei datteri nei palmeti a luglio',
      ],
      info: [
        ['Come arrivare', '6 ore di strada da Nouakchott, o un volo stagionale per Atar'],
        ['Quanto tempo', '3 – 7 giorni'],
        ['Stagione migliore', 'Da novembre a marzo'],
        ['Da abbinare a', 'Tutto — è qui che nasce la maggior parte dei viaggi'],
      ],
    },
    {
      id: 'sahara',
      name: 'Il deserto del Sahara',
      sub: 'Erg, silenzio e campi nomadi',
      img: 'camel-caravan-dune',
      photos: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'lone-vehicle-plain'],
      story: 'Il novanta per cento della Mauritania è deserto, e gran parte non è mai stata cartografata nel dettaglio. È qui che i viaggi diventano silenziosi.',
      history: 'Il Sahara era verde appena 6.000 anni fa; nell’interno sopravvivono pitture rupestri di bovini e giraffe. La cultura nomade che l’ha sostituito — carovane, tende, cerimonia del tè, poesia recitata di notte — è ancora viva qui come non lo è più in gran parte del Nord Africa.',
      why: [
        'Dune e mari di sabbia senza nessun altro gruppo in vista',
        'Notti sotto un cielo senza alcun inquinamento luminoso',
        'Carovane che percorrono ancora le rotte antiche',
      ],
      moments: [
        'L’istante in cui i motori si spengono e non si sente assolutamente nulla',
        'Camminare scalzi su una cresta di duna all’alba',
        'Il terzo bicchiere di tè, un’ora dopo il primo',
      ],
      info: [
        ['Come arrivare', 'In 4×4 con una guida sahariana autorizzata — sempre'],
        ['Quanto tempo', '2 – 9 giorni'],
        ['Stagione migliore', 'Da novembre a marzo'],
        ['Da abbinare a', 'Chinguetti, Ouadane, il treno del ferro'],
      ],
    },
    {
      id: 'iron-ore-route',
      name: 'La linea del treno del ferro',
      sub: '704 km di rotaia attraverso il deserto',
      img: 'iron-ore-train-mono',
      photos: ['train-riders', 'train-arms-open', 'train-night-rest'],
      story: 'Una linea, una direzione, fino a 220 vagoni: la ferrovia che porta il ferro da Zouérat all’Atlantico, e i viaggiatori che lo chiedono con gentilezza.',
      history: 'Costruita fra il 1960 e il 1963 per portare il minerale dalle miniere di Zouérat al porto di Nouadhibou, la linea attraversa 704 chilometri di Sahara aperto. Fu progettata per resistere a sabbia, calore e isolamento totale, e funziona quasi senza interruzioni da sessant’anni.',
      why: [
        'Uno degli ultimi grandi viaggi davvero gratuiti al mondo',
        'Tramonto, notte e alba da un vagone aperto',
        'Una traversata del quarto vuoto del Sahara',
      ],
      moments: [
        'Sentire il treno molto prima di vederlo',
        'La prima ora, in piedi, con il vento e la luce',
        'Arrivare all’oceano coperti di polvere di ferro',
      ],
      info: [
        ['Come arrivare', 'Raggiungiamo la linea vicino a Choum, in 4×4 da Atar'],
        ['Quanto tempo', '2 – 3 giorni, trasferimenti inclusi'],
        ['Stagione migliore', 'Da ottobre ad aprile — mai d’estate'],
        ['Da abbinare a', 'Nouadhibou, il Banc d’Arguin, l’Adrar'],
      ],
    },
    {
      id: 'banc-darguin',
      name: 'Parco nazionale del Banc d’Arguin',
      sub: 'Due milioni di uccelli fra deserto e oceano',
      img: 'arguin-pelicans',
      photos: ['arguin-birds-shore', 'camels-atlantic', 'beach-convoy'],
      story: 'Un parco di 12.000 km² patrimonio dell’umanità, fatto di banchi di sabbia, acque basse e dune, dove il Sahara finisce nell’Atlantico e gli uccelli migratori arrivano a milioni.',
      history: 'Creato nel 1976 e iscritto all’UNESCO nel 1989, il parco protegge le aree di svernamento di uccelli che arrivano fin dalla Siberia. Gli Imraguen, l’unica comunità autorizzata a pescarvi, usano ancora lance a vela tradizionali e una pesca assistita dai delfini selvatici.',
      why: [
        'Uno dei siti ornitologici più ricchi del pianeta',
        'Navigare con i pescatori Imraguen',
        'I cammelli che camminano sulla battigia con la bassa marea',
      ],
      moments: [
        'Migliaia di pellicani che si alzano tutti insieme',
        'Guidare sulla sabbia bagnata con l’oceano accanto alle ruote',
        'Il pesce grigliato sulla spiaggia mentre il sole scende',
      ],
      info: [
        ['Come arrivare', '3 – 4 ore a nord di Nouakchott in 4×4, permesso obbligatorio'],
        ['Quanto tempo', '2 – 4 giorni'],
        ['Stagione migliore', 'Da novembre ad aprile per i migratori'],
        ['Da abbinare a', 'Nouadhibou, il treno del ferro, Nouakchott'],
      ],
    },
    {
      id: 'nouakchott',
      name: 'Nouakchott',
      sub: 'La capitale sulla sabbia',
      img: 'nouakchott-fish-market',
      photos: ['atlantic-sunset-group', 'beach-arrival', 'ocean-silhouettes'],
      story: 'Una città che nel 1958 era un villaggio di poche centinaia di persone e oggi ospita un terzo del Paese — piatta, bassa, color sabbia, e molto più interessante di quanto sembri.',
      history: 'Scelta come capitale all’indipendenza nel 1960 proprio perché non apparteneva a nessuno, Nouakchott è cresciuta in modo esplosivo mentre la siccità spingeva via dalla terra le famiglie nomadi. La spiaggia dei pescatori, il mercato dei cammelli e i centri artigiani sono la migliore introduzione alla Mauritania di oggi.',
      why: [
        'Il porto di pesca, uno dei grandi spettacoli dell’Africa occidentale',
        'I mercati, l’argenteria e il museo nazionale',
        'La porta d’accesso a tutto il resto del Paese',
      ],
      moments: [
        'Centinaia di piroghe che scaricano il pescato sulla sabbia',
        'Il tramonto sulla spiaggia atlantica, con tutta la città a passeggio',
        'Il vostro primo bicchiere di tè mauritano',
      ],
      info: [
        ['Come arrivare', 'Voli internazionali per Nouakchott–Oumtounsy (NKC)'],
        ['Quanto tempo', '1 giorno all’inizio o alla fine del viaggio'],
        ['Stagione migliore', 'Tutto l’anno; l’aria costiera resta mite'],
        ['Da abbinare a', 'Il Banc d’Arguin, l’Adrar, il treno del ferro'],
      ],
    },
  ],

  galleryPage: {
    hero: {
      eyebrow: 'Fotografie',
      title: 'Galleria',
      sub: 'Ogni fotografia di questo sito è stata scattata durante uno dei nostri viaggi, dalle nostre guide e dai viaggiatori che sono venuti con noi.',
      scroll: 'Inizia il viaggio',
    },
    chapters: {
      train: { n: '01', t: 'Il treno del ferro', d: 'Dodici ore su un vagone aperto, dalle miniere di Zouérat all’Atlantico.' },
      desert: { n: '02', t: 'Traversate del deserto', d: 'Erg, bivacchi, carovane e il silenzio che si attraversa un continente per ascoltare.' },
      culture: { n: '03', t: 'Cultura', d: 'Città di pietra, biblioteche familiari, pasti condivisi e otto secoli di ospitalità.' },
      landscapes: { n: '04', t: 'Paesaggi', d: 'Canyon, oasi, banchi di sabbia e il punto in cui il Sahara cade nell’oceano.' },
      travellers: { n: '05', t: 'Viaggiatori', d: 'Le persone che sono venute con noi, e ciò che questo Paese ha fatto loro.' },
    },
    ui: { openImage: 'Apri la fotografia', of: 'di', jump: 'Vai al capitolo' },
  },

  aboutPage: {
    hero: {
      eyebrow: 'Chi siamo',
      title: 'Un\u2019agenzia mauritana, in un Paese che ne aveva bisogno.',
      sub: 'Travel and Trips in Mauritania esiste perch\u00e9 chi arriva qui incontri il Paese attraverso le persone che ci vivono.',
      img: 'flag-and-camels',
    },
    story: {
      eyebrow: 'La nostra storia',
      title: 'La nostra storia',
      body: [],
      img: 'guide-and-traveller-ridge',
    },
    pillars: {
      eyebrow: 'In cosa crediamo',
      title: 'In cosa crediamo',
      items: [],
    },
    guides: {
      eyebrow: 'Le nostre guide',
      title: 'Le nostre guide',
      body: [],
      img: 'plateau-two-travellers',
      stats: [],
    },
    safety: {
      eyebrow: 'Viaggiare sicuri',
      title: 'Viaggiare sicuri',
      items: [],
      img: 'beach-convoy',
    },
    mission: {
      eyebrow: 'La nostra missione',
      quote: 'Mostrare la Mauritania al mondo senza cambiare ci\u00f2 che la rende degna di essere mostrata.',
      body: '',
      cta: 'Progetta il viaggio con noi',
      waMsg: 'Buongiorno, vorrei organizzare un viaggio in Mauritania.',
    },
  },

  guidePage: {
    hero: {
      eyebrow: 'Prima di partire',
      title: 'Guida di viaggio Mauritania',
      sub: 'Tutto quello che i viaggiatori ci chiedono, con risposte oneste. Se qualcosa resta poco chiaro, scriveteci: rispondiamo personalmente.',
      img: 'adrar-road-mesa',
    },
    sections: [
      {
        id: 'when',
        t: 'Quando andare in Mauritania',
        body: [
          'La stagione va da **ottobre ad aprile**. Le giornate stanno fra 22 e 32 °C, le notti nel deserto scendono a 8–15 °C e la luce è al suo meglio. Dicembre e gennaio sono i mesi più freschi e più richiesti.',
          'Da **maggio a settembre** l’interno supera regolarmente i 45 °C e viaggiare nel deserto diventa davvero faticoso e, in alcuni punti, pericoloso.',
          'L’**harmattan**, un vento secco di polvere, può ridurre la visibilità per qualche giorno fra dicembre e febbraio. La costa resta più mite e ventilata tutto l’anno: il Banc d’Arguin e Nouakchott restano piacevoli al di fuori della piena estate.',
        ],
      },
      {
        id: 'visa',
        t: 'Visto e ingresso',
        body: [
          'La maggior parte dei viaggiatori europei e nordamericani ottiene il **visto all’arrivo** all’aeroporto internazionale di Nouakchott–Oumtounsy e ai principali valichi terrestri. Viene rilasciato sul posto, di norma valido 30 giorni, e si paga in **euro contanti**.',
          'Servono un passaporto valido almeno sei mesi, un biglietto di uscita o ritorno e un indirizzo nel Paese.',
          'Regole e tariffe possono cambiare con poco preavviso, e alcune nazionalità devono ottenere il visto in anticipo. Verificate i requisiti aggiornati per il vostro passaporto prima di prenotare.',
        ],
      },
      {
        id: 'pack',
        t: 'Cosa mettere in valigia',
        body: [
          '**Abbigliamento.** Strati leggeri, larghi e coprenti per il giorno; un pile o una giacca calda e pantaloni lunghi per le notti nel deserto, davvero fredde da dicembre a febbraio. Una sciarpa o *chèche* è l’oggetto più utile che avrete — contro sole, polvere e vento.',
          '**Scarpe.** Scarpe da camminata chiuse più sandali per il campo e la sabbia. Portate più calze di quante pensiate.',
          '**Sole e polvere.** Crema solare ad alta protezione, burrocacao, occhiali da sole e una custodia stagna per le fotocamere — la sabbia fine entra ovunque.',
          '**Pratico.** Frontalino, power bank (al bivacco non c’è elettricità), adattatore universale, borraccia, farmaci personali, salviette e un piccolo kit di primo soccorso.',
          '**Denaro.** Portate euro in contanti. Le carte non sono accettate quasi da nessuna parte fuori da pochi hotel di Nouakchott, e i bancomat sono inaffidabili. La valuta locale è l’ouguiya (MRU).',
        ],
      },
      {
        id: 'safety',
        t: 'La sicurezza in Mauritania',
        body: [
          'La Mauritania è tranquilla, e le regioni che i viaggiatori visitano — Nouakchott, la costa atlantica, l’Adrar, il corridoio ferroviario — sono considerate stabili e sono percorse regolarmente da visitatori europei. I reati violenti contro i turisti sono molto rari e la cultura dell’ospitalità verso gli ospiti è fortissima.',
          'I rischi veri qui sono ambientali, non politici: caldo, disidratazione, sabbia molle e distanza dai soccorsi medici. Per questo nel deserto si viaggia con guide autorizzate e mezzi attrezzati, mai in autonomia.',
          'Stipulate un’assicurazione di viaggio che copra il deserto e leggete le indicazioni aggiornate del vostro governo prima di prenotare.',
        ],
      },
      {
        id: 'culture',
        t: 'Cultura e tradizioni',
        body: [
          'La Mauritania è una repubblica islamica e la vita quotidiana la segue: cinque preghiere, il venerdì come giorno di riposo, **nessun alcol in tutto il Paese** e un mese di digiuno durante il Ramadan, quando non si mangia né si beve in pubblico durante il giorno.',
          'Vestitevi in modo sobrio: spalle e ginocchia coperte, per tutti. Le donne non devono coprirsi i capelli, ma un foulard è utile e apprezzato nei villaggi e nelle moschee.',
          'Salutate prima di chiedere qualsiasi cosa: una stretta di mano e qualche parola su salute e famiglia vengono prima degli affari. Accettate sempre il tè se ve lo offrono; i tre bicchieri richiedono un’ora e rifiutarli è l’unica cosa che sorprende davvero.',
          '**Fotografia.** Chiedete prima di fotografare qualcuno, soprattutto le donne, e accettate un no. Non fotografate mai posti militari, checkpoint o edifici governativi. La vostra guida vi dirà quando si può.',
          'Mangiate e passate le cose con la mano destra. E se vi invitano in casa, sarete nutriti molto più di quanto riusciate — non è facoltativo.',
        ],
      },
      {
        id: 'transport',
        t: 'Come ci si sposta',
        body: [
          '**Voli.** Nouakchott–Oumtounsy (NKC) è la porta d’ingresso principale, con collegamenti da Parigi, Casablanca, Istanbul, Madrid e Dakar. In inverno voli charter stagionali raggiungono a volte direttamente Atar.',
          '**Su strada.** La strada Nouakchott–Atar è asfaltata e richiede circa sei ore. Oltre, è tutta pista e serve un 4×4. Le distanze sono lunghe e i distributori molto distanti fra loro.',
          '**Il treno del ferro.** Gratuito, indimenticabile e completamente non regolamentato. Non è cosa da tentare senza guida, attrezzatura e cibo.',
        ],
      },
    ],
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'La Mauritania è sicura per i turisti?', a: 'Le regioni che i viaggiatori visitano — Nouakchott, la costa atlantica, l’Adrar e il corridoio ferroviario — sono tranquille e percorse regolarmente da visitatori europei, e i reati violenti contro i turisti sono molto rari. I rischi veri sono ambientali: caldo, disidratazione, sabbia molle e distanza dai soccorsi, ed è per questo che nel deserto si viaggia con guide autorizzate e mezzi attrezzati. Leggete le indicazioni aggiornate del vostro governo prima di prenotare.' },
      { q: 'Serve il visto?', a: 'La maggior parte dei viaggiatori europei e nordamericani riceve il visto all’arrivo all’aeroporto internazionale di Nouakchott–Oumtounsy e ai principali valichi terrestri, rilasciato sul posto, di norma valido 30 giorni e pagato in euro contanti. Le regole cambiano e alcune nazionalità devono ottenerlo in anticipo: verificate per il vostro passaporto prima di prenotare.' },
      { q: 'Qual è il periodo migliore?', a: 'Da ottobre ad aprile. Le giornate stanno fra 22 e 32 °C e le notti nel deserto scendono a 8–15 °C. Dicembre e gennaio sono i più freschi. Da maggio a settembre l’interno supera regolarmente i 45 °C.' },
      { q: 'Si può davvero salire sul treno del ferro?', a: 'Sì. Il treno porta il minerale da Zouérat a Nouadhibou e i viaggiatori viaggiano sopra il minerale, nei vagoni aperti, gratuitamente. Il viaggio dura circa dodici ore, non c’è alcun riparo e la notte nel deserto è davvero fredda.' },
      { q: 'C’è campo e internet?', a: 'In città sì, ed è economico. Nel deserto profondo e sul treno no.' },
      { q: 'Come funziona con i soldi?', a: 'La valuta locale è l’ouguiya (MRU). Portate euro in contanti: le carte non sono accettate quasi da nessuna parte fuori da pochi hotel di Nouakchott e i bancomat sono inaffidabili.' },
      { q: 'Si trova alcol?', a: 'No. La Mauritania è una repubblica islamica e l’alcol non è in vendita da nessuna parte nel Paese.' },
    ],
    cta: {
      title: 'Avete ancora una domanda?',
      sub: 'Scriveteci direttamente. Vi risponderemo.',
      cta: 'Chiedete su WhatsApp',
      waMsg: 'Buongiorno, ho una domanda su un viaggio in Mauritania.',
    },
  },

  contactPage: {
    hero: {
      eyebrow: 'Contatti',
      title: 'Progettiamo il vostro viaggio.',
      sub: 'Diteci chi viaggia, più o meno quando e cosa vorreste vedere. Vi risponderemo.',
      img: 'dune-sunset-crew',
    },
    methods: {
      whatsapp: { t: 'WhatsApp', d: 'Il modo più rapido per raggiungerci.', a: 'Inizia la conversazione' },
      email: { t: 'E-mail', d: 'Per itinerari dettagliati, documenti e prenotazioni di gruppo.', a: 'Scrivici' },
      phone: { t: 'Telefono', d: 'Chiamateci direttamente.', a: 'Chiama ora' },
      location: { t: 'Dove siamo', d: 'Nouakchott, Mauritania.', a: 'Apri in Google Maps' },
    },
    map: { t: 'Dove trovarci', d: 'Il nostro ufficio è a Nouakchott. Toccate la mappa per indicazioni, orari e il profilo Google completo.' },
    form: {
      eyebrow: 'Richiesta',
      title: 'Raccontateci il vostro viaggio.',
      sub: 'Questo modulo apre WhatsApp con il messaggio già pronto: così nulla si perde in una cartella spam.',
      name: 'Il vostro nome',
      namePh: 'Anna Rossi',
      email: 'E-mail',
      emailPh: 'tu@esempio.com',
      country: 'Paese',
      countryPh: 'Italia',
      people: 'Viaggiatori',
      dates: 'Date approssimative',
      datesPh: 'Febbraio 2027, circa 10 giorni',
      interest: 'Cosa vi interessa di più',
      interestOptions: ['Avventura sul treno del ferro', 'Spedizione nel deserto del Sahara', 'Chinguetti, viaggio nel patrimonio', 'Ouadane, la città antica', 'Scoperta del Banc d’Arguin', 'Un viaggio privato su misura', 'Non lo so ancora'],
      message: 'Altro che dovremmo sapere',
      messagePh: 'Forma fisica, preferenze di comfort, esigenze alimentari, occasioni speciali…',
      submit: 'Invia via WhatsApp',
      submitAlt: 'oppure invia lo stesso messaggio via e-mail',
      required: 'Inserite il vostro nome e cosa vi interessa.',
      intro: 'Buongiorno, vorrei organizzare un viaggio in Mauritania.',
    },
    promise: {
      t: 'Cosa succede dopo',
      items: [],
    },
  },

  reviewsUi: {
    photo: 'foto',
    photos: 'foto',
    ownerReply: 'Risposta del proprietario',
    onGoogle: 'Leggi su Google',
    reviewsOnGoogle: 'recensioni su Google',
    viewProfile: 'Vedi tutte le recensioni',
    prev: 'Recensione precedente',
    next: 'Recensione successiva',
  },

  reviewsPage: {
    hero: {
      eyebrow: 'Con le loro parole',
      title: 'Recensioni',
      sub: 'Ogni recensione qui sotto è una vera recensione Google, mostrata esattamente come è stata scritta — con le parole di chi l’ha lasciata, a suo nome.',
      img: 'dune-summit-people',
    },
    cta: {
      title: 'Venite a scrivere la prossima.',
      sub: 'Diteci quando vorreste partire e costruiremo l’itinerario intorno a voi.',
      cta: 'Progetta il viaggio',
      waMsg: 'Buongiorno, ho letto le vostre recensioni e vorrei organizzare un viaggio in Mauritania.',
    },
  },

  footer: {
    tagline: 'Viaggi privati guidati da locali attraverso il Sahara, le città antiche e la costa atlantica della Mauritania.',
    explore: 'Esplora',
    company: 'Agenzia',
    contact: 'Contatti',
    follow: 'Segui il viaggio',
    rights: 'Tutti i diritti riservati.',
    built: 'Ogni fotografia di questo sito è stata scattata durante i nostri viaggi.',
    waMsg: 'Buongiorno, vorrei informazioni sui vostri viaggi in Mauritania.',
  },

  a11y: {
    skip: 'Vai al contenuto',
    heroSlides: 'Fotografie principali',
    lightbox: 'Visualizzatore di fotografie',
    menu: 'Menu principale',
  },
};
