/** Copie française. Structure identique à en.js. */
module.exports = {
  code: 'fr',
  htmlLang: 'fr',

  nav: {
    home: 'Accueil',
    experiences: 'Expériences',
    destinations: 'Destinations',
    gallery: 'Galerie',
    about: 'À propos',
    guide: 'Guide de voyage',
    contact: 'Contact',
    reviews: 'Avis',
    cta: 'WhatsApp',
    menu: 'Menu',
    close: 'Fermer',
    language: 'Langue',
  },

  ui: {
    explore: 'Découvrir',
    exploreExperience: 'Découvrir l’expérience',
    book: 'Réserver cette expérience',
    plan: 'Préparez votre aventure',
    viewAll: 'Voir toutes les expériences',
    viewGallery: 'Ouvrir la galerie',
    location: 'Lieu',
    duration: 'Durée',
    season: 'Meilleure saison',
    group: 'Groupe',
    included: 'Ce qui est inclus',
    bring: 'À emporter',
    priceFrom: 'à partir de',
    highlights: 'Points forts',
    journey: 'Ce que vivent les voyageurs',
    photos: 'Photographies',
    story: 'Le récit',
    history: 'Histoire',
    whyVisit: 'Pourquoi y aller',
    moments: 'Les plus beaux moments',
    info: 'Informations pratiques',
    close: 'Fermer',
    prev: 'Précédent',
    next: 'Suivant',
    scroll: 'Défiler',
    readMore: 'Lire la suite',
    all: 'Tout',
    talkToUs: 'Écrivez-nous sur WhatsApp',
    writeUs: 'Écrivez-nous',
  },

  meta: {
    home: {
      title: 'Travel and Trips in Mauritania — Sahara & train du fer',
      desc: 'Voyages privés guidés par des Mauritaniens : le Sahara, les cités anciennes de Chinguetti et Ouadane, le train du fer et le Banc d’Arguin.',
    },
    experiences: {
      title: 'Expériences — Train du fer, Sahara et cités anciennes',
      desc: 'Cinq voyages signature en Mauritanie : le train du fer, l’expédition saharienne, Chinguetti, Ouadane et le parc national du Banc d’Arguin. Départs privés, guides locaux.',
    },
    destinations: {
      title: 'Destinations — Chinguetti, Ouadane, Adrar, Banc d’Arguin',
      desc: 'Où aller en Mauritanie : le plateau de l’Adrar, les ksour UNESCO de Chinguetti et Ouadane, le Sahara, la voie ferrée du fer, le Banc d’Arguin et Nouakchott.',
    },
    gallery: {
      title: 'Galerie — Photographies de nos voyages en Mauritanie',
      desc: 'Un voyage photographique en Mauritanie : le train du fer, les traversées du désert, les cités anciennes, l’Atlantique et les voyageurs qui nous ont accompagnés.',
    },
    about: {
      title: 'À propos — Une agence mauritanienne | Travel and Trips in Mauritania',
      desc: 'Nous sommes une agence de voyage mauritanienne qui conçoit des voyages privés pour les voyageurs internationaux, avec nos propres guides, chauffeurs et équipes du désert.',
    },
    guide: {
      title: 'Guide de voyage Mauritanie — Visa, sécurité, saison',
      desc: 'Conseils pratiques et honnêtes pour voyager en Mauritanie : visa, saison, sécurité, culture, transports, argent et les questions que l’on nous pose le plus.',
    },
    reviews: {
      title: 'Avis — Ce que disent les voyageurs sur Google',
      desc: 'De vrais avis Google laissés par les voyageurs qui ont traversé la Mauritanie avec nous : le train du fer, l’Adrar, Chinguetti, Ouadane et le désert profond.',
    },
    contact: {
      title: 'Contact — Préparez votre voyage en Mauritanie',
      desc: 'Parlez à un expert local sur WhatsApp, par e-mail ou via notre formulaire. Nous répondons personnellement à chaque message, généralement en quelques heures.',
    },
  },

  hero: {
    line1: 'Découvrez la Mauritanie',
    line2: 'Au-delà de l’ordinaire',
    sub: 'Cités anciennes, déserts infinis et voyages inoubliables, avec des experts locaux.',
    cta1: 'Découvrir les expériences',
    cta2: 'Préparez votre aventure',
    scroll: 'Faites défiler',
    waMsg: 'Bonjour, je souhaite préparer une aventure en Mauritanie avec vous.',
  },

  home: {
    intro: {
      eyebrow: 'Le dernier grand silence',
      title: 'Un pays que le monde n’a pas encore appris à visiter.',
      body: [
        'La Mauritanie est grande comme l’Égypte et reçoit en une année moins de visiteurs qu’un seul musée européen en une semaine. Quatre-vingt-dix pour cent de son territoire est saharien. Le reste, c’est la côte atlantique, des vallées d’oasis et des villes de pierre sèche où l’on copiait des manuscrits d’astronomie quand l’Europe bâtissait encore ses cathédrales.',
        'Ici, pas de foule, pas de rue à souvenirs, pas de file d’attente au belvédère. Il y a un pays qui appartient encore entièrement à ceux qui y vivent — et quelques-uns d’entre nous qui savent vous y conduire comme il faut.',
      ],
      stats: [
        { n: '1 200 000', l: 'km² de désert, de côte et de silence' },
        { n: '2', l: 'sites inscrits au patrimoine mondial' },
        { n: '704 km', l: 'de voie ferrée à travers le Sahara' },
        { n: 'XIIIᵉ s.', l: 'l’âge des bibliothèques de Chinguetti' },
      ],
    },

    why: {
      eyebrow: 'Pourquoi voyager avec nous',
      title: 'Créée par des Mauritaniens, pour les voyageurs qui veulent le vrai.',
      items: [
        {
          t: 'Experts locaux',
          d: 'Notre guide Mohammed et son équipe sont mauritaniens, et les itinéraires sont les leurs. Les avis de cette page le citent par son nom, pas une société.',
          img: 'plateau-two-travellers',
        },
        {
          t: 'Expériences authentiques',
          d: 'Le pain cuit dans le sable, les trois verres de thé, les nuits chez les familles nomades au cœur du désert. C’est ainsi que les voyages se déroulent vraiment.',
          img: 'desert-tea',
        },
        {
          t: 'Voyages personnalisés',
          d: 'Départs privés, et départs quotidiens de Nouakchott. Quatre jours ou neuf, hôtels ou campements — l’itinéraire est rebâti autour de vous.',
          img: 'camp-sunrise',
        },
        {
          t: 'Tout est pris en charge',
          d: 'Transport 4×4, guide et chauffeur locaux professionnels, hôtels et campements, tous les repas, thé et eau tout au long, droits d’entrée.',
          img: 'group-lunch-desert',
        },
      ],
    },

    featured: {
      eyebrow: 'Voyages signature',
      title: 'Cinq façons de rencontrer la Mauritanie.',
      sub: 'Chacune est privée, encadrée par notre propre équipe, et peut être allongée, raccourcie ou combinée.',
    },

    destPreview: {
      eyebrow: 'Où nous allons',
      title: 'Sept lieux qui valent la traversée d’un continent.',
      cta: 'Découvrir les destinations',
    },

    moments: {
      eyebrow: 'Instants de voyage',
      title: 'Les photographies de ceux qui sont venus avec nous.',
      sub: 'Aucune de ces images n’est une banque d’images. Chaque photo de ce site a été prise pendant l’un de nos voyages.',
      cta: 'Ouvrir la galerie complète',
    },

    reviews: {
      eyebrow: 'En leurs mots',
      title: 'Ce que disent les voyageurs une fois rentrés.',
      cta: 'Les lire sur Google',
    },

    finalCta: {
      title: 'Votre aventure mauritanienne commence ici.',
      sub: 'Dites-nous quand vous voulez partir et ce que vous voulez voir.',
      cta1: 'Préparez votre aventure',
      cta2: 'Voir toutes les expériences',
      waMsg: 'Bonjour, je souhaite commencer à préparer mon voyage en Mauritanie.',
    },
  },

  experiencesPage: {
    hero: {
      eyebrow: 'Voyages signature',
      title: 'Expériences',
      sub: 'Cinq voyages, tous privés, tous encadrés par nos propres guides. Choisissez-en un, ou laissez-nous construire un itinéraire qui les relie.',
    },
    outro: {
      title: 'Aucun ne vous correspond tout à fait ?',
      sub: 'Alors dites-nous ce que vous aviez en tête.',
      cta: 'Concevoir un voyage privé',
      waMsg: 'Bonjour, je souhaite concevoir un voyage privé sur mesure en Mauritanie.',
    },
  },

  experiences: [
    {
      id: 'ouadane-caravan-city',
      title: 'Ouadane — la cité caravanière oubliée',
      tagline: 'Si vous voulez avoir l’impression d’avoir remonté 800 ans, Ouadane est l’endroit.',
      short: 'Une ville fantôme classée à l’UNESCO au cœur du Sahara, fondée au XIᵉ siècle, atteinte à travers le plateau de l’Adrar.',
      location: 'Nouakchott → Atar → Ouadane',
      duration: '4 jours / 3 nuits',
      season: '',
      group: 'Départs quotidiens de Nouakchott',
      price: '950 €',
      priceNote: 'par personne',
      audience: 'Idéal pour les amoureux d’histoire, les photographes et les chercheurs de silence',
      hero: 'ouadane-doorway-valley',
      gallery: ['ouadane-archway', 'ruins-gathering', 'red-hills-road', 'desert-tea', 'night-tent-stars', 'camp-sunrise'],
      story: [
        'L’une des plus anciennes villes de Mauritanie et un site du patrimoine mondial de l’UNESCO : une ville fantôme au cœur du Sahara, étape majeure de la route caravanière entre le Maroc et le Soudan occidental.',
        'Fondée au XIᵉ siècle, elle fut un centre de l’or, du sel et du commerce des livres. Aujourd’hui abandonnée, ses bâtiments de pierre, ses mosquées anciennes et ses vieilles bibliothèques racontent encore sa grandeur.',
        'Le silence y est lourd. On entend l’écho de ses propres pas.',
      ],
      highlights: [
        'La mosquée ancienne, les maisons de pierre effondrées et les ruines du fort portugais',
        'Des bibliothèques qui abritaient des manuscrits vieux de 500 ans',
        'La vallée de Ouadane et le vieux puits — la vue sur la ville depuis les hauteurs',
        'Le lever du soleil sur les ruines, la plus belle lumière du voyage',
        'Deux nuits en campement traditionnel, à dormir sous un ciel plein d’étoiles',
      ],
      journey: [
        { t: 'Jour 1 — Nouakchott → Atar', d: 'Prise en charge à 7h00 à votre hôtel ou à l’aéroport. 4×4 à travers le désert jusqu’à Atar, avec des arrêts thé et photos dans les dunes. Dîner et nuit à Atar.' },
        { t: 'Jour 2 — Atar → Ouadane', d: 'Départ à 8h00, 2h30 de piste sur le plateau de l’Adrar et ses montagnes de pierre noire. Visite à pied de la vieille ville, déjeuner sous un acacia, puis la vallée de Ouadane et le vieux puits. Nuit en campement.' },
        { t: 'Jour 3 — Ouadane', d: 'Lever du soleil à 6h00 sur les ruines. Marche plus profonde dans les ruelles cachées et les vieux quartiers. Après-midi avec des familles nomades lorsqu’elles sont proches. Dîner et observation des étoiles au campement.' },
        { t: 'Jour 4 — Ouadane → Atar → Nouakchott', d: 'Petit-déjeuner et dernière promenade, retour à Atar pour le déjeuner et le marché, puis la longue route vers le sud. Arrivée à Nouakchott vers 22h00.' },
      ],
      included: [
        'Transport 4×4 Nouakchott – Ouadane – Nouakchott',
        'Guide et chauffeur locaux professionnels',
        '1 nuit d’hôtel à Atar, 2 nuits en campement',
        'Tous les repas : petit-déjeuner, déjeuner et dîner',
        'Thé et eau tout au long du voyage',
        'Droits d’entrée',
      ],
      bring: 'Chaussures confortables pour marcher sur la pierre, chapeau, lunettes de soleil, crème solaire, appareil photo, batterie externe.',
      waMsg: 'Bonjour, je suis intéressé(e) par le circuit de 4 jours à Ouadane (950 €) vu sur votre site.',
    },
    {
      id: 'adrar-treasures',
      title: 'Trésors de l’Adrar',
      tagline: 'L’oasis de Terjit, Chinguetti et deux jours à dos de chameau dans l’Erg Amatlich.',
      short: 'La vraie Mauritanie : une oasis cachée, deux cités UNESCO et une méharée sans routes, sans touristes et sans réseau.',
      location: 'Nouakchott → Terjit → Chinguetti → Ouadane → Atar',
      duration: '7 jours',
      season: '',
      group: 'Départs privés',
      price: '950 €',
      priceNote: 'par personne',
      audience: 'Idéal pour ceux qui veulent le désert sans la foule',
      hero: 'oasis-rest-cliff',
      gallery: ['terjit-oasis-canyon', 'palms-in-dunes', 'chinguetti-minaret', 'erg-palm-line', 'camel-silhouette', 'milky-way-acacia'],
      story: [
        'Terjit est un petit village bâti autour d’une oasis naturelle : des palmiers, un canyon et une source d’eau douce où l’on se baigne après une journée de poussière.',
        'Chinguetti est la septième ville sainte de l’islam et un site UNESCO, point clé des routes commerciales reliant l’Afrique de l’Ouest à la Méditerranée. Ses bibliothèques conservent plus de 3 000 ouvrages, dont certains ont 1 400 ans.',
        'Puis les routes s’arrêtent. Deux jours à dos de chameau dans les dunes de l’Erg Amatlich avec une équipe bédouine — le pain cuit dans le sable, le thé avec les nomades, des tentes privées sous la Voie lactée.',
      ],
      highlights: [
        'L’oasis de Terjit — palmiers, canyon et source naturelle',
        'Les bibliothèques anciennes de Chinguetti et leurs manuscrits millénaires',
        'Deux jours de méharée dans les dunes de l’Erg Amatlich',
        'Apprendre à cuire le pain dans le sable et la cérémonie du thé nomade',
        'Les ruines de Ouadane et le retour par Atar',
      ],
      journey: [
        { t: 'Jour 1 — Nouakchott', d: 'Accueil à l’aéroport et hôtel.' },
        { t: 'Jour 2 — Nouakchott → oasis de Terjit', d: 'Cinq heures de 4×4 vers l’Adrar. Baignade dans la source, déjeuner sous les palmiers, nuit en auberge traditionnelle près de l’oasis ou en campement.' },
        { t: 'Jour 3 — Terjit → Chinguetti', d: 'Matinée à l’oasis, puis Chinguetti : les bibliothèques anciennes, la ville de pierre et les immenses dunes dorées. Coucher de soleil depuis les dunes, nuit en maison d’hôtes.' },
        { t: 'Jours 4–5 — Méharée dans le désert profond', d: 'Rencontre avec l’équipe bédouine et les chameaux pour deux jours dans l’Erg Amatlich. Ni routes, ni touristes, ni réseau — le silence et les étoiles.' },
        { t: 'Jour 6 — Désert → Ouadane → Atar', d: 'Lever du soleil sur les dunes, retour à dos de chameau, puis la cité fantôme UNESCO de Ouadane. Hôtel à Atar avec douche chaude.' },
        { t: 'Jour 7 — Atar → Nouakchott', d: 'Le marché d’Atar pour les souvenirs, puis la route vers Nouakchott.' },
      ],
      included: [],
      bring: '',
      waMsg: 'Bonjour, je suis intéressé(e) par le circuit Trésors de l’Adrar de 7 jours (950 €) vu sur votre site.',
    },
    {
      id: 'grand-crossing',
      title: 'La grande traversée',
      tagline: 'Une oasis, une ville sainte, l’Œil du Sahara et une nuit chez les nomades.',
      short: 'De Nouakchott à Nouadhibou par le long chemin : Terjit, Chinguetti, Ouadane, la structure de Richat et Ben Amera.',
      location: 'Nouakchott → Terjit → Chinguetti → Ouadane → Ben Amera → Nouadhibou',
      duration: '6 jours',
      season: '',
      group: 'Départs privés',
      price: '850 €',
      priceNote: 'par personne',
      audience: 'Idéal pour une première traversée complète du pays',
      hero: 'golden-dunes',
      gallery: ['eye-rock', 'oasis-palms-dunes', 'plateau-road', 'sand-canyon', 'dune-summit-people', 'camp-dinner-sunrise'],
      story: [
        'C’est l’itinéraire qui montre tout le pays en un seul voyage. Il part de la capitale et finit à l’Atlantique, et entre les deux il traverse tous les paysages de la Mauritanie.',
        'Ouadane est le point le plus proche de la structure de Richat — l’Œil du Sahara — et la nuit qui suit se passe chez des familles nomades, environ quatre pour cent de la population, pour comprendre comment fonctionne vraiment la vie du désert.',
        'Plus au nord, Ben Amera est le deuxième plus grand monolithe du monde, dressé près de deux montagnes que les Mauritaniens appellent le mâle et la femelle.',
      ],
      highlights: [
        'L’oasis de Terjit, née d’une source naturelle entre deux falaises',
        'Chinguetti — la septième ville de l’islam et ses bibliothèques anciennes',
        'La structure de Richat, l’Œil du Sahara, depuis Ouadane',
        'Une nuit chez des familles nomades dans le désert profond',
        'Ben Amera, deuxième monolithe du monde',
        'Nouadhibou et son port de pêche sur l’Atlantique',
      ],
      journey: [
        { t: 'Jour 1 — Arrivée', d: 'Accueil à l’aéroport de Nouakchott.' },
        { t: 'Jour 2 — Nouakchott → Terjit', d: 'Vers l’Adrar et le village-oasis de Terjit.' },
        { t: 'Jour 3 — Terjit → Chinguetti', d: 'La septième ville de l’islam : des bibliothèques de plus de 3 000 livres, certains vieux de 1 400 ans.' },
        { t: 'Jour 4 — Chinguetti → Ouadane', d: 'L’une des plus anciennes villes de Mauritanie et le point le plus proche de l’Œil du Sahara. Nuit chez des familles nomades.' },
        { t: 'Jour 5 — Ouadane → Ben Amera', d: 'Le deuxième plus grand monolithe du monde et les deux montagnes voisines.' },
        { t: 'Jour 6 — Ben Amera → Nouadhibou', d: 'Vers le nord et la deuxième ville du pays, avec sa flotte de pêche.' },
      ],
      included: [],
      bring: '',
      waMsg: 'Bonjour, je suis intéressé(e) par la traversée de 6 jours jusqu’à Nouadhibou (850 €) vue sur votre site.',
    },
    {
      id: 'iron-ore-train',
      title: 'Le train du fer',
      tagline: 'L’un des trains les plus longs et les plus lourds du monde — et on peut monter dessus.',
      short: 'Plus de 700 km des mines de Zouérat au port de Nouadhibou, 15 à 20 heures à travers le Sahara.',
      location: 'Zouérat → Choum → Nouadhibou',
      duration: '15 – 20 heures de train',
      season: 'De novembre à février',
      group: 'Encadré, à ajouter à n’importe quel itinéraire',
      price: '950 €',
      priceNote: 'par personne',
      audience: 'Pour le frisson, les paysages et la photographie',
      hero: 'ore-train-aerial',
      gallery: ['train-riders', 'ore-train-sunset', 'ore-train-wagons', 'train-arms-open', 'iron-ore-train-mono', 'ore-train-yard'],
      story: [
        'Le train minéralier mauritanien est l’un des trains les plus longs et les plus lourds du monde : plus de 700 kilomètres depuis la ville minière de Zouérat jusqu’au port de Nouadhibou. Il transporte le minerai de fer à travers le Sahara et met environ 15 à 20 heures.',
        'Les voyageurs le prennent pour l’aventure — souvent assis sur les wagons ouverts chargés de minerai, gratuitement, ou dans une voiture voyageurs sommaire.',
        'C’est un trajet rude : poussière, températures extrêmes et longues heures. On le fait pour le frisson, les paysages, la photographie, et pour vivre l’un des voyages ferroviaires les plus rudes du monde.',
      ],
      highlights: [
        'Plus de 700 km de Sahara ouvert par le rail',
        'Coucher de soleil, nuit et aube depuis un wagon ouvert',
        'Arrivée sur l’Atlantique à Nouadhibou',
        'L’un des grands voyages photographiques au monde',
      ],
      journey: [],
      included: [],
      bring: 'Lunettes de protection, chèche, vêtements chauds, eau et en-cas.',
      waMsg: 'Bonjour, je suis intéressé(e) par le voyage à bord du train du fer (950 €) vu sur votre site.',
    },
  ],

  rally: {
    eyebrow: 'Une photo de l’édition précédente',
    title: 'Au cœur du désert',
    body: [
      'Un instant immortel dans la mémoire de tous ceux qui en ont vécu les détails au plus profond du sable, là où le rugissement des moteurs rencontre la passion de l’aventure, créant des moments inoubliables qui laissent des souvenirs gravés sur le visage du désert.',
      'Les préparatifs sont en cours, et le sol commence à murmurer le défi qui approche. Tenez-vous prêts et gardez les yeux ouverts. La prochaine édition du rallye ne passera pas inaperçue. Le désert appelle.',
    ],
    years: '2025 · 2026',
    cta: 'Renseignez-vous sur le rallye',
    waMsg: 'Bonjour, je souhaite des informations sur le rallye du désert.',
    photos: ['desert-track-vehicle', 'dune-sunset-glow'],
  },

  destinationsPage: {
    hero: {
      eyebrow: 'Où nous allons',
      title: 'Destinations',
      sub: 'Sept paysages qui, ensemble, expliquent ce qu’est la Mauritanie : le désert, les cités de pierre nées en son sein, et l’océan qui finit par l’arrêter.',
    },
  },

  destinations: [
    {
      id: 'chinguetti',
      name: 'Chinguetti',
      sub: 'La septième ville de l’islam',
      img: 'chinguetti-minaret',
      photos: ['ruins-gathering', 'oasis-stone-wall', 'palm-grove'],
      story: 'Une cité caravanière à demi avalée par les dunes, où subsistent sous le sable des maisons de pierre, un minaret du XIIIᵉ siècle et des milliers de manuscrits copiés à la main. Patrimoine mondial de l’UNESCO depuis 1996.',
      history: 'Fondée vers 1264 comme étape pour les pèlerins et les marchands en route vers La Mecque, Chinguetti devint un centre du savoir islamique si important que la Mauritanie fut longtemps appelée simplement « le pays de Chinguetti ». Ses bibliothèques conservent des ouvrages d’astronomie, de jurisprudence, de grammaire et de médecine copiés à la main pendant sept siècles.',
      why: [
        'Le plus ancien minaret encore en usage du pays',
        'Des bibliothèques familiales où les manuscrits sont toujours conservés et lus',
        'Un vieux quartier lentement repris par l’erg',
      ],
      moments: [
        'L’appel à la prière résonnant sur les murs de pierre à l’aube',
        'Tourner la page d’un manuscrit d’astronomie de 700 ans',
        'Le coucher du soleil depuis les dunes, toute la ville en contrebas',
      ],
      info: [
        ['Y aller', '1 heure d’Atar en 4×4 ; Atar est accessible par la route ou par vol saisonnier'],
        ['Durée conseillée', '1 – 2 nuits'],
        ['Meilleure saison', 'D’octobre à avril'],
        ['À combiner avec', 'Ouadane, les dunes de l’Adrar, la structure de Richat'],
      ],
    },
    {
      id: 'ouadane',
      name: 'Ouadane',
      sub: 'La cité de pierre de 1147',
      img: 'ouadane-archway',
      photos: ['ruins-gathering', 'adrar-road-mesa', 'terjit-oasis-canyon'],
      story: 'Une ville médiévale en ruines, faite de ruelles de pierre sèche bâties sur une falaise au-dessus d’une palmeraie — le plus spectaculaire des quatre ksour anciens de Mauritanie, et le plus désert.',
      history: 'Fondée en 1147 par des marchands berbères, Ouadane s’enrichit du commerce de l’or, du sel et des dattes et compta plusieurs milliers d’habitants. Quand les routes caravanières se déplacèrent au XVIᵉ siècle, la ville commença à se vider et la cité basse fut peu à peu abandonnée au désert. Elle est inscrite à l’UNESCO depuis 1996.',
      why: [
        'Une ville abandonnée entière, bâtie sans mortier, toujours debout',
        'La porte d’entrée vers la structure de Richat, « l’Œil du Sahara »',
        'Presque aucun autre visiteur, presque tous les jours de l’année',
      ],
      moments: [
        'Monter les ruelles en escalier quand la pierre devient or',
        'Se tenir sur la plus haute terrasse au-dessus de la palmeraie',
        'Les deux heures de piste sur le plateau noir pour y arriver',
      ],
      info: [
        ['Y aller', '2 – 3 heures depuis Chinguetti à travers le plateau, en 4×4'],
        ['Durée conseillée', '1 nuit'],
        ['Meilleure saison', 'D’octobre à avril'],
        ['À combiner avec', 'La structure de Richat, Chinguetti, les grands ergs'],
      ],
    },
    {
      id: 'adrar',
      name: 'Région de l’Adrar',
      sub: 'Plateaux, canyons et vallées de palmiers',
      img: 'terjit-oasis-canyon',
      photos: ['adrar-road-mesa', 'palm-grove', 'plateau-two-travellers', 'oasis-stone-wall'],
      story: 'Le cœur de la Mauritanie saharienne : un haut plateau de roche noire entaillé de canyons, avec des oasis cachées de palmiers-dattiers et des sources chaudes au fond des gorges.',
      history: 'L’Adrar est habité depuis des millénaires — on y trouve encore des outils néolithiques et des gravures rupestres sur les plateaux. Berceau des cités caravanières, il reste le centre culturel du Sahara mauritanien, avec Atar pour capitale.',
      why: [
        'Des canyons-oasis où des sources chaudes nourrissent des palmeraies',
        'Les paysages désertiques les plus spectaculaires du pays',
        'La base pour Chinguetti, Ouadane et les grandes dunes',
      ],
      moments: [
        'Se baigner dans une source au fond d’une gorge après une journée de poussière',
        'La première tache de vert aperçue du haut d’une falaise',
        'La récolte des dattes dans les palmeraies en juillet',
      ],
      info: [
        ['Y aller', '6 heures de route depuis Nouakchott, ou un vol saisonnier vers Atar'],
        ['Durée conseillée', '3 – 7 jours'],
        ['Meilleure saison', 'De novembre à mars'],
        ['À combiner avec', 'Tout — c’est ici que se construisent la plupart des voyages'],
      ],
    },
    {
      id: 'sahara',
      name: 'Le désert du Sahara',
      sub: 'Ergs, silence et campements nomades',
      img: 'camel-caravan-dune',
      photos: ['dune-joy', 'dune-sunset-crew', 'desert-campfire', 'lone-vehicle-plain'],
      story: 'Quatre-vingt-dix pour cent de la Mauritanie est désertique, et une grande partie n’a jamais été cartographiée en détail. C’est là que les voyages deviennent silencieux.',
      history: 'Le Sahara était vert il y a seulement 6 000 ans ; des peintures rupestres de bovins et de girafes subsistent à l’intérieur des terres. La culture nomade qui lui a succédé — caravanes, tentes, cérémonie du thé, poésie récitée la nuit — est encore vivante ici comme elle ne l’est plus dans la plupart de l’Afrique du Nord.',
      why: [
        'Des dunes et des mers de sable sans aucun autre groupe en vue',
        'Des nuits sous un ciel sans la moindre pollution lumineuse',
        'Des caravanes qui empruntent encore les anciennes routes',
      ],
      moments: [
        'L’instant où les moteurs s’arrêtent et où l’on n’entend absolument rien',
        'Marcher pieds nus sur une crête de dune au lever du jour',
        'Le troisième verre de thé, une heure après le premier',
      ],
      info: [
        ['Y aller', 'En 4×4 avec un guide saharien agréé — toujours'],
        ['Durée conseillée', '2 – 9 jours'],
        ['Meilleure saison', 'De novembre à mars'],
        ['À combiner avec', 'Chinguetti, Ouadane, le train du fer'],
      ],
    },
    {
      id: 'iron-ore-route',
      name: 'La ligne du train du fer',
      sub: '704 km de rail à travers le désert',
      img: 'iron-ore-train-mono',
      photos: ['train-riders', 'train-arms-open', 'train-night-rest'],
      story: 'Une voie, une direction, jusqu’à 220 wagons : la ligne qui transporte le fer de Zouérat jusqu’à l’Atlantique, et les voyageurs qui le demandent poliment.',
      history: 'Construite entre 1960 et 1963 pour acheminer le minerai des mines de Zouérat au port de Nouadhibou, la ligne traverse 704 kilomètres de Sahara ouvert. Conçue pour résister au sable, à la chaleur et à l’isolement total, elle fonctionne presque sans interruption depuis soixante ans.',
      why: [
        'L’un des derniers grands voyages véritablement gratuits au monde',
        'Coucher de soleil, nuit et aube depuis un wagon ouvert',
        'Une traversée du quart vide du Sahara',
      ],
      moments: [
        'Entendre le train bien avant de le voir',
        'La première heure, debout, avec le vent et la lumière',
        'Arriver à l’océan couvert de poussière de fer',
      ],
      info: [
        ['Y aller', 'Nous rejoignons la voie près de Choum, en 4×4 depuis Atar'],
        ['Durée conseillée', '2 – 3 jours, transferts compris'],
        ['Meilleure saison', 'D’octobre à avril — jamais en été'],
        ['À combiner avec', 'Nouadhibou, le Banc d’Arguin, l’Adrar'],
      ],
    },
    {
      id: 'banc-darguin',
      name: 'Parc national du Banc d’Arguin',
      sub: 'Deux millions d’oiseaux entre désert et océan',
      img: 'arguin-pelicans',
      photos: ['arguin-birds-shore', 'camels-atlantic', 'beach-convoy'],
      story: 'Un parc de 12 000 km² classé au patrimoine mondial, fait de bancs de sable, d’eaux peu profondes et de dunes, où le Sahara s’achève dans l’Atlantique et où les oiseaux migrateurs arrivent par millions.',
      history: 'Créé en 1976 et inscrit à l’UNESCO en 1989, le parc protège les zones d’hivernage d’oiseaux venus d’aussi loin que la Sibérie. Les Imraguen, seule communauté autorisée à y pêcher, utilisent encore des lanches à voile traditionnelles et une pêche assistée par les dauphins sauvages.',
      why: [
        'L’un des sites ornithologiques les plus riches de la planète',
        'Naviguer avec les pêcheurs imraguen',
        'Les dromadaires longeant l’écume à marée basse',
      ],
      moments: [
        'Des milliers de pélicans s’envolant d’un seul coup',
        'Rouler sur le sable mouillé, l’océan contre les roues',
        'Le poisson grillé sur la plage au soleil couchant',
      ],
      info: [
        ['Y aller', '3 – 4 heures au nord de Nouakchott en 4×4, permis obligatoire'],
        ['Durée conseillée', '2 – 4 jours'],
        ['Meilleure saison', 'De novembre à avril pour les migrateurs'],
        ['À combiner avec', 'Nouadhibou, le train du fer, Nouakchott'],
      ],
    },
    {
      id: 'nouakchott',
      name: 'Nouakchott',
      sub: 'La capitale posée sur le sable',
      img: 'nouakchott-fish-market',
      photos: ['atlantic-sunset-group', 'beach-arrival', 'ocean-silhouettes'],
      story: 'Une ville qui n’était qu’un village de quelques centaines d’habitants en 1958 et abrite aujourd’hui un tiers du pays — plate, basse, couleur sable, et bien plus intéressante qu’il n’y paraît.',
      history: 'Choisie comme capitale à l’indépendance en 1960 précisément parce qu’elle n’appartenait à personne, Nouakchott a explosé à mesure que la sécheresse chassait les familles nomades. Sa plage de pêche, son marché aux chameaux et ses centres artisanaux sont la meilleure introduction à la vie mauritanienne d’aujourd’hui.',
      why: [
        'Le port de pêche, l’un des grands spectacles d’Afrique de l’Ouest',
        'Les marchés, l’argenterie et le musée national',
        'La porte d’entrée vers tout le reste du pays',
      ],
      moments: [
        'Des centaines de pirogues débarquant la pêche sur le sable',
        'Le coucher du soleil sur la plage, toute la ville en promenade',
        'Votre premier verre de thé mauritanien',
      ],
      info: [
        ['Y aller', 'Vols internationaux vers Nouakchott–Oumtounsy (NKC)'],
        ['Durée conseillée', '1 journée au début ou à la fin du voyage'],
        ['Meilleure saison', 'Toute l’année ; l’air côtier reste doux'],
        ['À combiner avec', 'Le Banc d’Arguin, l’Adrar, le train du fer'],
      ],
    },
  ],

  galleryPage: {
    hero: {
      eyebrow: 'Photographies',
      title: 'Galerie',
      sub: 'Chaque photographie de ce site a été prise pendant l’un de nos voyages, par nos guides et par les voyageurs qui nous ont accompagnés.',
      scroll: 'Commencer le voyage',
    },
    chapters: {
      train: { n: '01', t: 'Le train du fer', d: 'Douze heures sur un wagon ouvert, des mines de Zouérat jusqu’à l’Atlantique.' },
      desert: { n: '02', t: 'Traversées du désert', d: 'Ergs, bivouacs, caravanes, et le silence que l’on traverse un continent pour entendre.' },
      culture: { n: '03', t: 'Culture', d: 'Cités de pierre, bibliothèques familiales, repas partagés et huit siècles d’hospitalité.' },
      landscapes: { n: '04', t: 'Paysages', d: 'Canyons, oasis, bancs de sable et l’endroit où le Sahara tombe dans l’océan.' },
      travellers: { n: '05', t: 'Voyageurs', d: 'Ceux qui sont venus avec nous, et ce que ce pays a fait d’eux.' },
    },
    ui: { openImage: 'Ouvrir la photographie', of: 'sur', jump: 'Aller au chapitre' },
  },

  aboutPage: {
    hero: {
      eyebrow: 'Qui nous sommes',
      title: 'Une agence mauritanienne, dans un pays qui en avait besoin.',
      sub: 'Travel and Trips in Mauritania existe pour que les voyageurs qui arrivent ici rencontrent le pays \u00e0 travers ceux qui y vivent.',
      img: 'flag-and-camels',
    },
    story: {
      eyebrow: 'Notre histoire',
      title: 'Notre histoire',
      body: [],
      img: 'guide-and-traveller-ridge',
    },
    pillars: {
      eyebrow: 'Ce que nous d\u00e9fendons',
      title: 'Ce que nous d\u00e9fendons',
      items: [],
    },
    guides: {
      eyebrow: 'Nos guides',
      title: 'Nos guides',
      body: [],
      img: 'plateau-two-travellers',
      stats: [],
    },
    safety: {
      eyebrow: 'Voyager en s\u00e9curit\u00e9',
      title: 'Voyager en s\u00e9curit\u00e9',
      items: [],
      img: 'beach-convoy',
    },
    mission: {
      eyebrow: 'Notre mission',
      quote: 'Montrer la Mauritanie au monde sans changer ce qui m\u00e9rite d\u2019\u00eatre montr\u00e9.',
      body: '',
      cta: 'Pr\u00e9parez votre voyage avec nous',
      waMsg: 'Bonjour, je souhaite pr\u00e9parer un voyage en Mauritanie.',
    },
  },

  guidePage: {
    hero: {
      eyebrow: 'Avant de venir',
      title: 'Guide de voyage Mauritanie',
      sub: 'Tout ce que les voyageurs nous demandent, répondu honnêtement. S’il reste une zone d’ombre, écrivez-nous : nous répondons personnellement.',
      img: 'adrar-road-mesa',
    },
    sections: [
      {
        id: 'when',
        t: 'Quand partir en Mauritanie',
        body: [
          'La saison va d’**octobre à avril**. Les journées sont à 22–32 °C, les nuits dans le désert descendent à 8–15 °C, et la lumière est à son meilleur. Décembre et janvier sont les mois les plus frais et les plus demandés.',
          'De **mai à septembre**, l’intérieur dépasse régulièrement 45 °C et voyager dans le désert devient réellement pénible et, par endroits, dangereux.',
          'L’**harmattan**, un vent de poussière sec, peut réduire la visibilité pendant quelques jours entre décembre et février. La côte reste plus douce et plus ventée toute l’année : le Banc d’Arguin et Nouakchott restent agréables hors du plein été.',
        ],
      },
      {
        id: 'visa',
        t: 'Visa et entrée',
        body: [
          'La plupart des voyageurs européens et nord-américains obtiennent un **visa à l’arrivée** à l’aéroport international de Nouakchott–Oumtounsy et aux principaux postes frontières terrestres. Il est délivré sur place, généralement valable 30 jours, et payé en **euros en espèces**.',
          'Il vous faut un passeport valable au moins six mois, un billet de sortie ou de retour et une adresse dans le pays.',
          'Les règles et les tarifs peuvent changer sans grand préavis, et certaines nationalités doivent obtenir un visa à l’avance. Vérifiez les conditions en vigueur pour votre passeport avant de réserver.',
        ],
      },
      {
        id: 'pack',
        t: 'Que mettre dans son sac',
        body: [
          '**Vêtements.** Des couches légères, amples et couvrantes pour la journée ; une polaire ou une veste chaude et un pantalon long pour les nuits du désert, réellement froides de décembre à février. Un foulard ou *chèche* est l’objet le plus utile que vous posséderez — contre le soleil, la poussière et le vent.',
          '**Chaussures.** Des chaussures de marche fermées, plus des sandales pour le campement et le sable. Emportez plus de chaussettes que prévu.',
          '**Soleil et poussière.** Crème solaire à indice élevé, baume à lèvres, lunettes de soleil, et une housse étanche pour les appareils photo — le sable fin s’infiltre partout.',
          '**Pratique.** Lampe frontale, batterie externe (il n’y a pas d’électricité au bivouac), adaptateur universel, gourde, médicaments personnels, lingettes et une petite trousse de secours.',
          '**Argent.** Emportez des euros en espèces. Les cartes ne sont acceptées presque nulle part hors de quelques hôtels de Nouakchott, et les distributeurs sont peu fiables. La monnaie locale est l’ouguiya (MRU).',
        ],
      },
      {
        id: 'safety',
        t: 'La sécurité en Mauritanie',
        body: [
          'La Mauritanie est calme, et les régions que visitent les voyageurs — Nouakchott, la côte atlantique, l’Adrar, le corridor ferroviaire — sont considérées comme stables et régulièrement parcourues par des visiteurs européens. Les agressions contre les touristes sont très rares, et la culture d’hospitalité envers l’invité est extrêmement forte.',
          'Les vrais risques ici sont environnementaux, pas politiques : la chaleur, la déshydratation, le sable mou et l’éloignement des secours médicaux. C’est pourquoi le désert se parcourt avec des guides agréés et des véhicules bien équipés, jamais en autonomie.',
          'Prenez une assurance voyage couvrant le désert et consultez les recommandations actuelles de votre gouvernement avant de réserver.',
        ],
      },
      {
        id: 'culture',
        t: 'Culture et traditions',
        body: [
          'La Mauritanie est une république islamique, et la vie quotidienne suit ce rythme : cinq prières, le vendredi comme jour de repos, **aucun alcool dans tout le pays**, et un mois de jeûne pendant le ramadan, où l’on ne mange ni ne boit en public pendant la journée.',
          'Habillez-vous sobrement — épaules et genoux couverts, pour tout le monde. Les femmes ne sont pas tenues de se couvrir les cheveux, mais un foulard est utile et apprécié dans les villages et les mosquées.',
          'Saluez avant de demander quoi que ce soit : une poignée de main et quelques mots sur la santé et la famille précèdent toute affaire. Acceptez toujours le thé s’il vous est offert ; les trois verres prennent une heure et les refuser est la seule chose qui surprenne vraiment.',
          '**Photographie.** Demandez avant de photographier quelqu’un, surtout les femmes, et acceptez un refus. Ne photographiez jamais les postes militaires, les checkpoints ou les bâtiments officiels. Votre guide vous dira quand c’est possible.',
          'Mangez et donnez de la main droite. Et si l’on vous invite chez quelqu’un, vous serez nourri bien au-delà de vos capacités — ce n’est pas facultatif.',
        ],
      },
      {
        id: 'transport',
        t: 'Se déplacer',
        body: [
          '**Vols.** Nouakchott–Oumtounsy (NKC) est la porte d’entrée principale, avec des liaisons depuis Paris, Casablanca, Istanbul, Madrid et Dakar. Des charters saisonniers desservent parfois directement Atar en hiver.',
          '**Par la route.** La route Nouakchott–Atar est goudronnée et prend environ six heures. Au-delà, tout est piste et exige un 4×4. Les distances sont longues et les stations-service très espacées.',
          '**Le train du fer.** Gratuit, inoubliable et totalement non réglementé. Ce n’est pas à tenter sans guide, sans matériel et sans nourriture.',
        ],
      },
    ],
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'La Mauritanie est-elle sûre pour les touristes ?', a: 'Les régions que visitent les voyageurs — Nouakchott, la côte atlantique, l’Adrar et le corridor ferroviaire — sont calmes et régulièrement parcourues par des visiteurs européens, et les agressions contre les touristes sont très rares. Les vrais risques sont environnementaux : chaleur, déshydratation, sable mou et éloignement des secours, raison pour laquelle le désert se parcourt avec des guides agréés et des véhicules bien équipés. Consultez les recommandations actuelles de votre gouvernement avant de réserver.' },
      { q: 'Ai-je besoin d’un visa ?', a: 'La plupart des voyageurs européens et nord-américains obtiennent un visa à l’arrivée à l’aéroport international de Nouakchott–Oumtounsy et aux principaux postes frontières, délivré sur place, généralement valable 30 jours et payé en euros espèces. Les règles changent et certaines nationalités doivent l’obtenir à l’avance : vérifiez pour votre passeport avant de réserver.' },
      { q: 'Quelle est la meilleure période ?', a: 'D’octobre à avril. Les journées sont à 22–32 °C et les nuits du désert descendent à 8–15 °C. Décembre et janvier sont les plus frais. De mai à septembre, l’intérieur dépasse régulièrement 45 °C.' },
      { q: 'Peut-on vraiment monter dans le train du fer ?', a: 'Oui. Le train transporte le minerai de Zouérat à Nouadhibou et les voyageurs voyagent sur le minerai, dans les wagons ouverts, gratuitement. Le trajet dure environ douze heures, sans aucun abri, et la nuit du désert est réellement froide.' },
      { q: 'Y a-t-il du réseau et de l’internet ?', a: 'En ville, oui, et c’est bon marché. Dans le désert profond et dans le train, non.' },
      { q: 'Comment se passe l’argent ?', a: 'La monnaie locale est l’ouguiya (MRU). Emportez des euros en espèces : les cartes ne sont acceptées presque nulle part hors de quelques hôtels de Nouakchott, et les distributeurs sont peu fiables.' },
      { q: 'Trouve-t-on de l’alcool ?', a: 'Non. La Mauritanie est une république islamique et l’alcool n’est vendu nulle part dans le pays.' },
    ],
    cta: {
      title: 'Une question reste sans réponse ?',
      sub: 'Écrivez-nous directement. Nous vous répondrons.',
      cta: 'Posez votre question sur WhatsApp',
      waMsg: 'Bonjour, j’ai une question sur un voyage en Mauritanie.',
    },
  },

  contactPage: {
    hero: {
      eyebrow: 'Nous contacter',
      title: 'Préparons votre voyage.',
      sub: 'Dites-nous qui voyage, à peu près quand, et ce que vous rêvez de voir. Nous reviendrons vers vous.',
      img: 'dune-sunset-crew',
    },
    methods: {
      whatsapp: { t: 'WhatsApp', d: 'Le moyen le plus rapide de nous joindre.', a: 'Démarrer la conversation' },
      email: { t: 'E-mail', d: 'Pour les itinéraires détaillés, les documents et les groupes.', a: 'Nous écrire' },
      phone: { t: 'Téléphone', d: 'Appelez-nous directement.', a: 'Appeler' },
      location: { t: 'Où nous sommes', d: 'Nouakchott, Mauritanie.', a: 'Ouvrir dans Google Maps' },
    },
    map: { t: 'Nous trouver', d: 'Notre bureau est à Nouakchott. Touchez la carte pour l’itinéraire, les horaires et le profil Google complet.' },
    form: {
      eyebrow: 'Demande',
      title: 'Parlez-nous de votre voyage.',
      sub: 'Ce formulaire ouvre WhatsApp avec votre message prêt à envoyer : rien ne se perd dans un dossier de spam.',
      name: 'Votre nom',
      namePh: 'Anna Rossi',
      email: 'E-mail',
      emailPh: 'vous@exemple.com',
      country: 'Pays',
      countryPh: 'France',
      people: 'Voyageurs',
      dates: 'Dates approximatives',
      datesPh: 'Février 2027, environ 10 jours',
      interest: 'Ce qui vous intéresse le plus',
      interestOptions: ['L’aventure du train du fer', 'Expédition dans le Sahara', 'Chinguetti, voyage au patrimoine', 'Ouadane, la cité ancienne', 'Découverte du Banc d’Arguin', 'Un voyage privé sur mesure', 'Je ne sais pas encore'],
      message: 'Autre chose à nous signaler',
      messagePh: 'Condition physique, niveau de confort, régime alimentaire, occasions spéciales…',
      submit: 'Envoyer via WhatsApp',
      submitAlt: 'ou envoyer le même message par e-mail',
      required: 'Merci d’indiquer votre nom et ce qui vous intéresse.',
      intro: 'Bonjour, je souhaite préparer un voyage en Mauritanie.',
    },
    promise: {
      t: 'Ce qui se passe ensuite',
      items: [],
    },
  },

  reviewsUi: {
    photo: 'photo',
    photos: 'photos',
    ownerReply: 'Réponse du propriétaire',
    onGoogle: 'Lire sur Google',
    reviewsOnGoogle: 'avis sur Google',
    viewProfile: 'Voir tous les avis',
    prev: 'Avis précédent',
    next: 'Avis suivant',
  },

  reviewsPage: {
    hero: {
      eyebrow: 'En leurs mots',
      title: 'Avis',
      sub: 'Chaque avis ci-dessous est un véritable avis Google, présenté tel qu’il a été écrit — avec les mots de son auteur, sous son propre nom.',
      img: 'dune-summit-people',
    },
    cta: {
      title: 'Venez écrire le prochain.',
      sub: 'Dites-nous quand vous souhaitez partir et nous construirons l’itinéraire autour de vous.',
      cta: 'Préparez votre voyage',
      waMsg: 'Bonjour, j’ai lu vos avis et je souhaite préparer un voyage en Mauritanie.',
    },
  },

  footer: {
    tagline: 'Voyages privés guidés par des locaux à travers le Sahara, les cités anciennes et la côte atlantique de la Mauritanie.',
    explore: 'Explorer',
    company: 'L’agence',
    contact: 'Contact',
    follow: 'Suivre le voyage',
    rights: 'Tous droits réservés.',
    built: 'Chaque photographie de ce site a été prise pendant nos propres voyages.',
    waMsg: 'Bonjour, je souhaite des informations sur vos voyages en Mauritanie.',
  },

  a11y: {
    skip: 'Aller au contenu',
    heroSlides: 'Photographies principales',
    lightbox: 'Visionneuse de photographies',
    menu: 'Menu principal',
  },
};
